// Code generated by helix-gen. DO NOT EDIT.

use std::collections::HashMap;
use thrift::protocol::{TInputProtocol, TOutputProtocol, TSerializable, TFieldIdentifier, TStructIdentifier, TType};
use thrift::Error as ThriftError;

#[derive(Clone, PartialEq, ::prost::Message, ::serde::Serialize, ::serde::Deserialize)]
pub struct UserProfile {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub username: String,
    #[prost(string, tag = "3")]
    pub email: String,
}

impl TSerializable for UserProfile {
    fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Self> {
        i_prot.read_struct_begin()?;
        let mut var_user_id: Option<i64> = None;
        let mut var_username: Option<String> = None;
        let mut var_email: Option<String> = None;
        loop {
            let field_ident = i_prot.read_field_begin()?;
            if field_ident.field_type == TType::Stop {
                break;
            }
            let field_id = field_ident.id.unwrap_or(0);
            match field_id {
                1 => {
                    let val = i_prot.read_i64()?;
                    var_user_id = Some(val);
                }
                2 => {
                    let val = i_prot.read_string()?;
                    var_username = Some(val);
                }
                3 => {
                    let val = i_prot.read_string()?;
                    var_email = Some(val);
                }
                _ => {
                    i_prot.skip(field_ident.field_type)?;
                }
            }
            i_prot.read_field_end()?;
        }
        i_prot.read_struct_end()?;
        Ok(Self {
            user_id: var_user_id.unwrap_or_default(),
            username: var_username.unwrap_or_default(),
            email: var_email.unwrap_or_default(),
        })
    }

    fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
        o_prot.write_struct_begin(&TStructIdentifier::new("UserProfile"))?;
        o_prot.write_field_begin(&TFieldIdentifier::new("user_id", TType::I64, Some(1)))?;
        o_prot.write_i64(self.user_id)?;
        o_prot.write_field_end()?;
        o_prot.write_field_begin(&TFieldIdentifier::new("username", TType::String, Some(2)))?;
        o_prot.write_string(&self.username)?;
        o_prot.write_field_end()?;
        o_prot.write_field_begin(&TFieldIdentifier::new("email", TType::String, Some(3)))?;
        o_prot.write_string(&self.email)?;
        o_prot.write_field_end()?;
        o_prot.write_field_stop()?;
        o_prot.write_struct_end()?;
        Ok(())
    }
}

#[async_trait::async_trait]
pub trait UserProfileService: Send + Sync + 'static {
    async fn get_user_profile(&self, req: UserProfile) -> Result<UserProfile, ThriftError>;
}

