apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helixschemas.helixrpc.io
spec:
  group: helixrpc.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                idlContent:
                  type: string
                  description: "Raw Protobuf/Thrift IDL content"
                language:
                  type: string
                  description: "Target compilation language (go, rust, python, node)"
                outputDirectory:
                  type: string
                  description: "Relative directory path where stubs will be generated"
              required:
                - idlContent
                - language
                - outputDirectory
  scope: Namespaced
  names:
    plural: helixschemas
    singular: helixschema
    kind: HelixSchema
    shortNames:
      - hs
