// Automatically generated by Helix RPC. DO NOT EDIT.
#pragma once

#include <string>
#include <vector>
#include <string_view>
#include <stdexcept>
#include <cstdint>

namespace helix {

inline uint64_t ReadVarint(const uint8_t* buf, size_t size, size_t& idx) {
    uint64_t v = 0;
    int shift = 0;
    while (true) {
        if (idx >= size) throw std::runtime_error("unexpected EOF reading varint");
        uint8_t b = buf[idx++];
        v |= static_cast<uint64_t>(b & 0x7f) << shift;
        if ((b & 0x80) == 0) break;
        shift += 7;
    }
    return v;
}

inline void WriteThriftVarint(std::vector<uint8_t>& out, uint64_t v) {
    while (true) {
        if ((v & ~0x7FULL) == 0) {
            out.push_back(static_cast<uint8_t>(v));
            break;
        }
        out.push_back(static_cast<uint8_t>((v & 0x7F) | 0x80));
        v >>= 7;
    }
}

inline void WriteThriftI16(std::vector<uint8_t>& out, uint16_t v) {
    out.push_back(static_cast<uint8_t>((v >> 8) & 0xFF));
    out.push_back(static_cast<uint8_t>(v & 0xFF));
}

inline const uint8_t* FastScanField(const uint8_t* buf, size_t size, int target_field, size_t& out_len, int& out_wire_type) {
    size_t idx = 0;
    while (idx < size) {
        uint64_t tag = ReadVarint(buf, size, idx);
        int field_num = static_cast<int>(tag >> 3);
        int wire_type = static_cast<int>(tag & 0x7);
        if (field_num == target_field) {
            out_wire_type = wire_type;
            if (wire_type == 2) {
                uint64_t len = ReadVarint(buf, size, idx);
                out_len = static_cast<size_t>(len);
                if (idx + out_len > size) throw std::runtime_error("unexpected EOF");
                return buf + idx;
            } else if (wire_type == 0) {
                size_t start = idx;
                ReadVarint(buf, size, idx);
                out_len = idx - start;
                return buf + start;
            }
            throw std::runtime_error("unsupported wire type in fast scan");
        }
        if (wire_type == 0) {
            ReadVarint(buf, size, idx);
        } else if (wire_type == 2) {
            uint64_t len = ReadVarint(buf, size, idx);
            idx += static_cast<size_t>(len);
        } else {
            throw std::runtime_error("unknown wire type in fast scan skip");
        }
    }
    throw std::runtime_error("field not found");
}

struct UserProfile {
    int64_t user_id;
    std::string username;
    std::string email;

    static std::vector<uint8_t> TranspileProtobufToThriftCompact(const uint8_t* input, size_t size) {
        std::vector<uint8_t> out;
        size_t idx = 0;
        int last_field = 0;
        while (idx < size) {
            uint64_t tag = ReadVarint(input, size, idx);
            int field_num = static_cast<int>(tag >> 3);
            int wire_type = static_cast<int>(tag & 0x7);
            int delta = field_num - last_field;
            switch (field_num) {
                case 1: {
                    uint64_t val = ReadVarint(input, size, idx);
                    if (delta > 0 && delta <= 15) { out.push_back(static_cast<uint8_t>((delta << 4) | 0x06)); }
                    else { out.push_back(0x06); WriteThriftI16(out, 1); }
                    WriteThriftVarint(out, (val << 1) ^ (val >> 63));
                    last_field = field_num;
                    break;
                }
                case 2: {
                    uint64_t len = ReadVarint(input, size, idx);
                    if (delta > 0 && delta <= 15) { out.push_back(static_cast<uint8_t>((delta << 4) | 0x08)); }
                    else { out.push_back(0x08); WriteThriftI16(out, 2); }
                    WriteThriftVarint(out, len);
                    out.insert(out.end(), input + idx, input + idx + len);
                    idx += len;
                    last_field = field_num;
                    break;
                }
                case 3: {
                    uint64_t len = ReadVarint(input, size, idx);
                    if (delta > 0 && delta <= 15) { out.push_back(static_cast<uint8_t>((delta << 4) | 0x08)); }
                    else { out.push_back(0x08); WriteThriftI16(out, 3); }
                    WriteThriftVarint(out, len);
                    out.insert(out.end(), input + idx, input + idx + len);
                    idx += len;
                    last_field = field_num;
                    break;
                }
                default:
                    if (wire_type == 0) ReadVarint(input, size, idx);
                    else if (wire_type == 2) { uint64_t len = ReadVarint(input, size, idx); idx += len; }
                    break;
            }
        }
        out.push_back(0x00);
        return out;
    }
};

class LazyUserProfile {
public:
    LazyUserProfile(const uint8_t* raw, size_t size) : raw_(raw), size_(size) {}

    int64_t get_user_id() const {
        size_t len = 0; int wt = 0;
        const uint8_t* ptr = FastScanField(raw_, size_, 1, len, wt);
        size_t idx = 0;
        return static_cast<int64_t>(ReadVarint(ptr, len, idx));
    }

    std::string_view get_username() const {
        size_t len = 0; int wt = 0;
        const uint8_t* ptr = FastScanField(raw_, size_, 2, len, wt);
        return std::string_view(reinterpret_cast<const char*>(ptr), len);
    }

    std::string_view get_email() const {
        size_t len = 0; int wt = 0;
        const uint8_t* ptr = FastScanField(raw_, size_, 3, len, wt);
        return std::string_view(reinterpret_cast<const char*>(ptr), len);
    }

private:
    const uint8_t* raw_;
    size_t size_;
};

} // namespace helix
