// Automatically generated by Helix RPC. DO NOT EDIT.
package io.helixrpc.generated;

import java.util.List;
import java.util.NoSuchElementException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Flow;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import org.apache.thrift.TBase;
import org.apache.thrift.TException;
import org.apache.thrift.protocol.TField;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.protocol.TProtocolUtil;
import org.apache.thrift.protocol.TStruct;
import org.apache.thrift.protocol.TType;

class HelixHelpers {
    public static long readVarint(ByteBuffer buf) {
        long v = 0;
        int shift = 0;
        while (true) {
            byte b = buf.get();
            v |= (long)(b & 0x7F) << shift;
            if ((b & 0x80) == 0) break;
            shift += 7;
        }
        return v;
    }

    public static void writeThriftVarint(ByteBuffer buf, long v) {
        while (true) {
            if ((v & ~0x7FL) == 0) {
                buf.put((byte)v);
                break;
            }
            buf.put((byte)((v & 0x7F) | 0x80));
            v >>>= 7;
        }
    }

    public static void writeThriftI16(ByteBuffer buf, int v) {
        buf.put((byte)((v >> 8) & 0xFF));
        buf.put((byte)(v & 0xFF));
    }

    public static ByteBuffer fastScanField(ByteBuffer buf, int targetField, int[] outWireType) {
        ByteBuffer dup = buf.duplicate();
        while (dup.hasRemaining()) {
            long tag = readVarint(dup);
            int fieldNum = (int)(tag >>> 3);
            int wireType = (int)(tag & 0x7);
            if (fieldNum == targetField) {
                outWireType[0] = wireType;
                if (wireType == 2) {
                    long len = readVarint(dup);
                    int start = dup.position();
                    dup.limit(start + (int)len);
                    return dup.slice();
                } else if (wireType == 0) {
                    int start = dup.position();
                    readVarint(dup);
                    int end = dup.position();
                    ByteBuffer slice = dup.duplicate();
                    slice.position(start);
                    slice.limit(end);
                    return slice.slice();
                }
                throw new RuntimeException("unsupported wireType: " + wireType);
            }
            if (wireType == 0) {
                readVarint(dup);
            } else if (wireType == 2) {
                long len = readVarint(dup);
                dup.position(dup.position() + (int)len);
            } else {
                throw new RuntimeException("unknown wireType: " + wireType);
            }
        }
        throw new NoSuchElementException("field not found");
    }
}

public class UserProfile implements TBase<UserProfile, UserProfile._Fields> {
    public int id;
    public String username;
    public long created_at;

    public static ByteBuffer transpileProtobufToThriftCompact(ByteBuffer input, ByteBuffer output) {
        ByteBuffer out = output.duplicate();
        ByteBuffer in = input.duplicate();
        int lastField = 0;
        while (in.hasRemaining()) {
            long tag = HelixHelpers.readVarint(in);
            int fieldNum = (int)(tag >>> 3);
            int wireType = (int)(tag & 0x7);
            int delta = fieldNum - lastField;
            switch (fieldNum) {
                case 1: {
                    long val = HelixHelpers.readVarint(in);
                    if (delta > 0 && delta <= 15) { out.put((byte)((delta << 4) | 0x05)); }
                    else { out.put((byte)0x05); HelixHelpers.writeThriftI16(out, 1); }
                    HelixHelpers.writeThriftVarint(out, (val << 1) ^ (val >> 31));
                    lastField = fieldNum;
                    break;
                }
                case 2: {
                    long len = HelixHelpers.readVarint(in);
                    if (delta > 0 && delta <= 15) { out.put((byte)((delta << 4) | 0x08)); }
                    else { out.put((byte)0x08); HelixHelpers.writeThriftI16(out, 2); }
                    HelixHelpers.writeThriftVarint(out, len);
                    byte[] sBytes = new byte[(int)len];
                    in.get(sBytes);
                    out.put(sBytes);
                    lastField = fieldNum;
                    break;
                }
                case 3: {
                    long val = HelixHelpers.readVarint(in);
                    if (delta > 0 && delta <= 15) { out.put((byte)((delta << 4) | 0x06)); }
                    else { out.put((byte)0x06); HelixHelpers.writeThriftI16(out, 3); }
                    HelixHelpers.writeThriftVarint(out, (val << 1) ^ (val >> 63));
                    lastField = fieldNum;
                    break;
                }
                default:
                    if (wireType == 0) HelixHelpers.readVarint(in);
                    else if (wireType == 2) { long len = HelixHelpers.readVarint(in);
                    in.position(in.position() + (int)len); }
                    break;
            }
        }
        out.put((byte)0x00);
        out.flip();
        return out;
    }


    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        ID((short)1, "id"),
        USERNAME((short)2, "username"),
        CREATED_AT((short)3, "created_at");

        private final short _thriftId;
        private final String _fieldName;
        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }
        public short getThriftFieldId() { return _thriftId; }
        public String getFieldName() { return _fieldName; }
    }

    public void read(TProtocol iprot) throws TException {
        iprot.readStructBegin();
        while (true) {
            TField field = iprot.readFieldBegin();
            if (field.type == TType.STOP) { break; }
            switch (field.id) {
                case 1: // id
                    if (field.type == TType.I32) {
                        this.id = iprot.readI32();
                    } else { TProtocolUtil.skip(iprot, field.type); }
                    break;
                case 2: // username
                    if (field.type == TType.STRING) {
                        this.username = iprot.readString();
                    } else { TProtocolUtil.skip(iprot, field.type); }
                    break;
                case 3: // created_at
                    if (field.type == TType.I64) {
                        this.created_at = iprot.readI64();
                    } else { TProtocolUtil.skip(iprot, field.type); }
                    break;
                default:
                    TProtocolUtil.skip(iprot, field.type);
            }
            iprot.readFieldEnd();
        }
        iprot.readStructEnd();
    }

    public void write(TProtocol oprot) throws TException {
        oprot.writeStructBegin(new TStruct("UserProfile"));
        oprot.writeFieldBegin(new TField("id", TType.I32, (short)1));
        oprot.writeI32(this.id);
        oprot.writeFieldEnd();
        oprot.writeFieldBegin(new TField("username", TType.STRING, (short)2));
        if (this.username != null) oprot.writeString(this.username);
        oprot.writeFieldEnd();
        oprot.writeFieldBegin(new TField("created_at", TType.I64, (short)3));
        oprot.writeI64(this.created_at);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
    }

    public void clear() {
        this.id = 0;
        this.username = null;
        this.created_at = 0;
    }

    public UserProfile deepCopy() {
        UserProfile copy = new UserProfile();
        copy.id = this.id;
        copy.username = this.username;
        copy.created_at = this.created_at;
        return copy;
    }

    public int compareTo(UserProfile other) {
        return 0; // Not fully implemented
    }

    public _Fields fieldForId(int fieldId) { return null; }
    public boolean isSet(_Fields field) { return true; }
    public Object getFieldValue(_Fields field) { return null; }
    public void setFieldValue(_Fields field, Object value) {}

    public void writeTo(CodedOutputStream output) throws IOException {
        if (this.id != 0) output.writeInt32(1, this.id);
        if (this.username != null && !this.username.isEmpty()) output.writeString(2, this.username);
        if (this.created_at != 0L) output.writeInt64(3, this.created_at);
    }

    public int getSerializedSize() {
        int size = 0;
        if (this.id != 0) size += CodedOutputStream.computeInt32Size(1, this.id);
        if (this.username != null && !this.username.isEmpty()) size += CodedOutputStream.computeStringSize(2, this.username);
        if (this.created_at != 0L) size += CodedOutputStream.computeInt64Size(3, this.created_at);
        return size;
    }

    public static UserProfile parseFrom(byte[] data) throws IOException {
        return parseFrom(CodedInputStream.newInstance(data));
    }

    public static UserProfile parseFrom(CodedInputStream input) throws IOException {
        UserProfile msg = new UserProfile();
        while (true) {
            int tag = input.readTag();
            if (tag == 0) break;
            switch (tag) {
                case 8:
                    msg.id = input.readInt32();
                    break;
                case 18:
                    msg.username = input.readString();
                    break;
                case 24:
                    msg.created_at = input.readInt64();
                    break;
                default:
                    input.skipField(tag);
            }
        }
        return msg;
    }

    public static class Lazy {
        private final ByteBuffer raw;
        public Lazy(ByteBuffer raw) { this.raw = raw; }

        public int getID() {
            ByteBuffer b = HelixHelpers.fastScanField(raw, 1, new int[1]);
            return (int)HelixHelpers.readVarint(b);
        }

        public String getUsername() {
            ByteBuffer b = HelixHelpers.fastScanField(raw, 2, new int[1]);
            byte[] bytes = new byte[b.remaining()];
            b.get(bytes);
            return new String(bytes, StandardCharsets.UTF_8);
        }

        public long getCreatedAt() {
            ByteBuffer b = HelixHelpers.fastScanField(raw, 3, new int[1]);
            return HelixHelpers.readVarint(b);
        }

    }
}

public interface UserService {
    CompletableFuture<UserProfile> getUser(UserProfile request);
    Flow.Publisher<UserProfile> streamUsers(Flow.Publisher<UserProfile> request);
}

