# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_completion.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'chat_completion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63hat_completion.proto\x12\x0bopenai.chat\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"b\n\x15\x43hatCompletionRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12*\n\x08messages\x18\x02 \x03(\x0b\x32\x18.openai.chat.ChatMessage\x12\x0e\n\x06stream\x18\x03 \x01(\x08\"\x90\x01\n\x14\x43hatCompletionChoice\x12\r\n\x05index\x18\x01 \x01(\x05\x12)\n\x07message\x18\x02 \x01(\x0b\x32\x18.openai.chat.ChatMessage\x12\'\n\x05\x64\x65lta\x18\x03 \x01(\x0b\x32\x18.openai.chat.ChatMessage\x12\x15\n\rfinish_reason\x18\x04 \x01(\t\"\x88\x01\n\x16\x43hatCompletionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x03\x12\r\n\x05model\x18\x04 \x01(\t\x12\x32\n\x07\x63hoices\x18\x05 \x03(\x0b\x32!.openai.chat.ChatCompletionChoice2\xdf\x01\n\x15\x43hatCompletionService\x12\x61\n\x14\x43reateChatCompletion\x12\".openai.chat.ChatCompletionRequest\x1a#.openai.chat.ChatCompletionResponse\"\x00\x12\x63\n\x14StreamChatCompletion\x12\".openai.chat.ChatCompletionRequest\x1a#.openai.chat.ChatCompletionResponse\"\x00\x30\x01\x42\x41Z?github.com/helix-rpc/helix/integration-tests/schema/openai_chatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_completion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/helix-rpc/helix/integration-tests/schema/openai_chat'
  _globals['_CHATMESSAGE']._serialized_start=38
  _globals['_CHATMESSAGE']._serialized_end=82
  _globals['_CHATCOMPLETIONREQUEST']._serialized_start=84
  _globals['_CHATCOMPLETIONREQUEST']._serialized_end=182
  _globals['_CHATCOMPLETIONCHOICE']._serialized_start=185
  _globals['_CHATCOMPLETIONCHOICE']._serialized_end=329
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_start=332
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_end=468
  _globals['_CHATCOMPLETIONSERVICE']._serialized_start=471
  _globals['_CHATCOMPLETIONSERVICE']._serialized_end=694
# @@protoc_insertion_point(module_scope)
