// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package example

import (
	"context"
	"fmt"
)

type UserProfile struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Username string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Email    string `thrift:"email,3" frugal:"3,default,string" json:"email"`
}

func NewUserProfile() *UserProfile {
	return &UserProfile{}
}

func (p *UserProfile) InitDefault() {
}

func (p *UserProfile) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserProfile) GetUsername() (v string) {
	return p.Username
}

func (p *UserProfile) GetEmail() (v string) {
	return p.Email
}
func (p *UserProfile) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserProfile) SetUsername(val string) {
	p.Username = val
}
func (p *UserProfile) SetEmail(val string) {
	p.Email = val
}

func (p *UserProfile) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserProfile(%+v)", *p)
}

var fieldIDToName_UserProfile = map[int16]string{
	1: "user_id",
	2: "username",
	3: "email",
}

type UserProfileService interface {
	GetUserProfile(ctx context.Context, request *UserProfile) (r *UserProfile, err error)
}

type UserProfileServiceGetUserProfileArgs struct {
	Request *UserProfile `thrift:"request,1" frugal:"1,default,UserProfile" json:"request"`
}

func NewUserProfileServiceGetUserProfileArgs() *UserProfileServiceGetUserProfileArgs {
	return &UserProfileServiceGetUserProfileArgs{}
}

func (p *UserProfileServiceGetUserProfileArgs) InitDefault() {
}

var UserProfileServiceGetUserProfileArgs_Request_DEFAULT *UserProfile

func (p *UserProfileServiceGetUserProfileArgs) GetRequest() (v *UserProfile) {
	if !p.IsSetRequest() {
		return UserProfileServiceGetUserProfileArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *UserProfileServiceGetUserProfileArgs) SetRequest(val *UserProfile) {
	p.Request = val
}

func (p *UserProfileServiceGetUserProfileArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserProfileServiceGetUserProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserProfileServiceGetUserProfileArgs(%+v)", *p)
}

var fieldIDToName_UserProfileServiceGetUserProfileArgs = map[int16]string{
	1: "request",
}

type UserProfileServiceGetUserProfileResult struct {
	Success *UserProfile `thrift:"success,0,optional" frugal:"0,optional,UserProfile" json:"success,omitempty"`
}

func NewUserProfileServiceGetUserProfileResult() *UserProfileServiceGetUserProfileResult {
	return &UserProfileServiceGetUserProfileResult{}
}

func (p *UserProfileServiceGetUserProfileResult) InitDefault() {
}

var UserProfileServiceGetUserProfileResult_Success_DEFAULT *UserProfile

func (p *UserProfileServiceGetUserProfileResult) GetSuccess() (v *UserProfile) {
	if !p.IsSetSuccess() {
		return UserProfileServiceGetUserProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserProfileServiceGetUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserProfile)
}

func (p *UserProfileServiceGetUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserProfileServiceGetUserProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserProfileServiceGetUserProfileResult(%+v)", *p)
}

var fieldIDToName_UserProfileServiceGetUserProfileResult = map[int16]string{
	0: "success",
}
