// Code generated by Kitex v0.16.2. DO NOT EDIT.
package userprofileservice

import (
	server "github.com/cloudwego/kitex/server"
	example "github.com/helix-rpc/helix/tests/go-go/kitex_gen/helix/example"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler example.UserProfileService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler example.UserProfileService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
