# Code generated by helix-gen. DO NOT EDIT.
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, AsyncIterator
from abc import ABC, abstractmethod
import struct as _struct

def _read_varint(buf: memoryview, idx: int):
    v, shift = 0, 0
    while True:
        if idx >= len(buf): raise EOFError('unexpected EOF reading varint')
        b = buf[idx]; idx += 1
        v |= (b & 0x7f) << shift
        if (b & 0x80) == 0: break
        shift += 7
    return v, idx

def _write_thrift_varint(out: bytearray, v: int) -> None:
    while True:
        if (v & ~0x7F) == 0: out.append(v); break
        out.append((v & 0x7F) | 0x80); v >>= 7

def _write_thrift_i16(out: bytearray, v: int) -> None:
    out.append((v >> 8) & 0xFF); out.append(v & 0xFF)

def _fast_scan_field(raw: memoryview, target_field: int):
    idx = 0
    while idx < len(raw):
        tag, idx = _read_varint(raw, idx)
        field_num = tag >> 3
        wire_type = tag & 0x7
        if field_num == target_field:
            if wire_type == 2:
                length, idx = _read_varint(raw, idx)
                return raw[idx:idx+length], wire_type
            elif wire_type == 0:
                start = idx
                _, idx = _read_varint(raw, idx)
                return raw[start:idx], wire_type
            raise ValueError(f'unsupported wire_type {wire_type}')
        if wire_type == 0: _, idx = _read_varint(raw, idx)
        elif wire_type == 2:
            length, idx = _read_varint(raw, idx)
            idx += length
        else: raise ValueError(f'unknown wire_type {wire_type}')
    raise KeyError(f'field {target_field} not found')

@dataclass
class UserProfile:
    user_id: int
    username: str
    email: str

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_username = self.username.encode('utf-8') if self.username else b''
        if str_username:
            dynamic_size += 4 + len(str_username)
        str_email = self.email.encode('utf-8') if self.email else b''
        if str_email:
            dynamic_size += 4 + len(str_email)
        table_size = 24
        vtable_size = 10
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        struct.pack_into('<q', buf, 4 + 8, self.user_id or 0)
        if str_username:
            rel_offset = current_string_offset - (4 + 16)
            struct.pack_into('<I', buf, 4 + 16, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_username))
            buf[current_string_offset+4 : current_string_offset+4+len(str_username)] = str_username
            current_string_offset += 4 + len(str_username)
        if str_email:
            rel_offset = current_string_offset - (4 + 20)
            struct.pack_into('<I', buf, 4 + 20, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_email))
            buf[current_string_offset+4 : current_string_offset+4+len(str_email)] = str_email
            current_string_offset += 4 + len(str_email)
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 8)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 16)
        struct.pack_into('<H', buf, vtable_start + 4 + 4, 20)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'UserProfile':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_user_id = 0
        val_username = ""
        val_email = ""
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 8 <= len(buf):
                    val_user_id = struct.unpack_from('<q', buf, abs_offset)[0]
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_username = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 8 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 8)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_email = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        return cls(
            user_id=val_user_id,
            username=val_username,
            email=val_email,
        )

    @classmethod
    def from_proto(cls, buf: bytes) -> 'UserProfile':
        raw = memoryview(buf)
        val_user_id = 0
        val_username = ""
        val_email = ""
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                val_user_id, idx = _read_varint(raw, idx)
            elif field_num == 2:
                _len, idx = _read_varint(raw, idx); val_username = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            elif field_num == 3:
                _len, idx = _read_varint(raw, idx); val_email = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        return cls(
            user_id=val_user_id,
            username=val_username,
            email=val_email,
        )

class LazyUserProfile:
    __slots__ = ('_raw',)
    def __init__(self, raw: bytes) -> None:
        self._raw = memoryview(raw)
    def get_user_id(self) -> int:
        b, _ = _fast_scan_field(self._raw, 1)
        v, _ = _read_varint(b, 0)
        return v
    def get_username(self) -> str:
        b, _ = _fast_scan_field(self._raw, 2)
        return bytes(b).decode('utf-8')
    def get_email(self) -> str:
        b, _ = _fast_scan_field(self._raw, 3)
        return bytes(b).decode('utf-8')

    @classmethod
    def transpile_protobuf_to_thrift_compact(cls, data: bytes) -> bytes:
        raw = memoryview(data)
        out = bytearray()
        _f_user_id = 0
        _f_username = None
        _f_email = None
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                _f_user_id, idx = _read_varint(raw, idx)
            elif field_num == 2:
                _l, idx = _read_varint(raw, idx); _f_username = bytes(raw[idx:idx+_l]).decode('utf-8'); idx += _l
            elif field_num == 3:
                _l, idx = _read_varint(raw, idx); _f_email = bytes(raw[idx:idx+_l]).decode('utf-8'); idx += _l
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        prev_field = 0
        _delta = 1 - prev_field
        if 0 < _delta <= 15: out.append((_delta << 4) | 6)
        else: out.append(6); _write_thrift_i16(out, 1)
        _zz = (_f_user_id << 1) ^ (_f_user_id >> 63) if _f_user_id < 0 else _f_user_id << 1
        _write_thrift_varint(out, _zz)
        prev_field = 1
        if _f_username is not None:
            _delta = 2 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 2)
            _enc = _f_username.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 2
        if _f_email is not None:
            _delta = 3 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 3)
            _enc = _f_email.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 3
        out.append(0x00)  # Thrift STOP byte
        return bytes(out)

class UserProfileServiceBase(ABC):
    @abstractmethod
    async def GetUserProfile(self, request: 'UserProfile') -> 'UserProfile':
        pass

