// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: chat_completion.proto

package openai_chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_completion_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Stream        bool                   `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_chat_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_chat_completion_proto_rawDescGZIP(), []int{1}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type ChatCompletionChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Delta         *ChatMessage           `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"` // For streaming
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChoice) Reset() {
	*x = ChatCompletionChoice{}
	mi := &file_chat_completion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChoice) ProtoMessage() {}

func (x *ChatCompletionChoice) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChoice.ProtoReflect.Descriptor instead.
func (*ChatCompletionChoice) Descriptor() ([]byte, []int) {
	return file_chat_completion_proto_rawDescGZIP(), []int{2}
}

func (x *ChatCompletionChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletionChoice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatCompletionChoice) GetDelta() *ChatMessage {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ChatCompletionChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatCompletionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                  `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                  `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*ChatCompletionChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_chat_completion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_chat_completion_proto_rawDescGZIP(), []int{3}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*ChatCompletionChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

var File_chat_completion_proto protoreflect.FileDescriptor

const file_chat_completion_proto_rawDesc = "" +
	"\n" +
	"\x15chat_completion.proto\x12\vopenai.chat\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"{\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x124\n" +
	"\bmessages\x18\x02 \x03(\v2\x18.openai.chat.ChatMessageR\bmessages\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\"\xb5\x01\n" +
	"\x14ChatCompletionChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x122\n" +
	"\amessage\x18\x02 \x01(\v2\x18.openai.chat.ChatMessageR\amessage\x12.\n" +
	"\x05delta\x18\x03 \x01(\v2\x18.openai.chat.ChatMessageR\x05delta\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\"\xad\x01\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12;\n" +
	"\achoices\x18\x05 \x03(\v2!.openai.chat.ChatCompletionChoiceR\achoices2\xdf\x01\n" +
	"\x15ChatCompletionService\x12a\n" +
	"\x14CreateChatCompletion\x12\".openai.chat.ChatCompletionRequest\x1a#.openai.chat.ChatCompletionResponse\"\x00\x12c\n" +
	"\x14StreamChatCompletion\x12\".openai.chat.ChatCompletionRequest\x1a#.openai.chat.ChatCompletionResponse\"\x000\x01BAZ?github.com/helix-rpc/helix/integration-tests/schema/openai_chatb\x06proto3"

var (
	file_chat_completion_proto_rawDescOnce sync.Once
	file_chat_completion_proto_rawDescData []byte
)

func file_chat_completion_proto_rawDescGZIP() []byte {
	file_chat_completion_proto_rawDescOnce.Do(func() {
		file_chat_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_completion_proto_rawDesc), len(file_chat_completion_proto_rawDesc)))
	})
	return file_chat_completion_proto_rawDescData
}

var file_chat_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chat_completion_proto_goTypes = []any{
	(*ChatMessage)(nil),            // 0: openai.chat.ChatMessage
	(*ChatCompletionRequest)(nil),  // 1: openai.chat.ChatCompletionRequest
	(*ChatCompletionChoice)(nil),   // 2: openai.chat.ChatCompletionChoice
	(*ChatCompletionResponse)(nil), // 3: openai.chat.ChatCompletionResponse
}
var file_chat_completion_proto_depIdxs = []int32{
	0, // 0: openai.chat.ChatCompletionRequest.messages:type_name -> openai.chat.ChatMessage
	0, // 1: openai.chat.ChatCompletionChoice.message:type_name -> openai.chat.ChatMessage
	0, // 2: openai.chat.ChatCompletionChoice.delta:type_name -> openai.chat.ChatMessage
	2, // 3: openai.chat.ChatCompletionResponse.choices:type_name -> openai.chat.ChatCompletionChoice
	1, // 4: openai.chat.ChatCompletionService.CreateChatCompletion:input_type -> openai.chat.ChatCompletionRequest
	1, // 5: openai.chat.ChatCompletionService.StreamChatCompletion:input_type -> openai.chat.ChatCompletionRequest
	3, // 6: openai.chat.ChatCompletionService.CreateChatCompletion:output_type -> openai.chat.ChatCompletionResponse
	3, // 7: openai.chat.ChatCompletionService.StreamChatCompletion:output_type -> openai.chat.ChatCompletionResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_chat_completion_proto_init() }
func file_chat_completion_proto_init() {
	if File_chat_completion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_completion_proto_rawDesc), len(file_chat_completion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_completion_proto_goTypes,
		DependencyIndexes: file_chat_completion_proto_depIdxs,
		MessageInfos:      file_chat_completion_proto_msgTypes,
	}.Build()
	File_chat_completion_proto = out.File
	file_chat_completion_proto_goTypes = nil
	file_chat_completion_proto_depIdxs = nil
}
