// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: chat_completion.proto

package openai_chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatCompletionService_CreateChatCompletion_FullMethodName = "/openai.chat.ChatCompletionService/CreateChatCompletion"
	ChatCompletionService_StreamChatCompletion_FullMethodName = "/openai.chat.ChatCompletionService/StreamChatCompletion"
)

// ChatCompletionServiceClient is the client API for ChatCompletionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatCompletionServiceClient interface {
	// Unary completion
	CreateChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	// Streaming completion
	StreamChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionResponse], error)
}

type chatCompletionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatCompletionServiceClient(cc grpc.ClientConnInterface) ChatCompletionServiceClient {
	return &chatCompletionServiceClient{cc}
}

func (c *chatCompletionServiceClient) CreateChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, ChatCompletionService_CreateChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatCompletionServiceClient) StreamChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatCompletionService_ServiceDesc.Streams[0], ChatCompletionService_StreamChatCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, ChatCompletionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCompletionService_StreamChatCompletionClient = grpc.ServerStreamingClient[ChatCompletionResponse]

// ChatCompletionServiceServer is the server API for ChatCompletionService service.
// All implementations must embed UnimplementedChatCompletionServiceServer
// for forward compatibility.
type ChatCompletionServiceServer interface {
	// Unary completion
	CreateChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	// Streaming completion
	StreamChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionResponse]) error
	mustEmbedUnimplementedChatCompletionServiceServer()
}

// UnimplementedChatCompletionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatCompletionServiceServer struct{}

func (UnimplementedChatCompletionServiceServer) CreateChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChatCompletion not implemented")
}
func (UnimplementedChatCompletionServiceServer) StreamChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamChatCompletion not implemented")
}
func (UnimplementedChatCompletionServiceServer) mustEmbedUnimplementedChatCompletionServiceServer() {}
func (UnimplementedChatCompletionServiceServer) testEmbeddedByValue()                               {}

// UnsafeChatCompletionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatCompletionServiceServer will
// result in compilation errors.
type UnsafeChatCompletionServiceServer interface {
	mustEmbedUnimplementedChatCompletionServiceServer()
}

func RegisterChatCompletionServiceServer(s grpc.ServiceRegistrar, srv ChatCompletionServiceServer) {
	// If the following call panics, it indicates UnimplementedChatCompletionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatCompletionService_ServiceDesc, srv)
}

func _ChatCompletionService_CreateChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatCompletionServiceServer).CreateChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatCompletionService_CreateChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatCompletionServiceServer).CreateChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatCompletionService_StreamChatCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatCompletionServiceServer).StreamChatCompletion(m, &grpc.GenericServerStream[ChatCompletionRequest, ChatCompletionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatCompletionService_StreamChatCompletionServer = grpc.ServerStreamingServer[ChatCompletionResponse]

// ChatCompletionService_ServiceDesc is the grpc.ServiceDesc for ChatCompletionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatCompletionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openai.chat.ChatCompletionService",
	HandlerType: (*ChatCompletionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChatCompletion",
			Handler:    _ChatCompletionService_CreateChatCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChatCompletion",
			Handler:       _ChatCompletionService_StreamChatCompletion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat_completion.proto",
}
