// Code generated by Kitex v0.16.2. DO NOT EDIT.

package userprofileservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	example "github.com/helix-rpc/helix/tests/go/kitex_gen/helix/example"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetUserProfile": kitex.NewMethodInfo(
		getUserProfileHandler,
		newUserProfileServiceGetUserProfileArgs,
		newUserProfileServiceGetUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userProfileServiceServiceInfo                = NewServiceInfo()
	userProfileServiceServiceInfoForClient       = NewServiceInfoForClient()
	userProfileServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userProfileServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userProfileServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userProfileServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserProfileService"
	handlerType := (*example.UserProfileService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "example",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func getUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*example.UserProfileServiceGetUserProfileArgs)
	realResult := result.(*example.UserProfileServiceGetUserProfileResult)
	success, err := handler.(example.UserProfileService).GetUserProfile(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserProfileServiceGetUserProfileArgs() interface{} {
	return example.NewUserProfileServiceGetUserProfileArgs()
}

func newUserProfileServiceGetUserProfileResult() interface{} {
	return example.NewUserProfileServiceGetUserProfileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserProfile(ctx context.Context, request *example.UserProfile) (r *example.UserProfile, err error) {
	var _args example.UserProfileServiceGetUserProfileArgs
	_args.Request = request
	var _result example.UserProfileServiceGetUserProfileResult
	if err = p.c.Call(ctx, "GetUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
