# Code generated by helix-gen. DO NOT EDIT.
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, AsyncIterator
from abc import ABC, abstractmethod

@dataclass
class ChatMessage:
    role: str
    content: str

@dataclass
class ChatCompletionRequest:
    model: str
    messages: List['ChatMessage']
    stream: bool

@dataclass
class ChatCompletionChoice:
    index: int
    message: 'ChatMessage'
    delta: 'ChatMessage'
    finish_reason: str

@dataclass
class ChatCompletionResponse:
    id: str
    object: str
    created: int
    model: str
    choices: List['ChatCompletionChoice']

class ChatCompletionServiceBase(ABC):
    @abstractmethod
    async def CreateChatCompletion(self, request: 'ChatCompletionRequest') -> 'ChatCompletionResponse':
        pass

    @abstractmethod
    async def StreamChatCompletion(self, request: 'ChatCompletionRequest') -> AsyncIterator['ChatCompletionResponse']:
        pass

