# Code generated by helix-gen. DO NOT EDIT.
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, AsyncIterator
from abc import ABC, abstractmethod

@dataclass
class ChatMessage:
    role: str
    content: str

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_role = self.role.encode('utf-8') if self.role else b''
        if str_role:
            dynamic_size += 4 + len(str_role)
        str_content = self.content.encode('utf-8') if self.content else b''
        if str_content:
            dynamic_size += 4 + len(str_content)
        table_size = 12
        vtable_size = 8
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        if str_role:
            rel_offset = current_string_offset - (4 + 4)
            struct.pack_into('<I', buf, 4 + 4, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_role))
            buf[current_string_offset+4 : current_string_offset+4+len(str_role)] = str_role
            current_string_offset += 4 + len(str_role)
        if str_content:
            rel_offset = current_string_offset - (4 + 8)
            struct.pack_into('<I', buf, 4 + 8, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_content))
            buf[current_string_offset+4 : current_string_offset+4+len(str_content)] = str_content
            current_string_offset += 4 + len(str_content)
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatMessage':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_role = ""
        val_content = ""
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_role = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_content = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        return cls(
            role=val_role,
            content=val_content,
        )

@dataclass
class ChatCompletionRequest:
    model: str
    messages: List['ChatMessage']
    stream: bool

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_model = self.model.encode('utf-8') if self.model else b''
        if str_model:
            dynamic_size += 4 + len(str_model)
        table_size = 16
        vtable_size = 10
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        if str_model:
            rel_offset = current_string_offset - (4 + 4)
            struct.pack_into('<I', buf, 4 + 4, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_model))
            buf[current_string_offset+4 : current_string_offset+4+len(str_model)] = str_model
            current_string_offset += 4 + len(str_model)
        struct.pack_into('<?', buf, 4 + 12, bool(self.stream))
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        struct.pack_into('<H', buf, vtable_start + 4 + 4, 12)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatCompletionRequest':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_model = ""
        val_messages = 0
        val_stream = False
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_model = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        if 8 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 8)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset < len(buf):
                    val_stream = struct.unpack_from('<?', buf, abs_offset)[0]
        return cls(
            model=val_model,
            messages=val_messages,
            stream=val_stream,
        )

@dataclass
class ChatCompletionChoice:
    index: int
    message: 'ChatMessage'
    delta: 'ChatMessage'
    finish_reason: str

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_finish_reason = self.finish_reason.encode('utf-8') if self.finish_reason else b''
        if str_finish_reason:
            dynamic_size += 4 + len(str_finish_reason)
        table_size = 20
        vtable_size = 12
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        struct.pack_into('<i', buf, 4 + 4, self.index or 0)
        if str_finish_reason:
            rel_offset = current_string_offset - (4 + 16)
            struct.pack_into('<I', buf, 4 + 16, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_finish_reason))
            buf[current_string_offset+4 : current_string_offset+4+len(str_finish_reason)] = str_finish_reason
            current_string_offset += 4 + len(str_finish_reason)
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        struct.pack_into('<H', buf, vtable_start + 4 + 4, 12)
        struct.pack_into('<H', buf, vtable_start + 4 + 6, 16)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatCompletionChoice':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_index = 0
        val_message = 0
        val_delta = 0
        val_finish_reason = ""
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    val_index = struct.unpack_from('<i', buf, abs_offset)[0]
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        if 8 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 8)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        if 10 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 10)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_finish_reason = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        return cls(
            index=val_index,
            message=val_message,
            delta=val_delta,
            finish_reason=val_finish_reason,
        )

@dataclass
class ChatCompletionResponse:
    id: str
    object: str
    created: int
    model: str
    choices: List['ChatCompletionChoice']

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_id = self.id.encode('utf-8') if self.id else b''
        if str_id:
            dynamic_size += 4 + len(str_id)
        str_object = self.object.encode('utf-8') if self.object else b''
        if str_object:
            dynamic_size += 4 + len(str_object)
        str_model = self.model.encode('utf-8') if self.model else b''
        if str_model:
            dynamic_size += 4 + len(str_model)
        table_size = 32
        vtable_size = 14
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        if str_id:
            rel_offset = current_string_offset - (4 + 4)
            struct.pack_into('<I', buf, 4 + 4, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_id))
            buf[current_string_offset+4 : current_string_offset+4+len(str_id)] = str_id
            current_string_offset += 4 + len(str_id)
        if str_object:
            rel_offset = current_string_offset - (4 + 8)
            struct.pack_into('<I', buf, 4 + 8, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_object))
            buf[current_string_offset+4 : current_string_offset+4+len(str_object)] = str_object
            current_string_offset += 4 + len(str_object)
        struct.pack_into('<q', buf, 4 + 16, self.created or 0)
        if str_model:
            rel_offset = current_string_offset - (4 + 24)
            struct.pack_into('<I', buf, 4 + 24, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_model))
            buf[current_string_offset+4 : current_string_offset+4+len(str_model)] = str_model
            current_string_offset += 4 + len(str_model)
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        struct.pack_into('<H', buf, vtable_start + 4 + 4, 16)
        struct.pack_into('<H', buf, vtable_start + 4 + 6, 24)
        struct.pack_into('<H', buf, vtable_start + 4 + 8, 28)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatCompletionResponse':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_id = ""
        val_object = ""
        val_created = 0
        val_model = ""
        val_choices = 0
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_id = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_object = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 8 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 8)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 8 <= len(buf):
                    val_created = struct.unpack_from('<q', buf, abs_offset)[0]
        if 10 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 10)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_model = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 12 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 12)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        return cls(
            id=val_id,
            object=val_object,
            created=val_created,
            model=val_model,
            choices=val_choices,
        )

class ChatCompletionServiceBase(ABC):
    @abstractmethod
    async def CreateChatCompletion(self, request: 'ChatCompletionRequest') -> 'ChatCompletionResponse':
        pass

    @abstractmethod
    async def StreamChatCompletion(self, request: 'ChatCompletionRequest') -> AsyncIterator['ChatCompletionResponse']:
        pass

