# Code generated by helix-gen. DO NOT EDIT.
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, AsyncIterator
from abc import ABC, abstractmethod
import struct as _struct

def _read_varint(buf: memoryview, idx: int):
    v, shift = 0, 0
    while True:
        if idx >= len(buf): raise EOFError('unexpected EOF reading varint')
        b = buf[idx]; idx += 1
        v |= (b & 0x7f) << shift
        if (b & 0x80) == 0: break
        shift += 7
    return v, idx

def _write_thrift_varint(out: bytearray, v: int) -> None:
    while True:
        if (v & ~0x7F) == 0: out.append(v); break
        out.append((v & 0x7F) | 0x80); v >>= 7

def _write_thrift_i16(out: bytearray, v: int) -> None:
    out.append((v >> 8) & 0xFF); out.append(v & 0xFF)

def _fast_scan_field(raw: memoryview, target_field: int):
    idx = 0
    while idx < len(raw):
        tag, idx = _read_varint(raw, idx)
        field_num = tag >> 3
        wire_type = tag & 0x7
        if field_num == target_field:
            if wire_type == 2:
                length, idx = _read_varint(raw, idx)
                return raw[idx:idx+length], wire_type
            elif wire_type == 0:
                start = idx
                _, idx = _read_varint(raw, idx)
                return raw[start:idx], wire_type
            raise ValueError(f'unsupported wire_type {wire_type}')
        if wire_type == 0: _, idx = _read_varint(raw, idx)
        elif wire_type == 2:
            length, idx = _read_varint(raw, idx)
            idx += length
        else: raise ValueError(f'unknown wire_type {wire_type}')
    raise KeyError(f'field {target_field} not found')

@dataclass
class ChatMessage:
    role: str
    content: str

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_role = self.role.encode('utf-8') if self.role else b''
        if str_role:
            dynamic_size += 4 + len(str_role)
        str_content = self.content.encode('utf-8') if self.content else b''
        if str_content:
            dynamic_size += 4 + len(str_content)
        table_size = 12
        vtable_size = 8
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        if str_role:
            rel_offset = current_string_offset - (4 + 4)
            struct.pack_into('<I', buf, 4 + 4, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_role))
            buf[current_string_offset+4 : current_string_offset+4+len(str_role)] = str_role
            current_string_offset += 4 + len(str_role)
        if str_content:
            rel_offset = current_string_offset - (4 + 8)
            struct.pack_into('<I', buf, 4 + 8, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_content))
            buf[current_string_offset+4 : current_string_offset+4+len(str_content)] = str_content
            current_string_offset += 4 + len(str_content)
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatMessage':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_role = ""
        val_content = ""
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_role = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_content = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        return cls(
            role=val_role,
            content=val_content,
        )

    @classmethod
    def from_proto(cls, buf: bytes) -> 'ChatMessage':
        raw = memoryview(buf)
        val_role = ""
        val_content = ""
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                _len, idx = _read_varint(raw, idx); val_role = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            elif field_num == 2:
                _len, idx = _read_varint(raw, idx); val_content = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        return cls(
            role=val_role,
            content=val_content,
        )

class LazyChatMessage:
    __slots__ = ('_raw',)
    def __init__(self, raw: bytes) -> None:
        self._raw = memoryview(raw)
    def get_role(self) -> str:
        b, _ = _fast_scan_field(self._raw, 1)
        return bytes(b).decode('utf-8')
    def get_content(self) -> str:
        b, _ = _fast_scan_field(self._raw, 2)
        return bytes(b).decode('utf-8')

    @classmethod
    def transpile_protobuf_to_thrift_compact(cls, data: bytes) -> bytes:
        raw = memoryview(data)
        out = bytearray()
        _f_role = None
        _f_content = None
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                _l, idx = _read_varint(raw, idx)
                _f_role = bytes(raw[idx:idx+_l])
                idx += _l
                _f_role = _f_role.decode('utf-8')
            elif field_num == 2:
                _l, idx = _read_varint(raw, idx)
                _f_content = bytes(raw[idx:idx+_l])
                idx += _l
                _f_content = _f_content.decode('utf-8')
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        prev_field = 0
        if _f_role is not None:
            _delta = 1 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 1)
            _enc = _f_role.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 1
        if _f_content is not None:
            _delta = 2 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 2)
            _enc = _f_content.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 2
        out.append(0x00)  # Thrift STOP byte
        return bytes(out)

@dataclass
class ChatCompletionRequest:
    model: str
    messages: List['ChatMessage']
    stream: bool

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_model = self.model.encode('utf-8') if self.model else b''
        if str_model:
            dynamic_size += 4 + len(str_model)
        table_size = 16
        vtable_size = 10
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        if str_model:
            rel_offset = current_string_offset - (4 + 4)
            struct.pack_into('<I', buf, 4 + 4, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_model))
            buf[current_string_offset+4 : current_string_offset+4+len(str_model)] = str_model
            current_string_offset += 4 + len(str_model)
        struct.pack_into('<?', buf, 4 + 12, bool(self.stream))
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        struct.pack_into('<H', buf, vtable_start + 4 + 4, 12)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatCompletionRequest':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_model = ""
        val_messages = 0
        val_stream = False
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_model = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        if 8 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 8)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset < len(buf):
                    val_stream = struct.unpack_from('<?', buf, abs_offset)[0]
        return cls(
            model=val_model,
            messages=val_messages,
            stream=val_stream,
        )

    @classmethod
    def from_proto(cls, buf: bytes) -> 'ChatCompletionRequest':
        raw = memoryview(buf)
        val_model = ""
        val_messages = 0
        val_stream = False
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                _len, idx = _read_varint(raw, idx); val_model = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            elif field_num == 2:
                _, idx = _read_varint(raw, idx)
            elif field_num == 3:
                _v, idx = _read_varint(raw, idx); val_stream = bool(_v)
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        return cls(
            model=val_model,
            messages=val_messages,
            stream=val_stream,
        )

class LazyChatCompletionRequest:
    __slots__ = ('_raw',)
    def __init__(self, raw: bytes) -> None:
        self._raw = memoryview(raw)
    def get_model(self) -> str:
        b, _ = _fast_scan_field(self._raw, 1)
        return bytes(b).decode('utf-8')
    def get_messages(self):
        b, _ = _fast_scan_field(self._raw, 2)
        return bytes(b)
    def get_stream(self) -> bool:
        b, _ = _fast_scan_field(self._raw, 3)
        v, _ = _read_varint(b, 0)
        return v != 0

    @classmethod
    def transpile_protobuf_to_thrift_compact(cls, data: bytes) -> bytes:
        raw = memoryview(data)
        out = bytearray()
        _f_model = None
        _f_messages = 0
        _f_stream = False
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                _l, idx = _read_varint(raw, idx)
                _f_model = bytes(raw[idx:idx+_l])
                idx += _l
                _f_model = _f_model.decode('utf-8')
            elif field_num == 2:
            elif field_num == 3:
                v, idx = _read_varint(raw, idx)
                _f_stream = (v != 0)
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        prev_field = 0
        if _f_model is not None:
            _delta = 1 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 1)
            _enc = _f_model.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 1
        _delta = 3 - prev_field
        _ttype = 1 if _f_stream else 2
        if 0 < _delta <= 15: out.append((_delta << 4) | _ttype)
        else: out.append(_ttype); _write_thrift_i16(out, 3)
        prev_field = 3
        out.append(0x00)  # Thrift STOP byte
        return bytes(out)

@dataclass
class ChatCompletionChoice:
    index: int
    message: 'ChatMessage'
    delta: 'ChatMessage'
    finish_reason: str

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_finish_reason = self.finish_reason.encode('utf-8') if self.finish_reason else b''
        if str_finish_reason:
            dynamic_size += 4 + len(str_finish_reason)
        table_size = 20
        vtable_size = 12
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        struct.pack_into('<i', buf, 4 + 4, self.index or 0)
        if str_finish_reason:
            rel_offset = current_string_offset - (4 + 16)
            struct.pack_into('<I', buf, 4 + 16, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_finish_reason))
            buf[current_string_offset+4 : current_string_offset+4+len(str_finish_reason)] = str_finish_reason
            current_string_offset += 4 + len(str_finish_reason)
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        struct.pack_into('<H', buf, vtable_start + 4 + 4, 12)
        struct.pack_into('<H', buf, vtable_start + 4 + 6, 16)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatCompletionChoice':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_index = 0
        val_message = 0
        val_delta = 0
        val_finish_reason = ""
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    val_index = struct.unpack_from('<i', buf, abs_offset)[0]
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        if 8 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 8)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        if 10 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 10)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_finish_reason = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        return cls(
            index=val_index,
            message=val_message,
            delta=val_delta,
            finish_reason=val_finish_reason,
        )

    @classmethod
    def from_proto(cls, buf: bytes) -> 'ChatCompletionChoice':
        raw = memoryview(buf)
        val_index = 0
        val_message = 0
        val_delta = 0
        val_finish_reason = ""
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                val_index, idx = _read_varint(raw, idx)
            elif field_num == 2:
                _, idx = _read_varint(raw, idx)
            elif field_num == 3:
                _, idx = _read_varint(raw, idx)
            elif field_num == 4:
                _len, idx = _read_varint(raw, idx); val_finish_reason = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        return cls(
            index=val_index,
            message=val_message,
            delta=val_delta,
            finish_reason=val_finish_reason,
        )

class LazyChatCompletionChoice:
    __slots__ = ('_raw',)
    def __init__(self, raw: bytes) -> None:
        self._raw = memoryview(raw)
    def get_index(self) -> int:
        b, _ = _fast_scan_field(self._raw, 1)
        v, _ = _read_varint(b, 0)
        return v
    def get_message(self):
        b, _ = _fast_scan_field(self._raw, 2)
        return bytes(b)
    def get_delta(self):
        b, _ = _fast_scan_field(self._raw, 3)
        return bytes(b)
    def get_finish_reason(self) -> str:
        b, _ = _fast_scan_field(self._raw, 4)
        return bytes(b).decode('utf-8')

    @classmethod
    def transpile_protobuf_to_thrift_compact(cls, data: bytes) -> bytes:
        raw = memoryview(data)
        out = bytearray()
        _f_index = 0
        _f_message = 0
        _f_delta = 0
        _f_finish_reason = None
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                v, idx = _read_varint(raw, idx)
                _f_index = v
            elif field_num == 2:
            elif field_num == 3:
            elif field_num == 4:
                _l, idx = _read_varint(raw, idx)
                _f_finish_reason = bytes(raw[idx:idx+_l])
                idx += _l
                _f_finish_reason = _f_finish_reason.decode('utf-8')
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        prev_field = 0
        _delta = 1 - prev_field
        if 0 < _delta <= 15: out.append((_delta << 4) | 5)
        else: out.append(5); _write_thrift_i16(out, 1)
        _zz = (_f_index << 1) ^ (_f_index >> 31) if _f_index < 0 else _f_index << 1
        _write_thrift_varint(out, _zz)
        prev_field = 1
        if _f_finish_reason is not None:
            _delta = 4 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 4)
            _enc = _f_finish_reason.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 4
        out.append(0x00)  # Thrift STOP byte
        return bytes(out)

@dataclass
class ChatCompletionResponse:
    id: str
    object: str
    created: int
    model: str
    choices: List['ChatCompletionChoice']

    def marshal_flatbuffers(self) -> bytes:
        import struct
        dynamic_size = 0
        str_id = self.id.encode('utf-8') if self.id else b''
        if str_id:
            dynamic_size += 4 + len(str_id)
        str_object = self.object.encode('utf-8') if self.object else b''
        if str_object:
            dynamic_size += 4 + len(str_object)
        str_model = self.model.encode('utf-8') if self.model else b''
        if str_model:
            dynamic_size += 4 + len(str_model)
        table_size = 32
        vtable_size = 14
        total_size = 4 + table_size + dynamic_size + vtable_size
        buf = bytearray(total_size)
        struct.pack_into('<I', buf, 0, 4) # root offset
        vtable_start = 4 + table_size + dynamic_size
        vtable_offset = vtable_start - 4
        struct.pack_into('<i', buf, 4, vtable_offset)
        current_string_offset = 4 + table_size
        if str_id:
            rel_offset = current_string_offset - (4 + 4)
            struct.pack_into('<I', buf, 4 + 4, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_id))
            buf[current_string_offset+4 : current_string_offset+4+len(str_id)] = str_id
            current_string_offset += 4 + len(str_id)
        if str_object:
            rel_offset = current_string_offset - (4 + 8)
            struct.pack_into('<I', buf, 4 + 8, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_object))
            buf[current_string_offset+4 : current_string_offset+4+len(str_object)] = str_object
            current_string_offset += 4 + len(str_object)
        struct.pack_into('<q', buf, 4 + 16, self.created or 0)
        if str_model:
            rel_offset = current_string_offset - (4 + 24)
            struct.pack_into('<I', buf, 4 + 24, rel_offset)
            struct.pack_into('<I', buf, current_string_offset, len(str_model))
            buf[current_string_offset+4 : current_string_offset+4+len(str_model)] = str_model
            current_string_offset += 4 + len(str_model)
        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)
        struct.pack_into('<H', buf, vtable_start + 4 + 0, 4)
        struct.pack_into('<H', buf, vtable_start + 4 + 2, 8)
        struct.pack_into('<H', buf, vtable_start + 4 + 4, 16)
        struct.pack_into('<H', buf, vtable_start + 4 + 6, 24)
        struct.pack_into('<H', buf, vtable_start + 4 + 8, 28)
        return bytes(buf)

    @classmethod
    def unmarshal_flatbuffers(cls, buf: bytes) -> 'ChatCompletionResponse':
        import struct
        if len(buf) < 8:
            raise ValueError('flatbuffers: buffer too small')
        root_offset = struct.unpack_from('<I', buf, 0)[0]
        if root_offset + 4 > len(buf):
            raise ValueError('flatbuffers: invalid root offset')
        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]
        vtable_start = root_offset + vtable_offset
        if vtable_start < 0 or vtable_start + 4 > len(buf):
            raise ValueError('flatbuffers: invalid vtable offset')
        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]
        val_id = ""
        val_object = ""
        val_created = 0
        val_model = ""
        val_choices = 0
        if 4 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 4)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_id = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 6 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 6)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_object = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 8 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 8)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 8 <= len(buf):
                    val_created = struct.unpack_from('<q', buf, abs_offset)[0]
        if 10 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 10)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
                if abs_offset + 4 <= len(buf):
                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]
                    str_start = abs_offset + rel_offset
                    if str_start + 4 <= len(buf):
                        str_len = struct.unpack_from('<I', buf, str_start)[0]
                        if str_start + 4 + str_len <= len(buf):
                            val_model = buf[str_start+4 : str_start+4+str_len].decode('utf-8')
        if 12 + 2 <= vtable_size:
            foffset = struct.unpack_from('<H', buf, vtable_start + 12)[0]
            if foffset > 0:
                abs_offset = root_offset + foffset
        return cls(
            id=val_id,
            object=val_object,
            created=val_created,
            model=val_model,
            choices=val_choices,
        )

    @classmethod
    def from_proto(cls, buf: bytes) -> 'ChatCompletionResponse':
        raw = memoryview(buf)
        val_id = ""
        val_object = ""
        val_created = 0
        val_model = ""
        val_choices = 0
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                _len, idx = _read_varint(raw, idx); val_id = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            elif field_num == 2:
                _len, idx = _read_varint(raw, idx); val_object = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            elif field_num == 3:
                val_created, idx = _read_varint(raw, idx)
            elif field_num == 4:
                _len, idx = _read_varint(raw, idx); val_model = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len
            elif field_num == 5:
                _, idx = _read_varint(raw, idx)
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        return cls(
            id=val_id,
            object=val_object,
            created=val_created,
            model=val_model,
            choices=val_choices,
        )

class LazyChatCompletionResponse:
    __slots__ = ('_raw',)
    def __init__(self, raw: bytes) -> None:
        self._raw = memoryview(raw)
    def get_id(self) -> str:
        b, _ = _fast_scan_field(self._raw, 1)
        return bytes(b).decode('utf-8')
    def get_object(self) -> str:
        b, _ = _fast_scan_field(self._raw, 2)
        return bytes(b).decode('utf-8')
    def get_created(self) -> int:
        b, _ = _fast_scan_field(self._raw, 3)
        v, _ = _read_varint(b, 0)
        return v
    def get_model(self) -> str:
        b, _ = _fast_scan_field(self._raw, 4)
        return bytes(b).decode('utf-8')
    def get_choices(self):
        b, _ = _fast_scan_field(self._raw, 5)
        return bytes(b)

    @classmethod
    def transpile_protobuf_to_thrift_compact(cls, data: bytes) -> bytes:
        raw = memoryview(data)
        out = bytearray()
        _f_id = None
        _f_object = None
        _f_created = 0
        _f_model = None
        _f_choices = 0
        idx = 0
        while idx < len(raw):
            tag, idx = _read_varint(raw, idx)
            field_num = tag >> 3
            wire_type = tag & 0x7
            if field_num == 1:
                _l, idx = _read_varint(raw, idx)
                _f_id = bytes(raw[idx:idx+_l])
                idx += _l
                _f_id = _f_id.decode('utf-8')
            elif field_num == 2:
                _l, idx = _read_varint(raw, idx)
                _f_object = bytes(raw[idx:idx+_l])
                idx += _l
                _f_object = _f_object.decode('utf-8')
            elif field_num == 3:
                v, idx = _read_varint(raw, idx)
                _f_created = v
            elif field_num == 4:
                _l, idx = _read_varint(raw, idx)
                _f_model = bytes(raw[idx:idx+_l])
                idx += _l
                _f_model = _f_model.decode('utf-8')
            elif field_num == 5:
            else:
                if wire_type == 0: _, idx = _read_varint(raw, idx)
                elif wire_type == 2:
                    _l, idx = _read_varint(raw, idx); idx += _l
                elif wire_type == 5: idx += 4
                elif wire_type == 1: idx += 8
        prev_field = 0
        if _f_id is not None:
            _delta = 1 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 1)
            _enc = _f_id.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 1
        if _f_object is not None:
            _delta = 2 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 2)
            _enc = _f_object.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 2
        _delta = 3 - prev_field
        if 0 < _delta <= 15: out.append((_delta << 4) | 6)
        else: out.append(6); _write_thrift_i16(out, 3)
        _zz = (_f_created << 1) ^ (_f_created >> 63) if _f_created < 0 else _f_created << 1
        _write_thrift_varint(out, _zz)
        prev_field = 3
        if _f_model is not None:
            _delta = 4 - prev_field
            if 0 < _delta <= 15: out.append((_delta << 4) | 8)
            else: out.append(8); _write_thrift_i16(out, 4)
            _enc = _f_model.encode('utf-8')
            _write_thrift_varint(out, len(_enc))
            out.extend(_enc)
            prev_field = 4
        out.append(0x00)  # Thrift STOP byte
        return bytes(out)

class ChatCompletionServiceBase(ABC):
    @abstractmethod
    async def CreateChatCompletion(self, request: 'ChatCompletionRequest') -> 'ChatCompletionResponse':
        pass

    @abstractmethod
    async def StreamChatCompletion(self, request: 'ChatCompletionRequest') -> AsyncIterator['ChatCompletionResponse']:
        pass

