# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_completion_pb2 as chat__completion__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat_completion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatCompletionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChatCompletion = channel.unary_unary(
                '/openai.chat.ChatCompletionService/CreateChatCompletion',
                request_serializer=chat__completion__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=chat__completion__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)
        self.StreamChatCompletion = channel.unary_stream(
                '/openai.chat.ChatCompletionService/StreamChatCompletion',
                request_serializer=chat__completion__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=chat__completion__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)


class ChatCompletionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateChatCompletion(self, request, context):
        """Unary completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChatCompletion(self, request, context):
        """Streaming completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatCompletionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChatCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChatCompletion,
                    request_deserializer=chat__completion__pb2.ChatCompletionRequest.FromString,
                    response_serializer=chat__completion__pb2.ChatCompletionResponse.SerializeToString,
            ),
            'StreamChatCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChatCompletion,
                    request_deserializer=chat__completion__pb2.ChatCompletionRequest.FromString,
                    response_serializer=chat__completion__pb2.ChatCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openai.chat.ChatCompletionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openai.chat.ChatCompletionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatCompletionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openai.chat.ChatCompletionService/CreateChatCompletion',
            chat__completion__pb2.ChatCompletionRequest.SerializeToString,
            chat__completion__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/openai.chat.ChatCompletionService/StreamChatCompletion',
            chat__completion__pb2.ChatCompletionRequest.SerializeToString,
            chat__completion__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
