apiVersion: orchestration.helixrpc.io/v1alpha1
kind: HelixService
metadata:
  labels:
    app.kubernetes.io/name: helix-operator
    app.kubernetes.io/managed-by: kustomize
  name: helixservice-sample
spec:
  # TODO(user): Add fields here
