// Code generated by helix-gen. DO NOT EDIT.

use std::collections::HashMap;
use thrift::protocol::{TInputProtocol, TOutputProtocol, TSerializable, TFieldIdentifier, TStructIdentifier, TType};
use thrift::Error as ThriftError;


#[inline]
fn read_varint(buf: &[u8], mut idx: usize) -> Result<(u64, usize), String> {
    let mut v: u64 = 0;
    let mut shift: u32 = 0;
    loop {
        if idx >= buf.len() { return Err("unexpected EOF reading varint".to_string()); }
        let b = buf[idx]; idx += 1;
        v |= ((b & 0x7f) as u64) << shift;
        if b & 0x80 == 0 { break; }
        shift += 7;
    }
    Ok((v, idx))
}

#[inline]
fn write_thrift_varint(out: &mut Vec<u8>, mut v: u64) {
    loop {
        if v & !0x7F == 0 { out.push(v as u8); break; }
        out.push((v as u8 & 0x7F) | 0x80);
        v >>= 7;
    }
}

#[inline]
fn write_thrift_i16(out: &mut Vec<u8>, v: i16) {
    out.push((v >> 8) as u8);
    out.push(v as u8);
}

fn fast_scan_field(buf: &[u8], target: i32) -> Result<(&[u8], u8), String> {
    let mut idx = 0usize;
    while idx < buf.len() {
        let (tag, ni) = read_varint(buf, idx)?;
        idx = ni;
        let field_num = (tag >> 3) as i32;
        let wire_type = (tag & 0x7) as u8;
        if field_num == target {
            if wire_type == 2 {
                let (len, ni) = read_varint(buf, idx)?;
                let end = ni + len as usize;
                if end > buf.len() { return Err("unexpected EOF".to_string()); }
                return Ok((&buf[ni..end], wire_type));
            } else if wire_type == 0 {
                let start = idx;
                let (_, ni) = read_varint(buf, idx)?;
                return Ok((&buf[start..ni], wire_type));
            }
            return Err(format!("unsupported wire_type {} for fast_scan", wire_type));
        }
        // Skip unknown field
        if wire_type == 0 { let (_, ni) = read_varint(buf, idx)?; idx = ni; }
        else if wire_type == 2 { let (len, ni) = read_varint(buf, idx)?; idx = ni + len as usize; }
        else { return Err(format!("unhandled wire_type {} in fast_scan skip", wire_type)); }
    }
    Err(format!("field {} not found", target))
}

#[derive(Clone, PartialEq, ::prost::Message, ::serde::Serialize, ::serde::Deserialize)]
pub struct ComplexRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "4")]
    pub metadata: String,
}

impl TSerializable for ComplexRequest {
    fn read_from_in_protocol(_i_prot: &mut dyn TInputProtocol) -> thrift::Result<Self> {
        Err(thrift::Error::User(Box::new(std::io::Error::new(std::io::ErrorKind::Other, "Thrift serialization is unsupported for complex fields"))))
    }
    fn write_to_out_protocol(&self, _o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
        Err(thrift::Error::User(Box::new(std::io::Error::new(std::io::ErrorKind::Other, "Thrift serialization is unsupported for complex fields"))))
    }
}

impl ComplexRequest {
    pub fn marshal_flatbuffers(&self) -> Vec<u8> {
        Vec::new()
    }
    pub fn unmarshal_flatbuffers(_buf: &[u8]) -> Result<Self, String> {
        Err("FlatBuffers is unsupported for complex fields".to_string())
    }
}

pub struct LazyComplexRequest<'a> {
    decoded: ComplexRequest,
    _marker: std::marker::PhantomData<&'a ()>,
}

impl<'a> LazyComplexRequest<'a> {
    pub fn new(raw: &'a [u8]) -> Self {
        let mut decoded = ComplexRequest::default();
        let _ = prost::Message::merge(&mut decoded, raw);
        Self { decoded, _marker: std::marker::PhantomData }
    }
    pub fn get_id(&self) -> Result<i32, String> { Ok(self.decoded.id as i32) }
}

impl ComplexRequest {
    pub fn transpile_protobuf_to_thrift_compact(_input: &[u8], _output: &mut Vec<u8>) -> Result<(), String> {
        Err("Transpilation is unsupported for structs with complex fields.".to_string())
    }
}

