package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

// GenerateCPP produces C++ struct and class stubs from the AST.
func GenerateCPP(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Automatically generated by Helix RPC. DO NOT EDIT.\n")
	sb.WriteString("#pragma once\n\n")
	sb.WriteString("#include <string>\n")
	sb.WriteString("#include <vector>\n")
	sb.WriteString("#include <string_view>\n")
	sb.WriteString("#include <stdexcept>\n")
	sb.WriteString("#include <cstdint>\n\n")

	sb.WriteString("namespace helix {\n\n")

	// Generate structs
	for _, str := range parsed.Structs {
		sb.WriteString(fmt.Sprintf("struct %s {\n", str.Name))
		for _, f := range str.Fields {
			cppType := getCPPType(f.Type)
			sb.WriteString(fmt.Sprintf("    %s %s;\n", cppType, toLowerSnakeCase(f.Name)))
		}
		sb.WriteString("};\n\n")
	}

	sb.WriteString("} // namespace helix\n")
	return sb.String(), nil
}

func getCPPType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int32_t"
	case ast.TypeInt64:
		return "int64_t"
	case ast.TypeString:
		return "std::string"
	case ast.TypeBinary:
		return "std::vector<uint8_t>"
	case ast.TypeBool:
		return "bool"
	default:
		return "std::string"
	}
}

func toLowerSnakeCase(s string) string {
	var res strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			res.WriteRune('_')
		}
		res.WriteRune(r)
	}
	return strings.ToLower(res.String())
}
