package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

func GenerateGo(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by helix-gen. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", strings.ReplaceAll(parsed.Namespace, ".", "_")))

	// Write standard imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"unsafe\"\n")
	sb.WriteString("\t\"github.com/golang/protobuf/proto\"\n")
	sb.WriteString("\t\"github.com/apache/thrift/lib/go/thrift\"\n")
	sb.WriteString("\truntime \"github.com/helix-rpc/helix/runtime-go\"\n")
	sb.WriteString(")\n\n")

	// Helper functions for protobuf serialization (varints)
	sb.WriteString(`func writeVarint(buf []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		buf[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	buf[offset] = uint8(v)
	return offset + 1
}

func readVarint(buf []byte, offset int) (uint64, int, error) {
	var v uint64
	var shift uint
	for {
		if offset >= len(buf) {
			return 0, 0, fmt.Errorf("unexpected EOF reading varint")
		}
		b := buf[offset]
		offset++
		v |= uint64(b&0x7f) << shift
		if b&0x80 == 0 {
			break
		}
		shift += 7
	}
	return v, offset, nil
}

func unsafeString(b []byte) string {
	if len(b) == 0 {
		return ""
	}
	return unsafe.String(&b[0], len(b))
}

func encodeZigZag32(n int32) uint32 {
	return uint32((n << 1) ^ (n >> 31))
}

func writeThriftVarint(buf []byte, offset int, v uint64) int {
	for {
		if (v & ^uint64(0x7F)) == 0 {
			buf[offset] = byte(v)
			offset++
			break
		} else {
			buf[offset] = byte((v & 0x7F) | 0x80)
			offset++
			v >>= 7
		}
	}
	return offset
}

func writeThriftI16(buf []byte, offset int, v int16) int {
	buf[offset] = byte(v >> 8)
	buf[offset+1] = byte(v)
	return offset + 2
}

func fastScanField(dAtA []byte, targetFieldNum int32) ([]byte, int, error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var i uint64
		var err error
		i, iNdEx, err = readVarint(dAtA, iNdEx)
		if err != nil {
			return nil, 0, err
		}
		fieldNum := int32(i >> 3)
		wireType := int(i & 0x7)
		if fieldNum == targetFieldNum {
			if wireType == 2 {
				var length uint64
				length, iNdEx, err = readVarint(dAtA, iNdEx)
				if err != nil {
					return nil, 0, err
				}
				postIndex := iNdEx + int(length)
				if postIndex < 0 || postIndex > l {
					return nil, 0, fmt.Errorf("unexpected EOF")
				}
				return dAtA[iNdEx:postIndex], wireType, nil
			} else if wireType == 0 {
				start := iNdEx
				_, iNdEx, err = readVarint(dAtA, iNdEx)
				if err != nil {
					return nil, 0, err
				}
				return dAtA[start:iNdEx], wireType, nil
			}
			return nil, 0, fmt.Errorf("unsupported wireType for fast scan")
		}
		if wireType == 0 {
			_, iNdEx, err = readVarint(dAtA, iNdEx)
			if err != nil {
				return nil, 0, err
			}
		} else if wireType == 2 {
			var length uint64
			length, iNdEx, err = readVarint(dAtA, iNdEx)
			if err != nil {
				return nil, 0, err
			}
			iNdEx += int(length)
		} else {
			return nil, 0, fmt.Errorf("unhandled wireType in fastScan skip")
		}
	}
	return nil, 0, fmt.Errorf("field not found")
}
`)
	sb.WriteString("\n")

	// Generate Structs
	for _, str := range parsed.Structs {
		// Define the struct
		sb.WriteString(fmt.Sprintf("type %s struct {\n", str.Name))
		for _, f := range str.Fields {
			goType := mapGoType(f.Type)
			protoTag := fmt.Sprintf("%s,%d", mapProtoType(f.Type), f.ID)
			thriftTag := fmt.Sprintf("%s,%d", f.Name, f.ID)
			sb.WriteString(fmt.Sprintf("\t%s %s `thrift:\"%s\" json:\"%s\" proto:\"%s\"`\n",
				toCamelCase(f.Name), goType, thriftTag, f.Name, protoTag))
		}
		sb.WriteString("}\n\n")

		// Satisfy proto.Message
		sb.WriteString(fmt.Sprintf("func (x *%s) Reset()         { *x = %s{} }\n", str.Name, str.Name))
		sb.WriteString(fmt.Sprintf("func (x *%s) String() string { return proto.CompactTextString(x) }\n", str.Name))
		sb.WriteString(fmt.Sprintf("func (x *%s) ProtoMessage()  {}\n\n", str.Name))

		// Marshal interface
		sb.WriteString(fmt.Sprintf("func (x *%s) Marshal() ([]byte, error) {\n", str.Name))
		sb.WriteString("\tbuf := make([]byte, x.ProtoSize())\n")
		sb.WriteString("\t_, err := x.MarshalTo(buf)\n")
		sb.WriteString("\treturn buf, err\n")
		sb.WriteString("}\n\n")

		// ProtoSize calculations
		sb.WriteString(fmt.Sprintf("func (x *%s) ProtoSize() (size int) {\n", str.Name))
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\tif x.%s != 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tsize += 1 + sizeOfVarint(uint64(x.%s))\n", capName))
				sb.WriteString("\t}\n")
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\tif len(x.%s) > 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tsize += 1 + sizeOfVarint(uint64(len(x.%s))) + len(x.%s)\n", capName, capName))
				sb.WriteString("\t}\n")
			}
		}
		sb.WriteString("\treturn size\n")
		sb.WriteString("}\n\n")

		// sizeOfVarint helper
		sb.WriteString(`func sizeOfVarint(v uint64) int {
	if v == 0 {
		return 1
	}
	size := 0
	for v > 0 {
		size++
		v >>= 7
	}
	return size
}

`)

		// MarshalTo calculations
		sb.WriteString(fmt.Sprintf("func (x *%s) MarshalTo(dAtA []byte) (int, error) {\n", str.Name))
		sb.WriteString("\tvar i int\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			// Tag field key = (field_number << 3) | wire_type
			wireType := 0 // varint
			if f.Type.Kind == ast.TypeString || f.Type.Kind == ast.TypeBinary {
				wireType = 2 // length-delimited
			}
			tagVal := (f.ID << 3) | int32(wireType)

			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\tif x.%s != 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tdAtA[i] = 0x%x\n", tagVal))
				sb.WriteString("\t\ti++\n")
				sb.WriteString(fmt.Sprintf("\t\ti = writeVarint(dAtA, i, uint64(x.%s))\n", capName))
				sb.WriteString("\t}\n")
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\tif len(x.%s) > 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tdAtA[i] = 0x%x\n", tagVal))
				sb.WriteString("\t\ti++\n")
				sb.WriteString(fmt.Sprintf("\t\ti = writeVarint(dAtA, i, uint64(len(x.%s)))\n", capName))
				sb.WriteString(fmt.Sprintf("\t\ti += copy(dAtA[i:], x.%s)\n", capName))
				sb.WriteString("\t}\n")
			}
		}
		sb.WriteString("\treturn i, nil\n")
		sb.WriteString("}\n\n")

		// Unmarshal implementation
		sb.WriteString(fmt.Sprintf("func (x *%s) Unmarshal(dAtA []byte) error {\n", str.Name))
		sb.WriteString("\tl := len(dAtA)\n")
		sb.WriteString("\tiNdEx := 0\n")
		sb.WriteString("\tfor iNdEx < l {\n")
		sb.WriteString("\t\tpostIndex := 0\n")
		sb.WriteString("\t\tvar i uint64\n")
		sb.WriteString("\t\tvar err error\n")
		sb.WriteString("\t\ti, iNdEx, err = readVarint(dAtA, iNdEx)\n")
		sb.WriteString("\t\tif err != nil {\n")
		sb.WriteString("\t\t\treturn err\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tfieldNum := int32(i >> 3)\n")
		sb.WriteString("\t\twireType := int(i & 0x7)\n")
		sb.WriteString("\t\tif wireType == 4 {\n")
		sb.WriteString(fmt.Sprintf("\t\t\treturn fmt.Errorf(\"proto: %s: wiretype end group for non-group\")\n", str.Name))
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tswitch fieldNum {\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			sb.WriteString(fmt.Sprintf("\t\tcase %d:\n", f.ID))
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeInt64:
				sb.WriteString("\t\t\tif wireType != 0 {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\treturn fmt.Errorf(\"proto: wrong wireType = %%d for field %s\", wireType)\n", capName))
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\tvar v uint64\n")
				sb.WriteString("\t\t\tv, iNdEx, err = readVarint(dAtA, iNdEx)\n")
				sb.WriteString("\t\t\tif err != nil {\n")
				sb.WriteString("\t\t\t\treturn err\n")
				sb.WriteString("\t\t\t}\n")
				if f.Type.Kind == ast.TypeInt32 {
					sb.WriteString(fmt.Sprintf("\t\t\tx.%s = int32(v)\n", capName))
				} else {
					sb.WriteString(fmt.Sprintf("\t\t\tx.%s = int64(v)\n", capName))
				}
			case ast.TypeString:
				sb.WriteString("\t\t\tif wireType != 2 {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\treturn fmt.Errorf(\"proto: wrong wireType = %%d for field %s\", wireType)\n", capName))
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\tvar stringLen uint64\n")
				sb.WriteString("\t\t\tstringLen, iNdEx, err = readVarint(dAtA, iNdEx)\n")
				sb.WriteString("\t\t\tif err != nil {\n")
				sb.WriteString("\t\t\t\treturn err\n")
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\tpostIndex = iNdEx + int(stringLen)\n")
				sb.WriteString("\t\t\tif postIndex < 0 || postIndex > l {\n")
				sb.WriteString("\t\t\t\treturn fmt.Errorf(\"unexpected EOF\")\n")
				sb.WriteString("\t\t\t}\n")
				sb.WriteString(fmt.Sprintf("\t\t\tx.%s = unsafeString(dAtA[iNdEx:postIndex])\n", capName))
				sb.WriteString("\t\t\tiNdEx = postIndex\n")
			}
		}
		sb.WriteString("\t\tdefault:\n")
		// skip unknown field
		sb.WriteString("\t\t\tvar v uint64\n")
		sb.WriteString("\t\t\tv, iNdEx, err = readVarint(dAtA, iNdEx)\n")
		sb.WriteString("\t\t\tif err != nil {\n")
		sb.WriteString("\t\t\t\treturn err\n")
		sb.WriteString("\t\t\t}\n")
		sb.WriteString("\t\t\tif wireType == 0 {\n")
		sb.WriteString("\t\t\t\t// already read varint\n")
		sb.WriteString("\t\t\t} else if wireType == 2 {\n")
		sb.WriteString("\t\t\t\tpostIndex = iNdEx + int(v)\n")
		sb.WriteString("\t\t\t\tiNdEx = postIndex\n")
		sb.WriteString("\t\t\t} else {\n")
		sb.WriteString("\t\t\t\treturn fmt.Errorf(\"unhandled wireType in unmarshal skip\")\n")
		sb.WriteString("\t\t\t}\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn nil\n")
		sb.WriteString("}\n\n")

		// FlatBuffers Marshal implementation
		// Calculate fixed offsets
		offsets := make([]int, len(str.Fields))
		currentOffset := 4 // starts after vtable_offset (4 bytes)
		for idx, f := range str.Fields {
			size := 4
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeBool:
				size = 4
			case ast.TypeInt64, ast.TypeDouble:
				size = 8
			case ast.TypeString, ast.TypeBinary:
				size = 4
			}
			rem := currentOffset % size
			if rem != 0 {
				currentOffset += size - rem
			}
			offsets[idx] = currentOffset
			currentOffset += size
		}
		tableSize := currentOffset
		vtableSize := 4 + 2*len(str.Fields)

		sb.WriteString(fmt.Sprintf("func (x *%s) MarshalFlatBuffers() []byte {\n", str.Name))
		sb.WriteString("\tdynamicSize := 0\n")
		for _, f := range str.Fields {
			if f.Type.Kind == ast.TypeString || f.Type.Kind == ast.TypeBinary {
				capName := toCamelCase(f.Name)
				sb.WriteString(fmt.Sprintf("\tif len(x.%s) > 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tdynamicSize += 4 + len(x.%s)\n", capName))
				sb.WriteString("\t}\n")
			}
		}
		sb.WriteString(fmt.Sprintf("\ttotalSize := 4 + %d + dynamicSize + %d\n", tableSize, vtableSize))
		sb.WriteString("\tbuf := make([]byte, totalSize)\n")
		sb.WriteString("\t// Root offset pointing to the root table (always 4)\n")
		sb.WriteString("\tbuf[0] = 4\n")
		sb.WriteString("\t// Table starts at offset 4\n")
		sb.WriteString("\t// Write vtable offset at buf[4:8]\n")
		sb.WriteString(fmt.Sprintf("\tvtableStart := 4 + %d + dynamicSize\n", tableSize))
		sb.WriteString("\tvtableOffset := int32(vtableStart - 4)\n")
		sb.WriteString("\tfor j := 0; j < 4; j++ {\n")
		sb.WriteString("\t\tbuf[4+j] = byte(vtableOffset >> (j * 8))\n")
		sb.WriteString("\t}\n")

		// Write fields
		sb.WriteString("\tcurrentStringOffset := 4 + " + fmt.Sprintf("%d\n", tableSize))
		for idx, f := range str.Fields {
			capName := toCamelCase(f.Name)
			off := offsets[idx]
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("\t{\n\t\tv := uint32(x.%s)\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tfor j := 0; j < 4; j++ {\n\t\t\tbuf[4+%d+j] = byte(v >> (j * 8))\n\t\t}\n\t}\n", off))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\t{\n\t\tv := uint64(x.%s)\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tfor j := 0; j < 8; j++ {\n\t\t\tbuf[4+%d+j] = byte(v >> (j * 8))\n\t\t}\n\t}\n", off))
			case ast.TypeBool:
				sb.WriteString(fmt.Sprintf("\tif x.%s {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tbuf[4+%d] = 1\n\t}\n", off))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\tif len(x.%s) > 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\trelOffset := uint32(currentStringOffset - (4 + %d))\n", off))
				sb.WriteString(fmt.Sprintf("\t\tfor j := 0; j < 4; j++ {\n\t\t\tbuf[4+%d+j] = byte(relOffset >> (j * 8))\n\t\t}\n", off))
				sb.WriteString(fmt.Sprintf("\t\tstrLen := uint32(len(x.%s))\n", capName))
				sb.WriteString("\t\tfor j := 0; j < 4; j++ {\n\t\t\tbuf[currentStringOffset+j] = byte(strLen >> (j * 8))\n\t\t}\n")
				sb.WriteString(fmt.Sprintf("\t\tcopy(buf[currentStringOffset+4:], x.%s)\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tcurrentStringOffset += 4 + len(x.%s)\n", capName))
				sb.WriteString("\t}\n")
			}
		}

		// Write vtable
		sb.WriteString("\t// Write vtable header\n")
		sb.WriteString(fmt.Sprintf("\tbuf[vtableStart] = byte(%d)\n", vtableSize))
		sb.WriteString(fmt.Sprintf("\tbuf[vtableStart+1] = byte(%d >> 8)\n", vtableSize))
		sb.WriteString(fmt.Sprintf("\tbuf[vtableStart+2] = byte(%d)\n", tableSize))
		sb.WriteString(fmt.Sprintf("\tbuf[vtableStart+3] = byte(%d >> 8)\n", tableSize))
		for idx := range str.Fields {
			off := offsets[idx]
			sb.WriteString(fmt.Sprintf("\tbuf[vtableStart+4+%d] = byte(%d)\n", 2*idx, off))
			sb.WriteString(fmt.Sprintf("\tbuf[vtableStart+4+%d+1] = byte(%d >> 8)\n", 2*idx, off))
		}
		sb.WriteString("\treturn buf\n")
		sb.WriteString("}\n\n")

		// FlatBuffers Unmarshal implementation
		sb.WriteString(fmt.Sprintf("func (x *%s) UnmarshalFlatBuffers(buf []byte) error {\n", str.Name))
		sb.WriteString("\tif len(buf) < 8 {\n\t\treturn fmt.Errorf(\"flatbuffers: buffer too small\")\n\t}\n")
		sb.WriteString("\trootOffset := uint32(buf[0]) | uint32(buf[1])<<8 | uint32(buf[2])<<16 | uint32(buf[3])<<24\n")
		sb.WriteString("\tif int(rootOffset)+4 > len(buf) {\n\t\treturn fmt.Errorf(\"flatbuffers: invalid root offset\")\n\t}\n")
		sb.WriteString("\tvtableOffset := int32(uint32(buf[rootOffset]) | uint32(buf[rootOffset+1])<<8 | uint32(buf[rootOffset+2])<<16 | uint32(buf[rootOffset+3])<<24)\n")
		sb.WriteString("\tvtableStart := int(rootOffset) + int(vtableOffset)\n")
		sb.WriteString("\tif vtableStart < 0 || vtableStart+4 > len(buf) {\n\t\treturn fmt.Errorf(\"flatbuffers: invalid vtable offset\")\n\t}\n")
		sb.WriteString("\tvtableSize := uint16(buf[vtableStart]) | uint16(buf[vtableStart+1])<<8\n")
		// Read fields
		for idx, f := range str.Fields {
			capName := toCamelCase(f.Name)
			voff := 4 + 2*idx
			sb.WriteString(fmt.Sprintf("\tif %d+2 <= int(vtableSize) {\n", voff))
			sb.WriteString(fmt.Sprintf("\t\tfoffset := uint16(buf[vtableStart+%d]) | uint16(buf[vtableStart+%d+1])<<8\n", voff, voff))
			sb.WriteString("\t\tif foffset > 0 {\n")
			sb.WriteString("\t\t\tabsOffset := int(rootOffset) + int(foffset)\n")
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString("\t\t\tif absOffset+4 <= len(buf) {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\tx.%s = int32(uint32(buf[absOffset]) | uint32(buf[absOffset+1])<<8 | uint32(buf[absOffset+2])<<16 | uint32(buf[absOffset+3])<<24)\n", capName))
				sb.WriteString("\t\t\t}\n")
			case ast.TypeInt64:
				sb.WriteString("\t\t\tif absOffset+8 <= len(buf) {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\tx.%s = int64(uint64(buf[absOffset]) | uint64(buf[absOffset+1])<<8 | uint64(buf[absOffset+2])<<16 | uint64(buf[absOffset+3])<<24 | uint64(buf[absOffset+4])<<32 | uint64(buf[absOffset+5])<<40 | uint64(buf[absOffset+6])<<48 | uint64(buf[absOffset+7])<<56)\n", capName))
				sb.WriteString("\t\t\t}\n")
			case ast.TypeBool:
				sb.WriteString("\t\t\tif absOffset < len(buf) {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\tx.%s = buf[absOffset] != 0\n", capName))
				sb.WriteString("\t\t\t}\n")
			case ast.TypeString:
				sb.WriteString("\t\t\tif absOffset+4 <= len(buf) {\n")
				sb.WriteString("\t\t\t\trelOffset := uint32(buf[absOffset]) | uint32(buf[absOffset+1])<<8 | uint32(buf[absOffset+2])<<16 | uint32(buf[absOffset+3])<<24\n")
				sb.WriteString("\t\t\t\tstrStart := absOffset + int(relOffset)\n")
				sb.WriteString("\t\t\t\tif strStart+4 <= len(buf) {\n")
				sb.WriteString("\t\t\t\t\tstrLen := uint32(buf[strStart]) | uint32(buf[strStart+1])<<8 | uint32(buf[strStart+2])<<16 | uint32(buf[strStart+3])<<24\n")
				sb.WriteString("\t\t\t\t\tif strStart+4+int(strLen) <= len(buf) {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\t\t\tx.%s = string(buf[strStart+4 : strStart+4+int(strLen)])\n", capName))
				sb.WriteString("\t\t\t\t\t}\n")
				sb.WriteString("\t\t\t\t}\n")
				sb.WriteString("\t\t\t}\n")
			}
			sb.WriteString("\t\t}\n")
			sb.WriteString("\t}\n")
		}
		sb.WriteString("\treturn nil\n")
		sb.WriteString("}\n\n")

		// Write satisfies thrift.TStruct
		sb.WriteString(fmt.Sprintf("func (x *%s) Write(ctx context.Context, oprot thrift.TProtocol) error {\n", str.Name))
		sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteStructBegin(ctx, \"%s\"); err != nil {\n", str.Name))
		sb.WriteString("\t\treturn err\n")
		sb.WriteString("\t}\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			thriftType := mapThriftTypeConst(f.Type)
			sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteFieldBegin(ctx, \"%s\", thrift.%s, %d); err != nil {\n", f.Name, thriftType, f.ID))
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteI32(ctx, x.%s); err != nil {\n", capName))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteI64(ctx, x.%s); err != nil {\n", capName))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteString(ctx, x.%s); err != nil {\n", capName))
			}
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
			sb.WriteString("\tif err := oprot.WriteFieldEnd(ctx); err != nil {\n")
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
		}
		sb.WriteString("\tif err := oprot.WriteFieldStop(ctx); err != nil {\n")
		sb.WriteString("\t\treturn err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn oprot.WriteStructEnd(ctx)\n")
		sb.WriteString("}\n\n")

		// Read satisfies thrift.TStruct
		sb.WriteString(fmt.Sprintf("func (x *%s) Read(ctx context.Context, iprot thrift.TProtocol) error {\n", str.Name))
		sb.WriteString("\tif _, err := iprot.ReadStructBegin(ctx); err != nil {\n")
		sb.WriteString("\t\treturn err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tfor {\n")
		sb.WriteString("\t\t_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)\n")
		sb.WriteString("\t\tif err != nil {\n")
		sb.WriteString("\t\t\treturn err\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tif fieldTypeId == thrift.STOP {\n")
		sb.WriteString("\t\t\tbreak\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tswitch fieldId {\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			thriftType := mapThriftTypeConst(f.Type)
			sb.WriteString(fmt.Sprintf("\t\tcase %d:\n", f.ID))
			sb.WriteString(fmt.Sprintf("\t\t\tif fieldTypeId == thrift.%s {\n", thriftType))
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("\t\t\t\tif v, err := iprot.ReadI32(ctx); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t} else {\n\t\t\t\t\tx.%s = v\n\t\t\t\t}\n", capName))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\t\t\t\tif v, err := iprot.ReadI64(ctx); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t} else {\n\t\t\t\t\tx.%s = v\n\t\t\t\t}\n", capName))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\t\t\t\tif v, err := iprot.ReadString(ctx); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t} else {\n\t\t\t\t\tx.%s = v\n\t\t\t\t}\n", capName))
			}
			sb.WriteString("\t\t\t} else {\n")
			sb.WriteString("\t\t\t\tiprot.Skip(ctx, fieldTypeId)\n")
			sb.WriteString("\t\t\t}\n")
		}
		sb.WriteString("\t\tdefault:\n")
		sb.WriteString("\t\t\tiprot.Skip(ctx, fieldTypeId)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tif err := iprot.ReadFieldEnd(ctx); err != nil {\n")
		sb.WriteString("\t\t\treturn err\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn iprot.ReadStructEnd(ctx)\n")
		sb.WriteString("}\n\n")
		if str.HasFallback {
			sb.WriteString(fmt.Sprintf("type Lazy%s struct {\n\tdecoded *%s\n}\n\n", str.Name, str.Name))
			sb.WriteString(fmt.Sprintf("func NewLazy%s(raw []byte) *Lazy%s {\n\tvar decoded %s\n\t_ = decoded.Unmarshal(raw)\n\treturn &Lazy%s{decoded: &decoded}\n}\n\n", str.Name, str.Name, str.Name, str.Name))
			for _, f := range str.Fields {
				capName := toCamelCase(f.Name)
				goType := mapGoType(f.Type)
				sb.WriteString(fmt.Sprintf("func (x *Lazy%s) Get%s() (%s, error) {\n", str.Name, capName, goType))
				sb.WriteString(fmt.Sprintf("\treturn x.decoded.%s, nil\n", capName))
				sb.WriteString("}\n\n")
			}

			sb.WriteString(fmt.Sprintf("func (x *%s) TranspileProtobufToThriftCompact(in []byte, out []byte) (int, error) {\n", str.Name))
			sb.WriteString("\treturn 0, fmt.Errorf(\"transpilation unsupported for complex types\")\n")
			sb.WriteString("}\n\n")
		} else {
			// LazyStruct definition
			sb.WriteString(fmt.Sprintf("type Lazy%s struct {\n\traw []byte\n}\n\n", str.Name))
			sb.WriteString(fmt.Sprintf("func NewLazy%s(raw []byte) *Lazy%s {\n\treturn &Lazy%s{raw: raw}\n}\n\n", str.Name, str.Name, str.Name))
			for _, f := range str.Fields {
				capName := toCamelCase(f.Name)
				goType := mapGoType(f.Type)
				sb.WriteString(fmt.Sprintf("func (x *Lazy%s) Get%s() (%s, error) {\n", str.Name, capName, goType))
				sb.WriteString(fmt.Sprintf("\tb, _, err := fastScanField(x.raw, %d)\n", f.ID))
				sb.WriteString("\tif err != nil {\n\t\tvar zero " + goType + "\n\t\treturn zero, err\n\t}\n")
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString("\tv, _, err := readVarint(b, 0)\n\tif err != nil {\n\t\treturn 0, err\n\t}\n\treturn int32(v), nil\n")
				case ast.TypeInt64:
					sb.WriteString("\tv, _, err := readVarint(b, 0)\n\tif err != nil {\n\t\treturn 0, err\n\t}\n\treturn int64(v), nil\n")
				case ast.TypeString:
					sb.WriteString("\treturn unsafeString(b), nil\n")
				default:
					sb.WriteString("\tvar zero " + goType + "\n\treturn zero, fmt.Errorf(\"unsupported lazy type\")\n")
				}
				sb.WriteString("}\n\n")
			}

			// TranspileProtobufToThriftCompact definition
			sb.WriteString(fmt.Sprintf("func (x *%s) TranspileProtobufToThriftCompact(in []byte, out []byte) (int, error) {\n", str.Name))
			sb.WriteString("\tl := len(in)\n")
			sb.WriteString("\tiNdEx := 0\n")
			sb.WriteString("\toutIdx := 0\n")
			sb.WriteString("\tvar err error\n")
			sb.WriteString("\tlastFieldID := int16(0)\n")
			sb.WriteString("\tfor iNdEx < l {\n")
			sb.WriteString("\t\tvar i uint64\n")
			sb.WriteString("\t\ti, iNdEx, err = readVarint(in, iNdEx)\n")
			sb.WriteString("\t\tif err != nil {\n\t\t\treturn 0, err\n\t\t}\n")
			sb.WriteString("\t\tfieldNum := int16(i >> 3)\n")
			sb.WriteString("\t\twireType := int(i & 0x7)\n")
			sb.WriteString("\t\tswitch fieldNum {\n")
			for _, f := range str.Fields {
				sb.WriteString(fmt.Sprintf("\t\tcase %d:\n", f.ID))
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString("\t\t\tvar rawVal uint64\n")
					sb.WriteString("\t\t\trawVal, iNdEx, err = readVarint(in, iNdEx)\n")
					sb.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn 0, err\n\t\t\t}\n")
					sb.WriteString(fmt.Sprintf("\t\t\tdelta := int16(%d) - lastFieldID\n", f.ID))
					sb.WriteString("\t\t\tif delta > 0 && delta <= 15 {\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte((delta << 4) | %d)\n", 5))
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t} else {\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte(%d)\n", 5))
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte(%d >> 8)\n", f.ID))
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx+1] = byte(%d)\n", f.ID))
					sb.WriteString("\t\t\t\toutIdx += 2\n")
					sb.WriteString("\t\t\t}\n")
					sb.WriteString("\t\t\tzz := (rawVal << 1) ^ uint64(int64(rawVal)>>63)\n")
					sb.WriteString("\t\t\tfor {\n")
					sb.WriteString("\t\t\t\tif (zz & ^uint64(0x7F)) == 0 {\n")
					sb.WriteString("\t\t\t\t\tout[outIdx] = byte(zz)\n")
					sb.WriteString("\t\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t\t\tbreak\n")
					sb.WriteString("\t\t\t\t}\n")
					sb.WriteString("\t\t\t\tout[outIdx] = byte((zz & 0x7F) | 0x80)\n")
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t\tzz >>= 7\n")
					sb.WriteString("\t\t\t}\n")
					sb.WriteString(fmt.Sprintf("\t\t\tlastFieldID = int16(%d)\n", f.ID))
				case ast.TypeInt64:
					sb.WriteString("\t\t\tvar rawVal uint64\n")
					sb.WriteString("\t\t\trawVal, iNdEx, err = readVarint(in, iNdEx)\n")
					sb.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn 0, err\n\t\t\t}\n")
					sb.WriteString(fmt.Sprintf("\t\t\tdelta := int16(%d) - lastFieldID\n", f.ID))
					sb.WriteString("\t\t\tif delta > 0 && delta <= 15 {\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte((delta << 4) | %d)\n", 6))
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t} else {\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte(%d)\n", 6))
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte(%d >> 8)\n", f.ID))
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx+1] = byte(%d)\n", f.ID))
					sb.WriteString("\t\t\t\toutIdx += 2\n")
					sb.WriteString("\t\t\t}\n")
					sb.WriteString("\t\t\tzz := (rawVal << 1) ^ uint64(int64(rawVal)>>63)\n")
					sb.WriteString("\t\t\tfor {\n")
					sb.WriteString("\t\t\t\tif (zz & ^uint64(0x7F)) == 0 {\n")
					sb.WriteString("\t\t\t\t\tout[outIdx] = byte(zz)\n")
					sb.WriteString("\t\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t\t\tbreak\n")
					sb.WriteString("\t\t\t\t}\n")
					sb.WriteString("\t\t\t\tout[outIdx] = byte((zz & 0x7F) | 0x80)\n")
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t\tzz >>= 7\n")
					sb.WriteString("\t\t\t}\n")
					sb.WriteString(fmt.Sprintf("\t\t\tlastFieldID = int16(%d)\n", f.ID))
				case ast.TypeString:
					sb.WriteString("\t\t\tvar stringLen uint64\n")
					sb.WriteString("\t\t\tstringLen, iNdEx, err = readVarint(in, iNdEx)\n")
					sb.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn 0, err\n\t\t\t}\n")
					sb.WriteString(fmt.Sprintf("\t\t\tdelta := int16(%d) - lastFieldID\n", f.ID))
					sb.WriteString("\t\t\tif delta > 0 && delta <= 15 {\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte((delta << 4) | %d)\n", 8))
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t} else {\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte(%d)\n", 8))
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx] = byte(%d >> 8)\n", f.ID))
					sb.WriteString(fmt.Sprintf("\t\t\t\tout[outIdx+1] = byte(%d)\n", f.ID))
					sb.WriteString("\t\t\t\toutIdx += 2\n")
					sb.WriteString("\t\t\t}\n")
					sb.WriteString("\t\t\tzz := stringLen\n")
					sb.WriteString("\t\t\tfor {\n")
					sb.WriteString("\t\t\t\tif (zz & ^uint64(0x7F)) == 0 {\n")
					sb.WriteString("\t\t\t\t\tout[outIdx] = byte(zz)\n")
					sb.WriteString("\t\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t\t\tbreak\n")
					sb.WriteString("\t\t\t\t}\n")
					sb.WriteString("\t\t\t\tout[outIdx] = byte((zz & 0x7F) | 0x80)\n")
					sb.WriteString("\t\t\t\toutIdx++\n")
					sb.WriteString("\t\t\t\tzz >>= 7\n")
					sb.WriteString("\t\t\t}\n")
					sb.WriteString("\t\t\tcopy(out[outIdx:], in[iNdEx:iNdEx+int(stringLen)])\n")
					sb.WriteString("\t\t\toutIdx += int(stringLen)\n")
					sb.WriteString("\t\t\tiNdEx += int(stringLen)\n")
				}
			}
			sb.WriteString("\t\tdefault:\n")
			sb.WriteString("\t\t\tvar v uint64\n")
			sb.WriteString("\t\t\tv, iNdEx, err = readVarint(in, iNdEx)\n")
			sb.WriteString("\t\t\tif err != nil {\n\t\t\t\treturn 0, err\n\t\t\t}\n")
			sb.WriteString("\t\t\tif wireType == 0 {\n")
			sb.WriteString("\t\t\t\t// skip\n")
			sb.WriteString("\t\t\t} else if wireType == 2 {\n")
			sb.WriteString("\t\t\t\tiNdEx += int(v)\n")
			sb.WriteString("\t\t\t}\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString("\t}\n")
			sb.WriteString("\tout[outIdx] = 0\n")
			sb.WriteString("\toutIdx++\n")
			sb.WriteString("\treturn outIdx, nil\n")
			sb.WriteString("}\n\n")
		}
	}

	// Generate Service Interfaces
	for _, srv := range parsed.Services {
		sb.WriteString(fmt.Sprintf("type %s interface {\n", srv.Name))
		for _, m := range srv.Methods {
			sb.WriteString(fmt.Sprintf("\t%s(ctx context.Context, req *%s) (*%s, error)\n",
				m.Name, m.InputType, m.OutputType))
		}
		sb.WriteString("}\n\n")

		// Create dynamic handler wrapper for sniffing connection runtime dispatching
		sb.WriteString(fmt.Sprintf("type %sProcessor struct {\n", srv.Name))
		sb.WriteString(fmt.Sprintf("\thandler %s\n", srv.Name))
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("func New%sProcessor(handler %s) *%sProcessor {\n", srv.Name, srv.Name, srv.Name))
		sb.WriteString(fmt.Sprintf("\treturn &%sProcessor{handler: handler}\n", srv.Name))
		sb.WriteString("}\n\n")

		// Implement Thrift Process method
		sb.WriteString(fmt.Sprintf("func (p *%sProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (bool, thrift.TException) {\n", srv.Name))
		sb.WriteString("\tname, _, seqId, err := iprot.ReadMessageBegin(ctx)\n")
		sb.WriteString("\tif err != nil {\n")
		sb.WriteString("\t\treturn false, thrift.WrapTException(err)\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tswitch name {\n")
		for _, m := range srv.Methods {
			sb.WriteString(fmt.Sprintf("\tcase \"%s\":\n", m.Name))
			sb.WriteString(fmt.Sprintf("\t\targs := &%s{}\n", m.InputType))
			sb.WriteString("\t\tif err := args.Read(ctx, iprot); err != nil {\n")
			sb.WriteString("\t\t\treturn false, thrift.WrapTException(err)\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString("\t\tiprot.ReadMessageEnd(ctx)\n")
			sb.WriteString(fmt.Sprintf("\t\tres, err := p.handler.%s(ctx, args)\n", m.Name))
			sb.WriteString("\t\tif err != nil {\n")
			sb.WriteString("\t\t\tx := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, err.Error())\n")
			sb.WriteString(fmt.Sprintf("\t\t\toprot.WriteMessageBegin(ctx, \"%s\", thrift.EXCEPTION, seqId)\n", m.Name))
			sb.WriteString("\t\t\tx.Write(ctx, oprot)\n")
			sb.WriteString("\t\t\toprot.WriteMessageEnd(ctx)\n")
			sb.WriteString("\t\t\toprot.Flush(ctx)\n")
			sb.WriteString("\t\t\treturn true, thrift.WrapTException(err)\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString(fmt.Sprintf("\t\toprot.WriteMessageBegin(ctx, \"%s\", thrift.REPLY, seqId)\n", m.Name))
			sb.WriteString("\t\tres.Write(ctx, oprot)\n")
			sb.WriteString("\t\toprot.WriteMessageEnd(ctx)\n")
			sb.WriteString("\t\toprot.Flush(ctx)\n")
			sb.WriteString("\t\treturn true, nil\n")
		}
		sb.WriteString("\tdefault:\n")
		sb.WriteString("\t\treturn false, thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, \"unknown method \"+name)\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// Generate zero-reflection GRPCHandler registration stub
		sb.WriteString(fmt.Sprintf("func Register%s(server *runtime.Server, impl %s) {\n", srv.Name, srv.Name))
		for _, m := range srv.Methods {
			packagePrefix := parsed.Namespace
			if packagePrefix == "" {
				packagePrefix = "helix_example"
			}
			pathDot := fmt.Sprintf("/%s.%s/%s", packagePrefix, srv.Name, m.Name)
			pathUnderscore := fmt.Sprintf("/%s.%s/%s", strings.ReplaceAll(packagePrefix, ".", "_"), srv.Name, m.Name)

			if m.RESTMethod != "" && m.RESTPath != "" {
				sb.WriteString(fmt.Sprintf("\tserver.RegisterRESTRoute(\"%s\", \"%s\", \"%s\")\n", m.RESTMethod, m.RESTPath, pathDot))
			}

			// Register dot path
			sb.WriteString(fmt.Sprintf("\tserver.RegisterMethod(\"%s\", runtime.MethodInfo{\n", pathDot))
			sb.WriteString(fmt.Sprintf("\t\tDecoder: func(dec func(interface{}) error) (interface{}, error) {\n"))
			sb.WriteString(fmt.Sprintf("\t\t\treq := &%s{}\n", m.InputType))
			sb.WriteString("\t\t\tif err := dec(req); err != nil {\n")
			sb.WriteString("\t\t\t\treturn nil, err\n")
			sb.WriteString("\t\t\t}\n")
			sb.WriteString("\t\t\treturn req, nil\n")
			sb.WriteString("\t\t},\n")
			sb.WriteString(fmt.Sprintf("\t\tHandler: func(ctx context.Context, req interface{}) (interface{}, error) {\n"))
			sb.WriteString(fmt.Sprintf("\t\t\treturn impl.%s(ctx, req.(*%s))\n", m.Name, m.InputType))
			sb.WriteString("\t\t},\n")
			sb.WriteString(generateBinderString(m, parsed))
			sb.WriteString("\t})\n")

			// Register underscore path if it differs
			if pathDot != pathUnderscore {
				sb.WriteString(fmt.Sprintf("\tserver.RegisterMethod(\"%s\", runtime.MethodInfo{\n", pathUnderscore))
				sb.WriteString(fmt.Sprintf("\t\tDecoder: func(dec func(interface{}) error) (interface{}, error) {\n"))
				sb.WriteString(fmt.Sprintf("\t\t\treq := &%s{}\n", m.InputType))
				sb.WriteString("\t\t\tif err := dec(req); err != nil {\n")
				sb.WriteString("\t\t\t\treturn nil, err\n")
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\treturn req, nil\n")
				sb.WriteString("\t\t},\n")
				sb.WriteString(fmt.Sprintf("\t\tHandler: func(ctx context.Context, req interface{}) (interface{}, error) {\n"))
				sb.WriteString(fmt.Sprintf("\t\t\treturn impl.%s(ctx, req.(*%s))\n", m.Name, m.InputType))
				sb.WriteString("\t\t},\n")
				sb.WriteString(generateBinderString(m, parsed))
				sb.WriteString("\t})\n")
			}
		}
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if parts[i] == "id" {
			parts[i] = "ID"
		} else {
			parts[i] = capitalize(parts[i])
		}
	}
	return strings.Join(parts, "")
}

func mapGoType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int32"
	case ast.TypeInt64:
		return "int64"
	case ast.TypeString:
		return "string"
	case ast.TypeBinary:
		return "[]byte"
	case ast.TypeBool:
		return "bool"
	case ast.TypeDouble:
		return "float64"
	case ast.TypeStruct:
		return "*" + t.Name
	default:
		return "interface{}"
	}
}

func mapProtoType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int32"
	case ast.TypeInt64:
		return "int64"
	case ast.TypeString:
		return "string"
	case ast.TypeBinary:
		return "bytes"
	case ast.TypeBool:
		return "bool"
	default:
		return "string"
	}
}

func mapThriftTypeConst(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "I32"
	case ast.TypeInt64:
		return "I64"
	case ast.TypeString:
		return "STRING"
	case ast.TypeBinary:
		return "STRING" // Thrift maps binary to string internally in go TProtocol
	case ast.TypeBool:
		return "BOOL"
	case ast.TypeStruct:
		return "STRUCT"
	default:
		return "STOP"
	}
}

func generateBinderString(m *ast.MethodNode, parsed *ast.AST) string {
	var sb strings.Builder
	sb.WriteString("\t\tBinder: func(req interface{}, params map[string]string) error {\n")
	sb.WriteString(fmt.Sprintf("\t\t\tp, ok := req.(*%s)\n", m.InputType))
	sb.WriteString("\t\t\tif !ok {\n")
	sb.WriteString("\t\t\t\treturn fmt.Errorf(\"invalid request type for binder\")\n")
	sb.WriteString("\t\t\t}\n")

	var inputStruct *ast.StructNode
	for i := range parsed.Structs {
		if parsed.Structs[i].Name == m.InputType {
			inputStruct = parsed.Structs[i]
			break
		}
	}
	if inputStruct != nil {
		for _, f := range inputStruct.Fields {
			capName := toCamelCase(f.Name)
			jsonTag := f.Name
			sb.WriteString(fmt.Sprintf("\t\t\tif val, ok := params[\"%s\"]; ok {\n", jsonTag))
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString("\t\t\t\tvar id int32\n")
				sb.WriteString("\t\t\t\tif _, err := fmt.Sscanf(val, \"%d\", &id); err == nil {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\t\tp.%s = id\n", capName))
				sb.WriteString("\t\t\t\t}\n")
			case ast.TypeInt64:
				sb.WriteString("\t\t\t\tvar id int64\n")
				sb.WriteString("\t\t\t\tif _, err := fmt.Sscanf(val, \"%d\", &id); err == nil {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\t\tp.%s = id\n", capName))
				sb.WriteString("\t\t\t\t}\n")
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\t\t\t\tp.%s = val\n", capName))
			case ast.TypeBool:
				sb.WriteString("\t\t\t\tvar b bool\n")
				sb.WriteString("\t\t\t\tif _, err := fmt.Sscanf(val, \"%t\", &b); err == nil {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\t\tp.%s = b\n", capName))
				sb.WriteString("\t\t\t\t}\n")
			}
			sb.WriteString("\t\t\t}\n")
		}
	}
	sb.WriteString("\t\t\treturn nil\n")
	sb.WriteString("\t\t},\n")
	return sb.String()
}
