package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

func GenerateGo(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by helix-gen. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", strings.ReplaceAll(parsed.Namespace, ".", "_")))

	// Write standard imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"github.com/golang/protobuf/proto\"\n")
	sb.WriteString("\t\"github.com/apache/thrift/lib/go/thrift\"\n")
	sb.WriteString("\truntime \"github.com/helix-rpc/helix/runtime-go\"\n")
	sb.WriteString(")\n\n")

	// Helper functions for protobuf serialization (varints)
	sb.WriteString(`func writeVarint(buf []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		buf[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	buf[offset] = uint8(v)
	return offset + 1
}

func readVarint(buf []byte, offset int) (uint64, int, error) {
	var v uint64
	var shift uint
	for {
		if offset >= len(buf) {
			return 0, 0, fmt.Errorf("unexpected EOF reading varint")
		}
		b := buf[offset]
		offset++
		v |= uint64(b&0x7f) << shift
		if b&0x80 == 0 {
			break
		}
		shift += 7
	}
	return v, offset, nil
}
`)
	sb.WriteString("\n")

	// Generate Structs
	for _, str := range parsed.Structs {
		// Define the struct
		sb.WriteString(fmt.Sprintf("type %s struct {\n", str.Name))
		for _, f := range str.Fields {
			goType := mapGoType(f.Type)
			protoTag := fmt.Sprintf("%s,%d", mapProtoType(f.Type), f.ID)
			thriftTag := fmt.Sprintf("%s,%d", f.Name, f.ID)
			sb.WriteString(fmt.Sprintf("\t%s %s `thrift:\"%s\" json:\"%s\" proto:\"%s\"`\n",
				toCamelCase(f.Name), goType, thriftTag, f.Name, protoTag))
		}
		sb.WriteString("}\n\n")

		// Satisfy proto.Message
		sb.WriteString(fmt.Sprintf("func (x *%s) Reset()         { *x = %s{} }\n", str.Name, str.Name))
		sb.WriteString(fmt.Sprintf("func (x *%s) String() string { return proto.CompactTextString(x) }\n", str.Name))
		sb.WriteString(fmt.Sprintf("func (x *%s) ProtoMessage()  {}\n\n", str.Name))

		// Marshal interface
		sb.WriteString(fmt.Sprintf("func (x *%s) Marshal() ([]byte, error) {\n", str.Name))
		sb.WriteString("\tbuf := make([]byte, x.ProtoSize())\n")
		sb.WriteString("\t_, err := x.MarshalTo(buf)\n")
		sb.WriteString("\treturn buf, err\n")
		sb.WriteString("}\n\n")

		// ProtoSize calculations
		sb.WriteString(fmt.Sprintf("func (x *%s) ProtoSize() (size int) {\n", str.Name))
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\tif x.%s != 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tsize += 1 + sizeOfVarint(uint64(x.%s))\n", capName))
				sb.WriteString("\t}\n")
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\tif len(x.%s) > 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tsize += 1 + sizeOfVarint(uint64(len(x.%s))) + len(x.%s)\n", capName, capName))
				sb.WriteString("\t}\n")
			}
		}
		sb.WriteString("\treturn size\n")
		sb.WriteString("}\n\n")

		// sizeOfVarint helper
		sb.WriteString(`func sizeOfVarint(v uint64) int {
	if v == 0 {
		return 1
	}
	size := 0
	for v > 0 {
		size++
		v >>= 7
	}
	return size
}

`)

		// MarshalTo calculations
		sb.WriteString(fmt.Sprintf("func (x *%s) MarshalTo(dAtA []byte) (int, error) {\n", str.Name))
		sb.WriteString("\tvar i int\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			// Tag field key = (field_number << 3) | wire_type
			wireType := 0 // varint
			if f.Type.Kind == ast.TypeString || f.Type.Kind == ast.TypeBinary {
				wireType = 2 // length-delimited
			}
			tagVal := (f.ID << 3) | int32(wireType)

			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\tif x.%s != 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tdAtA[i] = 0x%x\n", tagVal))
				sb.WriteString("\t\ti++\n")
				sb.WriteString(fmt.Sprintf("\t\ti = writeVarint(dAtA, i, uint64(x.%s))\n", capName))
				sb.WriteString("\t}\n")
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\tif len(x.%s) > 0 {\n", capName))
				sb.WriteString(fmt.Sprintf("\t\tdAtA[i] = 0x%x\n", tagVal))
				sb.WriteString("\t\ti++\n")
				sb.WriteString(fmt.Sprintf("\t\ti = writeVarint(dAtA, i, uint64(len(x.%s)))\n", capName))
				sb.WriteString(fmt.Sprintf("\t\ti += copy(dAtA[i:], x.%s)\n", capName))
				sb.WriteString("\t}\n")
			}
		}
		sb.WriteString("\treturn i, nil\n")
		sb.WriteString("}\n\n")

		// Unmarshal implementation
		sb.WriteString(fmt.Sprintf("func (x *%s) Unmarshal(dAtA []byte) error {\n", str.Name))
		sb.WriteString("\tl := len(dAtA)\n")
		sb.WriteString("\tiNdEx := 0\n")
		sb.WriteString("\tfor iNdEx < l {\n")
		sb.WriteString("\t\tpostIndex := 0\n")
		sb.WriteString("\t\tvar i uint64\n")
		sb.WriteString("\t\tvar err error\n")
		sb.WriteString("\t\ti, iNdEx, err = readVarint(dAtA, iNdEx)\n")
		sb.WriteString("\t\tif err != nil {\n")
		sb.WriteString("\t\t\treturn err\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tfieldNum := int32(i >> 3)\n")
		sb.WriteString("\t\twireType := int(i & 0x7)\n")
		sb.WriteString("\t\tif wireType == 4 {\n")
		sb.WriteString(fmt.Sprintf("\t\t\treturn fmt.Errorf(\"proto: %s: wiretype end group for non-group\")\n", str.Name))
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tswitch fieldNum {\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			sb.WriteString(fmt.Sprintf("\t\tcase %d:\n", f.ID))
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeInt64:
				sb.WriteString("\t\t\tif wireType != 0 {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\treturn fmt.Errorf(\"proto: wrong wireType = %%d for field %s\", wireType)\n", capName))
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\tvar v uint64\n")
				sb.WriteString("\t\t\tv, iNdEx, err = readVarint(dAtA, iNdEx)\n")
				sb.WriteString("\t\t\tif err != nil {\n")
				sb.WriteString("\t\t\t\treturn err\n")
				sb.WriteString("\t\t\t}\n")
				if f.Type.Kind == ast.TypeInt32 {
					sb.WriteString(fmt.Sprintf("\t\t\tx.%s = int32(v)\n", capName))
				} else {
					sb.WriteString(fmt.Sprintf("\t\t\tx.%s = int64(v)\n", capName))
				}
			case ast.TypeString:
				sb.WriteString("\t\t\tif wireType != 2 {\n")
				sb.WriteString(fmt.Sprintf("\t\t\t\treturn fmt.Errorf(\"proto: wrong wireType = %%d for field %s\", wireType)\n", capName))
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\tvar stringLen uint64\n")
				sb.WriteString("\t\t\tstringLen, iNdEx, err = readVarint(dAtA, iNdEx)\n")
				sb.WriteString("\t\t\tif err != nil {\n")
				sb.WriteString("\t\t\t\treturn err\n")
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\tpostIndex = iNdEx + int(stringLen)\n")
				sb.WriteString("\t\t\tif postIndex < 0 || postIndex > l {\n")
				sb.WriteString("\t\t\t\treturn fmt.Errorf(\"unexpected EOF\")\n")
				sb.WriteString("\t\t\t}\n")
				sb.WriteString(fmt.Sprintf("\t\t\tx.%s = string(dAtA[iNdEx:postIndex])\n", capName))
				sb.WriteString("\t\t\tiNdEx = postIndex\n")
			}
		}
		sb.WriteString("\t\tdefault:\n")
		// skip unknown field
		sb.WriteString("\t\t\tvar v uint64\n")
		sb.WriteString("\t\t\tv, iNdEx, err = readVarint(dAtA, iNdEx)\n")
		sb.WriteString("\t\t\tif err != nil {\n")
		sb.WriteString("\t\t\t\treturn err\n")
		sb.WriteString("\t\t\t}\n")
		sb.WriteString("\t\t\tif wireType == 0 {\n")
		sb.WriteString("\t\t\t\t// already read varint\n")
		sb.WriteString("\t\t\t} else if wireType == 2 {\n")
		sb.WriteString("\t\t\t\tpostIndex = iNdEx + int(v)\n")
		sb.WriteString("\t\t\t\tiNdEx = postIndex\n")
		sb.WriteString("\t\t\t} else {\n")
		sb.WriteString("\t\t\t\treturn fmt.Errorf(\"unhandled wireType in unmarshal skip\")\n")
		sb.WriteString("\t\t\t}\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn nil\n")
		sb.WriteString("}\n\n")

		// Write satisfies thrift.TStruct
		sb.WriteString(fmt.Sprintf("func (x *%s) Write(ctx context.Context, oprot thrift.TProtocol) error {\n", str.Name))
		sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteStructBegin(ctx, \"%s\"); err != nil {\n", str.Name))
		sb.WriteString("\t\treturn err\n")
		sb.WriteString("\t}\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			thriftType := mapThriftTypeConst(f.Type)
			sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteFieldBegin(ctx, \"%s\", thrift.%s, %d); err != nil {\n", f.Name, thriftType, f.ID))
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteI32(ctx, x.%s); err != nil {\n", capName))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteI64(ctx, x.%s); err != nil {\n", capName))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\tif err := oprot.WriteString(ctx, x.%s); err != nil {\n", capName))
			}
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
			sb.WriteString("\tif err := oprot.WriteFieldEnd(ctx); err != nil {\n")
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
		}
		sb.WriteString("\tif err := oprot.WriteFieldStop(ctx); err != nil {\n")
		sb.WriteString("\t\treturn err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn oprot.WriteStructEnd(ctx)\n")
		sb.WriteString("}\n\n")

		// Read satisfies thrift.TStruct
		sb.WriteString(fmt.Sprintf("func (x *%s) Read(ctx context.Context, iprot thrift.TProtocol) error {\n", str.Name))
		sb.WriteString("\tif _, err := iprot.ReadStructBegin(ctx); err != nil {\n")
		sb.WriteString("\t\treturn err\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tfor {\n")
		sb.WriteString("\t\t_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)\n")
		sb.WriteString("\t\tif err != nil {\n")
		sb.WriteString("\t\t\treturn err\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tif fieldTypeId == thrift.STOP {\n")
		sb.WriteString("\t\t\tbreak\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tswitch fieldId {\n")
		for _, f := range str.Fields {
			capName := toCamelCase(f.Name)
			thriftType := mapThriftTypeConst(f.Type)
			sb.WriteString(fmt.Sprintf("\t\tcase %d:\n", f.ID))
			sb.WriteString(fmt.Sprintf("\t\t\tif fieldTypeId == thrift.%s {\n", thriftType))
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("\t\t\t\tif v, err := iprot.ReadI32(ctx); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t} else {\n\t\t\t\t\tx.%s = v\n\t\t\t\t}\n", capName))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("\t\t\t\tif v, err := iprot.ReadI64(ctx); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t} else {\n\t\t\t\t\tx.%s = v\n\t\t\t\t}\n", capName))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("\t\t\t\tif v, err := iprot.ReadString(ctx); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t} else {\n\t\t\t\t\tx.%s = v\n\t\t\t\t}\n", capName))
			}
			sb.WriteString("\t\t\t} else {\n")
			sb.WriteString("\t\t\t\tiprot.Skip(ctx, fieldTypeId)\n")
			sb.WriteString("\t\t\t}\n")
		}
		sb.WriteString("\t\tdefault:\n")
		sb.WriteString("\t\t\tiprot.Skip(ctx, fieldTypeId)\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t\tif err := iprot.ReadFieldEnd(ctx); err != nil {\n")
		sb.WriteString("\t\t\treturn err\n")
		sb.WriteString("\t\t}\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\treturn iprot.ReadStructEnd(ctx)\n")
		sb.WriteString("}\n\n")
	}

	// Generate Service Interfaces
	for _, srv := range parsed.Services {
		sb.WriteString(fmt.Sprintf("type %s interface {\n", srv.Name))
		for _, m := range srv.Methods {
			sb.WriteString(fmt.Sprintf("\t%s(ctx context.Context, req *%s) (*%s, error)\n",
				m.Name, m.InputType, m.OutputType))
		}
		sb.WriteString("}\n\n")

		// Create dynamic handler wrapper for sniffing connection runtime dispatching
		sb.WriteString(fmt.Sprintf("type %sProcessor struct {\n", srv.Name))
		sb.WriteString(fmt.Sprintf("\thandler %s\n", srv.Name))
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("func New%sProcessor(handler %s) *%sProcessor {\n", srv.Name, srv.Name, srv.Name))
		sb.WriteString(fmt.Sprintf("\treturn &%sProcessor{handler: handler}\n", srv.Name))
		sb.WriteString("}\n\n")

		// Implement Thrift Process method
		sb.WriteString(fmt.Sprintf("func (p *%sProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (bool, thrift.TException) {\n", srv.Name))
		sb.WriteString("\tname, _, seqId, err := iprot.ReadMessageBegin(ctx)\n")
		sb.WriteString("\tif err != nil {\n")
		sb.WriteString("\t\treturn false, thrift.WrapTException(err)\n")
		sb.WriteString("\t}\n")
		sb.WriteString("\tswitch name {\n")
		for _, m := range srv.Methods {
			sb.WriteString(fmt.Sprintf("\tcase \"%s\":\n", m.Name))
			sb.WriteString(fmt.Sprintf("\t\targs := &%s{}\n", m.InputType))
			sb.WriteString("\t\tif err := args.Read(ctx, iprot); err != nil {\n")
			sb.WriteString("\t\t\treturn false, thrift.WrapTException(err)\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString("\t\tiprot.ReadMessageEnd(ctx)\n")
			sb.WriteString(fmt.Sprintf("\t\tres, err := p.handler.%s(ctx, args)\n", m.Name))
			sb.WriteString("\t\tif err != nil {\n")
			sb.WriteString("\t\t\tx := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, err.Error())\n")
			sb.WriteString(fmt.Sprintf("\t\t\toprot.WriteMessageBegin(ctx, \"%s\", thrift.EXCEPTION, seqId)\n", m.Name))
			sb.WriteString("\t\t\tx.Write(ctx, oprot)\n")
			sb.WriteString("\t\t\toprot.WriteMessageEnd(ctx)\n")
			sb.WriteString("\t\t\toprot.Flush(ctx)\n")
			sb.WriteString("\t\t\treturn true, thrift.WrapTException(err)\n")
			sb.WriteString("\t\t}\n")
			sb.WriteString(fmt.Sprintf("\t\toprot.WriteMessageBegin(ctx, \"%s\", thrift.REPLY, seqId)\n", m.Name))
			sb.WriteString("\t\tres.Write(ctx, oprot)\n")
			sb.WriteString("\t\toprot.WriteMessageEnd(ctx)\n")
			sb.WriteString("\t\toprot.Flush(ctx)\n")
			sb.WriteString("\t\treturn true, nil\n")
		}
		sb.WriteString("\tdefault:\n")
		sb.WriteString("\t\treturn false, thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, \"unknown method \"+name)\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")

		// Generate zero-reflection GRPCHandler registration stub
		sb.WriteString(fmt.Sprintf("func Register%s(server *runtime.Server, impl %s) {\n", srv.Name, srv.Name))
		for _, m := range srv.Methods {
			packagePrefix := parsed.Namespace
			if packagePrefix == "" {
				packagePrefix = "helix_example"
			}
			pathDot := fmt.Sprintf("/%s.%s/%s", packagePrefix, srv.Name, m.Name)
			pathUnderscore := fmt.Sprintf("/%s.%s/%s", strings.ReplaceAll(packagePrefix, ".", "_"), srv.Name, m.Name)

			// Register dot path
			sb.WriteString(fmt.Sprintf("\tserver.RegisterMethod(\"%s\", runtime.MethodInfo{\n", pathDot))
			sb.WriteString(fmt.Sprintf("\t\tDecoder: func(dec func(interface{}) error) (interface{}, error) {\n"))
			sb.WriteString(fmt.Sprintf("\t\t\treq := &%s{}\n", m.InputType))
			sb.WriteString("\t\t\tif err := dec(req); err != nil {\n")
			sb.WriteString("\t\t\t\treturn nil, err\n")
			sb.WriteString("\t\t\t}\n")
			sb.WriteString("\t\t\treturn req, nil\n")
			sb.WriteString("\t\t},\n")
			sb.WriteString(fmt.Sprintf("\t\tHandler: func(ctx context.Context, req interface{}) (interface{}, error) {\n"))
			sb.WriteString(fmt.Sprintf("\t\t\treturn impl.%s(ctx, req.(*%s))\n", m.Name, m.InputType))
			sb.WriteString("\t\t},\n")
			sb.WriteString("\t})\n")

			// Register underscore path if it differs
			if pathDot != pathUnderscore {
				sb.WriteString(fmt.Sprintf("\tserver.RegisterMethod(\"%s\", runtime.MethodInfo{\n", pathUnderscore))
				sb.WriteString(fmt.Sprintf("\t\tDecoder: func(dec func(interface{}) error) (interface{}, error) {\n"))
				sb.WriteString(fmt.Sprintf("\t\t\treq := &%s{}\n", m.InputType))
				sb.WriteString("\t\t\tif err := dec(req); err != nil {\n")
				sb.WriteString("\t\t\t\treturn nil, err\n")
				sb.WriteString("\t\t\t}\n")
				sb.WriteString("\t\t\treturn req, nil\n")
				sb.WriteString("\t\t},\n")
				sb.WriteString(fmt.Sprintf("\t\tHandler: func(ctx context.Context, req interface{}) (interface{}, error) {\n"))
				sb.WriteString(fmt.Sprintf("\t\t\treturn impl.%s(ctx, req.(*%s))\n", m.Name, m.InputType))
				sb.WriteString("\t\t},\n")
				sb.WriteString("\t})\n")
			}
		}
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if parts[i] == "id" {
			parts[i] = "ID"
		} else {
			parts[i] = capitalize(parts[i])
		}
	}
	return strings.Join(parts, "")
}

func mapGoType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int32"
	case ast.TypeInt64:
		return "int64"
	case ast.TypeString:
		return "string"
	case ast.TypeBinary:
		return "[]byte"
	case ast.TypeBool:
		return "bool"
	case ast.TypeDouble:
		return "float64"
	case ast.TypeStruct:
		return "*" + t.Name
	default:
		return "interface{}"
	}
}

func mapProtoType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int32"
	case ast.TypeInt64:
		return "int64"
	case ast.TypeString:
		return "string"
	case ast.TypeBinary:
		return "bytes"
	case ast.TypeBool:
		return "bool"
	default:
		return "string"
	}
}

func mapThriftTypeConst(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "I32"
	case ast.TypeInt64:
		return "I64"
	case ast.TypeString:
		return "STRING"
	case ast.TypeBinary:
		return "STRING" // Thrift maps binary to string internally in go TProtocol
	case ast.TypeBool:
		return "BOOL"
	case ast.TypeStruct:
		return "STRUCT"
	default:
		return "STOP"
	}
}
