package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

// GenerateJava produces Java class stubs from the AST.
func GenerateJava(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Automatically generated by Helix RPC. DO NOT EDIT.\n")
	sb.WriteString("package io.helixrpc.generated;\n\n")
	sb.WriteString("import java.util.List;\n")
	sb.WriteString("import java.util.NoSuchElementException;\n")
	sb.WriteString("import java.nio.ByteBuffer;\n")
	sb.WriteString("import java.nio.charset.StandardCharsets;\n\n")

	// Global helpers class inside the package
	sb.WriteString(`class HelixHelpers {
    public static long readVarint(ByteBuffer buf) {
        long v = 0;
        int shift = 0;
        while (true) {
            byte b = buf.get();
            v |= (long)(b & 0x7F) << shift;
            if ((b & 0x80) == 0) break;
            shift += 7;
        }
        return v;
    }

    public static void writeThriftVarint(ByteBuffer buf, long v) {
        while (true) {
            if ((v & ~0x7FL) == 0) {
                buf.put((byte)v);
                break;
            }
            buf.put((byte)((v & 0x7F) | 0x80));
            v >>>= 7;
        }
    }

    public static void writeThriftI16(ByteBuffer buf, int v) {
        buf.put((byte)((v >> 8) & 0xFF));
        buf.put((byte)(v & 0xFF));
    }

    public static ByteBuffer fastScanField(ByteBuffer buf, int targetField, int[] outWireType) {
        ByteBuffer dup = buf.duplicate();
        while (dup.hasRemaining()) {
            long tag = readVarint(dup);
            int fieldNum = (int)(tag >>> 3);
            int wireType = (int)(tag & 0x7);
            if (fieldNum == targetField) {
                outWireType[0] = wireType;
                if (wireType == 2) {
                    long len = readVarint(dup);
                    int start = dup.position();
                    dup.limit(start + (int)len);
                    return dup.slice();
                } else if (wireType == 0) {
                    int start = dup.position();
                    readVarint(dup);
                    int end = dup.position();
                    ByteBuffer slice = dup.duplicate();
                    slice.position(start);
                    slice.limit(end);
                    return slice.slice();
                }
                throw new RuntimeException("unsupported wireType: " + wireType);
            }
            if (wireType == 0) {
                readVarint(dup);
            } else if (wireType == 2) {
                long len = readVarint(dup);
                dup.position(dup.position() + (int)len);
            } else {
                throw new RuntimeException("unknown wireType: " + wireType);
            }
        }
        throw new NoSuchElementException("field not found");
    }
}

`)

	for _, str := range parsed.Structs {
		// Struct definition
		sb.WriteString(fmt.Sprintf("public class %s {\n", str.Name))
		for _, f := range str.Fields {
			javaType := getJavaType(f.Type)
			sb.WriteString(fmt.Sprintf("    public %s %s;\n", javaType, f.Name))
		}

		// Static transpiler method
		sb.WriteString("\n    public static ByteBuffer transpileProtobufToThriftCompact(ByteBuffer input, ByteBuffer output) {\n")
		sb.WriteString("        ByteBuffer out = output.duplicate();\n")
		sb.WriteString("        ByteBuffer in = input.duplicate();\n")
		sb.WriteString("        int lastField = 0;\n")
		sb.WriteString("        while (in.hasRemaining()) {\n")
		sb.WriteString("            long tag = HelixHelpers.readVarint(in);\n")
		sb.WriteString("            int fieldNum = (int)(tag >>> 3);\n")
		sb.WriteString("            int wireType = (int)(tag & 0x7);\n")
		sb.WriteString("            int delta = fieldNum - lastField;\n")
		sb.WriteString("            switch (fieldNum) {\n")

		for _, f := range str.Fields {
			sb.WriteString(fmt.Sprintf("                case %d: {\n", f.ID))
			sb.WriteString("                    int typeNibble = 0;\n")
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString("                    typeNibble = 0x05;\n")
				sb.WriteString("                    long val = HelixHelpers.readVarint(in);\n")
				sb.WriteString("                    long zigzag = (val << 1) ^ (val >> 63);\n")
				sb.WriteString("                    if (delta > 0 && delta <= 15) {\n")
				sb.WriteString("                        out.put((byte)((delta << 4) | typeNibble));\n")
				sb.WriteString("                    } else {\n")
				sb.WriteString("                        out.put((byte)typeNibble);\n")
				sb.WriteString("                        HelixHelpers.writeThriftI16(out, fieldNum);\n")
				sb.WriteString("                    }\n")
				sb.WriteString("                    HelixHelpers.writeThriftVarint(out, zigzag);\n")
			case ast.TypeInt64:
				sb.WriteString("                    typeNibble = 0x06;\n")
				sb.WriteString("                    long val = HelixHelpers.readVarint(in);\n")
				sb.WriteString("                    long zigzag = (val << 1) ^ (val >> 63);\n")
				sb.WriteString("                    if (delta > 0 && delta <= 15) {\n")
				sb.WriteString("                        out.put((byte)((delta << 4) | typeNibble));\n")
				sb.WriteString("                    } else {\n")
				sb.WriteString("                        out.put((byte)typeNibble);\n")
				sb.WriteString("                        HelixHelpers.writeThriftI16(out, fieldNum);\n")
				sb.WriteString("                    }\n")
				sb.WriteString("                    HelixHelpers.writeThriftVarint(out, zigzag);\n")
			case ast.TypeString, ast.TypeBinary:
				sb.WriteString("                    typeNibble = 0x08;\n")
				sb.WriteString("                    long len = HelixHelpers.readVarint(in);\n")
				sb.WriteString("                    if (delta > 0 && delta <= 15) {\n")
				sb.WriteString("                        out.put((byte)((delta << 4) | typeNibble));\n")
				sb.WriteString("                    } else {\n")
				sb.WriteString("                        out.put((byte)typeNibble);\n")
				sb.WriteString("                        HelixHelpers.writeThriftI16(out, fieldNum);\n")
				sb.WriteString("                    }\n")
				sb.WriteString("                    HelixHelpers.writeThriftVarint(out, len);\n")
				sb.WriteString("                    byte[] data = new byte[(int)len];\n")
				sb.WriteString("                    in.get(data);\n")
				sb.WriteString("                    out.put(data);\n")
			}
			sb.WriteString("                    lastField = fieldNum;\n")
			sb.WriteString("                    break;\n")
			sb.WriteString("                }\n")
		}

		sb.WriteString("                default:\n")
		sb.WriteString("                    if (wireType == 0) HelixHelpers.readVarint(in);\n")
		sb.WriteString("                    else if (wireType == 2) { long len = HelixHelpers.readVarint(in); in.position(in.position() + (int)len); }\n")
		sb.WriteString("                    break;\n")
		sb.WriteString("            }\n")
		sb.WriteString("        }\n")
		sb.WriteString("        out.put((byte)0x00);\n")
		sb.WriteString("        out.flip();\n")
		sb.WriteString("        return out;\n")
		sb.WriteString("    }\n")
		sb.WriteString("}\n\n")

		// Lazy class
		sb.WriteString(fmt.Sprintf("public class Lazy%s {\n", str.Name))
		sb.WriteString("    private final ByteBuffer raw;\n")
		sb.WriteString(fmt.Sprintf("    public Lazy%s(ByteBuffer raw) { this.raw = raw; }\n\n", str.Name))

		for _, f := range str.Fields {
			fNameTitle := strings.Title(f.Name)
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("    public int get%s() {\n", fNameTitle))
				sb.WriteString(fmt.Sprintf("        ByteBuffer b = HelixHelpers.fastScanField(raw, %d, new int[1]);\n", f.ID))
				sb.WriteString("        return (int)HelixHelpers.readVarint(b);\n    }\n\n")
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("    public long get%s() {\n", fNameTitle))
				sb.WriteString(fmt.Sprintf("        ByteBuffer b = HelixHelpers.fastScanField(raw, %d, new int[1]);\n", f.ID))
				sb.WriteString("        return HelixHelpers.readVarint(b);\n    }\n\n")
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("    public String get%s() {\n", fNameTitle))
				sb.WriteString(fmt.Sprintf("        ByteBuffer b = HelixHelpers.fastScanField(raw, %d, new int[1]);\n", f.ID))
				sb.WriteString("        byte[] bytes = new byte[b.remaining()];\n        b.get(bytes);\n")
				sb.WriteString("        return new String(bytes, StandardCharsets.UTF_8);\n    }\n\n")
			}
		}
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func getJavaType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int"
	case ast.TypeInt64:
		return "long"
	case ast.TypeString:
		return "String"
	case ast.TypeBinary:
		return "byte[]"
	case ast.TypeBool:
		return "boolean"
	default:
		return "String"
	}
}
