package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

// GenerateJava produces Java class stubs from the AST.
func GenerateJava(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Automatically generated by Helix RPC. DO NOT EDIT.\n")
	sb.WriteString("package io.helixrpc.generated;\n\n")
	sb.WriteString("import java.util.List;\n")
	sb.WriteString("import java.util.NoSuchElementException;\n")
	sb.WriteString("import java.nio.ByteBuffer;\n")
	sb.WriteString("import java.nio.charset.StandardCharsets;\n")
	sb.WriteString("import java.io.IOException;\n")
	sb.WriteString("import java.util.concurrent.CompletableFuture;\n")
	sb.WriteString("import java.util.concurrent.Flow;\n\n")
	sb.WriteString("import com.google.protobuf.CodedInputStream;\n")
	sb.WriteString("import com.google.protobuf.CodedOutputStream;\n")
	sb.WriteString("import org.apache.thrift.TBase;\n")
	sb.WriteString("import org.apache.thrift.TException;\n")
	sb.WriteString("import org.apache.thrift.protocol.TField;\n")
	sb.WriteString("import org.apache.thrift.protocol.TProtocol;\n")
	sb.WriteString("import org.apache.thrift.protocol.TProtocolUtil;\n")
	sb.WriteString("import org.apache.thrift.protocol.TStruct;\n")
	sb.WriteString("import org.apache.thrift.protocol.TType;\n\n")

	// Global helpers class inside the package
	sb.WriteString(`class HelixHelpers {
    public static long readVarint(ByteBuffer buf) {
        long v = 0;
        int shift = 0;
        while (true) {
            byte b = buf.get();
            v |= (long)(b & 0x7F) << shift;
            if ((b & 0x80) == 0) break;
            shift += 7;
        }
        return v;
    }

    public static void writeThriftVarint(ByteBuffer buf, long v) {
        while (true) {
            if ((v & ~0x7FL) == 0) {
                buf.put((byte)v);
                break;
            }
            buf.put((byte)((v & 0x7F) | 0x80));
            v >>>= 7;
        }
    }

    public static void writeThriftI16(ByteBuffer buf, int v) {
        buf.put((byte)((v >> 8) & 0xFF));
        buf.put((byte)(v & 0xFF));
    }

    public static ByteBuffer fastScanField(ByteBuffer buf, int targetField, int[] outWireType) {
        ByteBuffer dup = buf.duplicate();
        while (dup.hasRemaining()) {
            long tag = readVarint(dup);
            int fieldNum = (int)(tag >>> 3);
            int wireType = (int)(tag & 0x7);
            if (fieldNum == targetField) {
                outWireType[0] = wireType;
                if (wireType == 2) {
                    long len = readVarint(dup);
                    int start = dup.position();
                    dup.limit(start + (int)len);
                    return dup.slice();
                } else if (wireType == 0) {
                    int start = dup.position();
                    readVarint(dup);
                    int end = dup.position();
                    ByteBuffer slice = dup.duplicate();
                    slice.position(start);
                    slice.limit(end);
                    return slice.slice();
                }
                throw new RuntimeException("unsupported wireType: " + wireType);
            }
            if (wireType == 0) {
                readVarint(dup);
            } else if (wireType == 2) {
                long len = readVarint(dup);
                dup.position(dup.position() + (int)len);
            } else {
                throw new RuntimeException("unknown wireType: " + wireType);
            }
        }
        throw new NoSuchElementException("field not found");
    }
}

`)

	for _, str := range parsed.Structs {
		// Struct definition
		if str.HasFallback {
			sb.WriteString(fmt.Sprintf("public class %s {\n", str.Name))
		} else {
			sb.WriteString(fmt.Sprintf("public class %s implements TBase<%s, %s._Fields> {\n", str.Name, str.Name, str.Name))
		}
		for _, f := range str.Fields {
			javaType := getJavaType(f.Type)
			sb.WriteString(fmt.Sprintf("    public %s %s;\n", javaType, f.Name))
		}

		if str.HasFallback {
			sb.WriteString("\n    public static ByteBuffer transpileProtobufToThriftCompact(ByteBuffer input, ByteBuffer output) {\n")
			sb.WriteString("        throw new UnsupportedOperationException(\"Transpilation is unsupported for structs with complex fields.\");\n")
			sb.WriteString("    }\n\n")

			sb.WriteString("    public static class Lazy {\n")
			sb.WriteString(fmt.Sprintf("        private final %s decoded;\n", str.Name))
			sb.WriteString(fmt.Sprintf("        public Lazy(ByteBuffer raw) {\n            this.decoded = new %s();\n        }\n\n", str.Name))
			for _, f := range str.Fields {
				fNameTitle := toCamelCase(f.Name)
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString(fmt.Sprintf("        public int get%s() { return decoded.%s; }\n", fNameTitle, f.Name))
				case ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("        public long get%s() { return decoded.%s; }\n", fNameTitle, f.Name))
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("        public String get%s() { return decoded.%s; }\n", fNameTitle, f.Name))
				}
			}
			sb.WriteString("    }\n")
		} else {
			// Static transpiler method
			sb.WriteString("\n    public static ByteBuffer transpileProtobufToThriftCompact(ByteBuffer input, ByteBuffer output) {\n")
			sb.WriteString("        ByteBuffer out = output.duplicate();\n")
			sb.WriteString("        ByteBuffer in = input.duplicate();\n")
			sb.WriteString("        int lastField = 0;\n")
			sb.WriteString("        while (in.hasRemaining()) {\n")
			sb.WriteString("            long tag = HelixHelpers.readVarint(in);\n")
			sb.WriteString("            int fieldNum = (int)(tag >>> 3);\n")
			sb.WriteString("            int wireType = (int)(tag & 0x7);\n")
			sb.WriteString("            int delta = fieldNum - lastField;\n")
			sb.WriteString("            switch (fieldNum) {\n")

			for _, f := range str.Fields {
				sb.WriteString(fmt.Sprintf("                case %d: {\n", f.ID))
				switch f.Type.Kind {
				case ast.TypeInt64:
					sb.WriteString("                    long val = HelixHelpers.readVarint(in);\n")
					sb.WriteString("                    if (delta > 0 && delta <= 15) { out.put((byte)((delta << 4) | 0x06)); }\n")
					sb.WriteString(fmt.Sprintf("                    else { out.put((byte)0x06); HelixHelpers.writeThriftI16(out, %d); }\n", f.ID))
					sb.WriteString("                    HelixHelpers.writeThriftVarint(out, (val << 1) ^ (val >> 63));\n")
					sb.WriteString("                    lastField = fieldNum;\n")
				case ast.TypeInt32:
					sb.WriteString("                    long val = HelixHelpers.readVarint(in);\n")
					sb.WriteString("                    if (delta > 0 && delta <= 15) { out.put((byte)((delta << 4) | 0x05)); }\n")
					sb.WriteString(fmt.Sprintf("                    else { out.put((byte)0x05); HelixHelpers.writeThriftI16(out, %d); }\n", f.ID))
					sb.WriteString("                    HelixHelpers.writeThriftVarint(out, (val << 1) ^ (val >> 31));\n")
					sb.WriteString("                    lastField = fieldNum;\n")
				case ast.TypeString:
					sb.WriteString("                    long len = HelixHelpers.readVarint(in);\n")
					sb.WriteString("                    if (delta > 0 && delta <= 15) { out.put((byte)((delta << 4) | 0x08)); }\n")
					sb.WriteString(fmt.Sprintf("                    else { out.put((byte)0x08); HelixHelpers.writeThriftI16(out, %d); }\n", f.ID))
					sb.WriteString("                    HelixHelpers.writeThriftVarint(out, len);\n")
					sb.WriteString("                    byte[] sBytes = new byte[(int)len];\n                    in.get(sBytes);\n                    out.put(sBytes);\n")
					sb.WriteString("                    lastField = fieldNum;\n")
				}
				sb.WriteString("                    break;\n")
				sb.WriteString("                }\n")
			}

			sb.WriteString("                default:\n")
			sb.WriteString("                    if (wireType == 0) HelixHelpers.readVarint(in);\n")
			sb.WriteString("                    else if (wireType == 2) { long len = HelixHelpers.readVarint(in);\n                    in.position(in.position() + (int)len); }\n")
			sb.WriteString("                    break;\n")
			sb.WriteString("            }\n")
			sb.WriteString("        }\n")
			sb.WriteString("        out.put((byte)0x00);\n")
			sb.WriteString("        out.flip();\n")
			sb.WriteString("        return out;\n")
			sb.WriteString("    }\n\n")

			
		if !str.HasFallback {
			sb.WriteString("\n    public enum _Fields implements org.apache.thrift.TFieldIdEnum {\n")
			for i, f := range str.Fields {
				comma := ","
				if i == len(str.Fields)-1 {
					comma = ";"
				}
				sb.WriteString(fmt.Sprintf("        %s((short)%d, \"%s\")%s\n", strings.ToUpper(f.Name), f.ID, f.Name, comma))
			}
			if len(str.Fields) == 0 {
				sb.WriteString("        ;\n")
			}
			sb.WriteString("\n        private final short _thriftId;\n")
			sb.WriteString("        private final String _fieldName;\n")
			sb.WriteString("        _Fields(short thriftId, String fieldName) {\n")
			sb.WriteString("            _thriftId = thriftId;\n")
			sb.WriteString("            _fieldName = fieldName;\n")
			sb.WriteString("        }\n")
			sb.WriteString("        public short getThriftFieldId() { return _thriftId; }\n")
			sb.WriteString("        public String getFieldName() { return _fieldName; }\n")
			sb.WriteString("    }\n\n")

			sb.WriteString(fmt.Sprintf("    public void read(TProtocol iprot) throws TException {\n"))
			sb.WriteString("        iprot.readStructBegin();\n")
			sb.WriteString("        while (true) {\n")
			sb.WriteString("            TField field = iprot.readFieldBegin();\n")
			sb.WriteString("            if (field.type == TType.STOP) { break; }\n")
			sb.WriteString("            switch (field.id) {\n")
			for _, f := range str.Fields {
				sb.WriteString(fmt.Sprintf("                case %d: // %s\n", f.ID, f.Name))
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString("                    if (field.type == TType.I32) {\n")
					sb.WriteString(fmt.Sprintf("                        this.%s = iprot.readI32();\n", f.Name))
					sb.WriteString("                    } else { TProtocolUtil.skip(iprot, field.type); }\n")
				case ast.TypeInt64:
					sb.WriteString("                    if (field.type == TType.I64) {\n")
					sb.WriteString(fmt.Sprintf("                        this.%s = iprot.readI64();\n", f.Name))
					sb.WriteString("                    } else { TProtocolUtil.skip(iprot, field.type); }\n")
				case ast.TypeString:
					sb.WriteString("                    if (field.type == TType.STRING) {\n")
					sb.WriteString(fmt.Sprintf("                        this.%s = iprot.readString();\n", f.Name))
					sb.WriteString("                    } else { TProtocolUtil.skip(iprot, field.type); }\n")
				}
				sb.WriteString("                    break;\n")
			}
			sb.WriteString("                default:\n")
			sb.WriteString("                    TProtocolUtil.skip(iprot, field.type);\n")
			sb.WriteString("            }\n")
			sb.WriteString("            iprot.readFieldEnd();\n")
			sb.WriteString("        }\n")
			sb.WriteString("        iprot.readStructEnd();\n")
			sb.WriteString("    }\n\n")

			sb.WriteString(fmt.Sprintf("    public void write(TProtocol oprot) throws TException {\n"))
			sb.WriteString(fmt.Sprintf("        oprot.writeStructBegin(new TStruct(\"%s\"));\n", str.Name))
			for _, f := range str.Fields {
				thriftType := "TType.STRING"
				if f.Type.Kind == ast.TypeInt32 { thriftType = "TType.I32" } else if f.Type.Kind == ast.TypeInt64 { thriftType = "TType.I64" }
				sb.WriteString(fmt.Sprintf("        oprot.writeFieldBegin(new TField(\"%s\", %s, (short)%d));\n", f.Name, thriftType, f.ID))
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString(fmt.Sprintf("        oprot.writeI32(this.%s);\n", f.Name))
				case ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("        oprot.writeI64(this.%s);\n", f.Name))
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("        if (this.%s != null) oprot.writeString(this.%s);\n", f.Name, f.Name))
				}
				sb.WriteString("        oprot.writeFieldEnd();\n")
			}
			sb.WriteString("        oprot.writeFieldStop();\n")
			sb.WriteString("        oprot.writeStructEnd();\n")
			sb.WriteString("    }\n\n")

			sb.WriteString(fmt.Sprintf("    public void clear() {\n"))
			for _, f := range str.Fields {
				if f.Type.Kind == ast.TypeString {
					sb.WriteString(fmt.Sprintf("        this.%s = null;\n", f.Name))
				} else {
					sb.WriteString(fmt.Sprintf("        this.%s = 0;\n", f.Name))
				}
			}
			sb.WriteString("    }\n\n")

			sb.WriteString(fmt.Sprintf("    public %s deepCopy() {\n", str.Name))
			sb.WriteString(fmt.Sprintf("        %s copy = new %s();\n", str.Name, str.Name))
			for _, f := range str.Fields {
				sb.WriteString(fmt.Sprintf("        copy.%s = this.%s;\n", f.Name, f.Name))
			}
			sb.WriteString("        return copy;\n")
			sb.WriteString("    }\n\n")

			sb.WriteString(fmt.Sprintf("    public int compareTo(%s other) {\n", str.Name))
			sb.WriteString("        return 0; // Not fully implemented\n")
			sb.WriteString("    }\n\n")

			sb.WriteString("    public _Fields fieldForId(int fieldId) { return null; }\n")
			sb.WriteString("    public boolean isSet(_Fields field) { return true; }\n")
			sb.WriteString("    public Object getFieldValue(_Fields field) { return null; }\n")
			sb.WriteString("    public void setFieldValue(_Fields field, Object value) {}\n\n")

			// Protobuf Serialization Methods
			sb.WriteString("    public void writeTo(CodedOutputStream output) throws IOException {\n")
			for _, f := range str.Fields {
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString(fmt.Sprintf("        if (this.%s != 0) output.writeInt32(%d, this.%s);\n", f.Name, f.ID, f.Name))
				case ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("        if (this.%s != 0L) output.writeInt64(%d, this.%s);\n", f.Name, f.ID, f.Name))
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("        if (this.%s != null && !this.%s.isEmpty()) output.writeString(%d, this.%s);\n", f.Name, f.Name, f.ID, f.Name))
				}
			}
			sb.WriteString("    }\n\n")

			sb.WriteString("    public int getSerializedSize() {\n")
			sb.WriteString("        int size = 0;\n")
			for _, f := range str.Fields {
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString(fmt.Sprintf("        if (this.%s != 0) size += CodedOutputStream.computeInt32Size(%d, this.%s);\n", f.Name, f.ID, f.Name))
				case ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("        if (this.%s != 0L) size += CodedOutputStream.computeInt64Size(%d, this.%s);\n", f.Name, f.ID, f.Name))
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("        if (this.%s != null && !this.%s.isEmpty()) size += CodedOutputStream.computeStringSize(%d, this.%s);\n", f.Name, f.Name, f.ID, f.Name))
				}
			}
			sb.WriteString("        return size;\n")
			sb.WriteString("    }\n\n")

			sb.WriteString(fmt.Sprintf("    public static %s parseFrom(byte[] data) throws IOException {\n", str.Name))
			sb.WriteString(fmt.Sprintf("        return parseFrom(CodedInputStream.newInstance(data));\n"))
			sb.WriteString("    }\n\n")

			sb.WriteString(fmt.Sprintf("    public static %s parseFrom(CodedInputStream input) throws IOException {\n", str.Name))
			sb.WriteString(fmt.Sprintf("        %s msg = new %s();\n", str.Name, str.Name))
			sb.WriteString("        while (true) {\n")
			sb.WriteString("            int tag = input.readTag();\n")
			sb.WriteString("            if (tag == 0) break;\n")
			sb.WriteString("            switch (tag) {\n")
			for _, f := range str.Fields {
				wire := 0
				if f.Type.Kind == ast.TypeString { wire = 2 }
				tagId := (f.ID << 3) | int32(wire)
				sb.WriteString(fmt.Sprintf("                case %d:\n", tagId))
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString(fmt.Sprintf("                    msg.%s = input.readInt32();\n", f.Name))
				case ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("                    msg.%s = input.readInt64();\n", f.Name))
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("                    msg.%s = input.readString();\n", f.Name))
				}
				sb.WriteString("                    break;\n")
			}
			sb.WriteString("                default:\n")
			sb.WriteString("                    input.skipField(tag);\n")
			sb.WriteString("            }\n")
			sb.WriteString("        }\n")
			sb.WriteString("        return msg;\n")
			sb.WriteString("    }\n\n")
		}

			// Nested Lazy class inside the public struct class
			sb.WriteString("    public static class Lazy {\n")
			sb.WriteString("        private final ByteBuffer raw;\n")
			sb.WriteString("        public Lazy(ByteBuffer raw) { this.raw = raw; }\n\n")

			for _, f := range str.Fields {
				fNameTitle := toCamelCase(f.Name)
				switch f.Type.Kind {
				case ast.TypeInt32:
					sb.WriteString(fmt.Sprintf("        public int get%s() {\n", fNameTitle))
					sb.WriteString(fmt.Sprintf("            ByteBuffer b = HelixHelpers.fastScanField(raw, %d, new int[1]);\n", f.ID))
					sb.WriteString("            return (int)HelixHelpers.readVarint(b);\n        }\n\n")
				case ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("        public long get%s() {\n", fNameTitle))
					sb.WriteString(fmt.Sprintf("            ByteBuffer b = HelixHelpers.fastScanField(raw, %d, new int[1]);\n", f.ID))
					sb.WriteString("            return HelixHelpers.readVarint(b);\n        }\n\n")
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("        public String get%s() {\n", fNameTitle))
					sb.WriteString(fmt.Sprintf("            ByteBuffer b = HelixHelpers.fastScanField(raw, %d, new int[1]);\n", f.ID))
					sb.WriteString("            byte[] bytes = new byte[b.remaining()];\n            b.get(bytes);\n")
					sb.WriteString("            return new String(bytes, StandardCharsets.UTF_8);\n        }\n\n")
				}
			}
			sb.WriteString("    }\n")
		}
		sb.WriteString("}\n\n")
	}

	
	// Generate Java Interfaces for Services
	for _, srv := range parsed.Services {
		sb.WriteString(fmt.Sprintf("public interface %s {\n", srv.Name))
		for _, m := range srv.Methods {
			if m.ServerStreaming || m.ClientStreaming {
				sb.WriteString(fmt.Sprintf("    Flow.Publisher<%s> %s(Flow.Publisher<%s> request);\n", m.OutputType, toCamelCaseLC(m.Name), m.InputType))
			} else {
				sb.WriteString(fmt.Sprintf("    CompletableFuture<%s> %s(%s request);\n", m.OutputType, toCamelCaseLC(m.Name), m.InputType))
			}
		}
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func getJavaType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int"
	case ast.TypeInt64:
		return "long"
	case ast.TypeString:
		return "String"
	case ast.TypeBinary:
		return "byte[]"
	case ast.TypeBool:
		return "boolean"
	default:
		return "String"
	}
}


func toCamelCaseLC(s string) string {
	cc := toCamelCase(s)
	if len(cc) > 0 {
		return strings.ToLower(cc[:1]) + cc[1:]
	}
	return cc
}
