package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

// GenerateJava produces Java class stubs from the AST.
func GenerateJava(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Automatically generated by Helix RPC. DO NOT EDIT.\n")
	sb.WriteString("package io.helixrpc.generated;\n\n")
	sb.WriteString("import java.util.List;\n")
	sb.WriteString("import java.nio.ByteBuffer;\n\n")

	for _, str := range parsed.Structs {
		sb.WriteString(fmt.Sprintf("public class %s {\n", str.Name))
		for _, f := range str.Fields {
			javaType := getJavaType(f.Type)
			sb.WriteString(fmt.Sprintf("    public %s %s;\n", javaType, f.Name))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func getJavaType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int"
	case ast.TypeInt64:
		return "long"
	case ast.TypeString:
		return "String"
	case ast.TypeBinary:
		return "byte[]"
	case ast.TypeBool:
		return "boolean"
	default:
		return "String"
	}
}
