package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

func GenerateNode(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Automatically generated by Helix RPC. DO NOT EDIT.\n\n")

	// Generate interfaces and classes for each struct
	for _, str := range parsed.Structs {
		// Calculate fixed offsets mirroring Go/Rust/Python exactly
		offsets := make([]int, len(str.Fields))
		currentOffset := 4 // starts after vtable_offset (4 bytes)
		for idx, f := range str.Fields {
			size := 4
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeBool:
				size = 4
			case ast.TypeInt64, ast.TypeDouble:
				size = 8
			case ast.TypeString, ast.TypeBinary:
				size = 4
			}
			rem := currentOffset % size
			if rem != 0 {
				currentOffset += size - rem
			}
			offsets[idx] = currentOffset
			currentOffset += size
		}
		tableSize := currentOffset
		vtableSize := 4 + 2*len(str.Fields)

		sb.WriteString(fmt.Sprintf("export class %s {\n", str.Name))
		for _, f := range str.Fields {
			jsType := mapJSType(f.Type)
			defaultVal := mapJSDefaultValue(f.Type)
			sb.WriteString(fmt.Sprintf("    public %s: %s = %s;\n", toJSFieldName(f.Name), jsType, defaultVal))
		}
		sb.WriteString("\n")

		// Constructor
		sb.WriteString("    constructor(init?: Partial<" + str.Name + ">) {\n")
		sb.WriteString("        if (init) {\n")
		sb.WriteString("            Object.assign(this, init);\n")
		sb.WriteString("        }\n")
		sb.WriteString("    }\n\n")

		// FlatBuffers Marshaller
		sb.WriteString("    public marshalFlatBuffers(): Uint8Array {\n")
		sb.WriteString("        const encoder = new TextEncoder();\n")
		sb.WriteString("        let dynamicSize = 0;\n")

		// Calculate string sizes
		for _, f := range str.Fields {
			if f.Type.Kind == ast.TypeString {
				fName := toJSFieldName(f.Name)
				sb.WriteString(fmt.Sprintf("        const enc_%s = this.%s ? encoder.encode(this.%s) : new Uint8Array(0);\n", fName, fName, fName))
				sb.WriteString(fmt.Sprintf("        if (this.%s) {\n", fName))
				sb.WriteString(fmt.Sprintf("            dynamicSize += 4 + enc_%s.length;\n", fName))
				sb.WriteString("        }\n")
			}
		}

		sb.WriteString(fmt.Sprintf("        const tableSize = %d;\n", tableSize))
		sb.WriteString(fmt.Sprintf("        const vtableSize = %d;\n", vtableSize))
		sb.WriteString("        const totalSize = 4 + tableSize + dynamicSize + vtableSize;\n")
		sb.WriteString("        const buf = new Uint8Array(totalSize);\n")
		sb.WriteString("        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);\n")
		sb.WriteString("        \n")
		sb.WriteString("        // Root offset pointing to root table (always 4)\n")
		sb.WriteString("        view.setUint32(0, 4, true);\n")
		sb.WriteString("        \n")
		sb.WriteString("        // Write vtable offset at buf[4:8]\n")
		sb.WriteString("        const vtableStart = 4 + tableSize + dynamicSize;\n")
		sb.WriteString("        const vtableOffset = vtableStart - 4;\n")
		sb.WriteString("        view.setInt32(4, vtableOffset, true);\n")
		sb.WriteString("        \n")

		sb.WriteString(fmt.Sprintf("        let currentStringOffset = 4 + %d;\n", tableSize))
		// Write field values using computed static offsets (relative to buffer start, so 4 + offset)
		for idx, f := range str.Fields {
			fName := toJSFieldName(f.Name)
			bufOffset := 4 + offsets[idx]
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("        view.setInt32(%d, this.%s || 0, true);\n", bufOffset, fName))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("        view.setBigInt64(%d, BigInt(this.%s || 0), true);\n", bufOffset, fName))
			case ast.TypeBool:
				sb.WriteString(fmt.Sprintf("        view.setUint8(%d, this.%s ? 1 : 0);\n", bufOffset, fName))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("        if (this.%s) {\n", fName))
				sb.WriteString(fmt.Sprintf("            const relOffset = currentStringOffset - %d;\n", bufOffset))
				sb.WriteString(fmt.Sprintf("            view.setUint32(%d, relOffset, true);\n", bufOffset))
				sb.WriteString(fmt.Sprintf("            view.setUint32(currentStringOffset, enc_%s.length, true);\n", fName))
				sb.WriteString(fmt.Sprintf("            buf.set(enc_%s, currentStringOffset + 4);\n", fName))
				sb.WriteString(fmt.Sprintf("            currentStringOffset += 4 + enc_%s.length;\n", fName))
				sb.WriteString("        }\n")
			}
		}

		// Write vtable header
		sb.WriteString("        // Write vtable\n")
		sb.WriteString("        view.setUint16(vtableStart, vtableSize, true);\n")
		sb.WriteString("        view.setUint16(vtableStart + 2, tableSize, true);\n")
		vOffset := 4
		for idx, f := range str.Fields {
			off := offsets[idx]
			sb.WriteString(fmt.Sprintf("        if (this.%s !== undefined) {\n", toJSFieldName(f.Name)))
			sb.WriteString(fmt.Sprintf("            view.setUint16(vtableStart + %d, %d, true);\n", vOffset, off))
			sb.WriteString("        }\n")
			vOffset += 2
		}
		sb.WriteString("        return buf;\n")
		sb.WriteString("    }\n\n")

		// FlatBuffers Unmarshaller
		sb.WriteString(fmt.Sprintf("    public static unmarshalFlatBuffers(buf: Uint8Array): %s {\n", str.Name))
		sb.WriteString("        const decoder = new TextDecoder();\n")
		sb.WriteString("        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);\n")
		sb.WriteString("        if (buf.length < 8) {\n")
		sb.WriteString("            throw new Error('flatbuffers: buffer too small');\n")
		sb.WriteString("        }\n")
		sb.WriteString("        const rootOffset = view.getUint32(0, true);\n")
		sb.WriteString("        if (rootOffset + 4 > buf.length) {\n")
		sb.WriteString("            throw new Error('flatbuffers: invalid root offset');\n")
		sb.WriteString("        }\n")
		sb.WriteString("        const vtableOffset = view.getInt32(rootOffset, true);\n")
		sb.WriteString("        const vtableStart = rootOffset + vtableOffset;\n")
		sb.WriteString("        if (vtableStart < 0 || vtableStart + 4 > buf.length) {\n")
		sb.WriteString("            throw new Error('flatbuffers: invalid vtable offset');\n")
		sb.WriteString("        }\n")
		sb.WriteString("        const vtableSize = view.getUint16(vtableStart, true);\n")
		sb.WriteString(fmt.Sprintf("        const result = new %s();\n", str.Name))
		sb.WriteString("        \n")

		// Read fields from vtable
		for idx, f := range str.Fields {
			fName := toJSFieldName(f.Name)
			voff := 4 + 2*idx
			sb.WriteString(fmt.Sprintf("        if (%d + 2 <= vtableSize) {\n", voff))
			sb.WriteString(fmt.Sprintf("            const foffset = view.getUint16(vtableStart + %d, true);\n", voff))
			sb.WriteString("            if (foffset > 0) {\n")
			sb.WriteString("                const absOffset = rootOffset + foffset;\n")
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString("                if (absOffset + 4 <= buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                    result.%s = view.getInt32(absOffset, true);\n", fName))
				sb.WriteString("                }\n")
			case ast.TypeInt64:
				sb.WriteString("                if (absOffset + 8 <= buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                    result.%s = Number(view.getBigInt64(absOffset, true));\n", fName))
				sb.WriteString("                }\n")
			case ast.TypeBool:
				sb.WriteString("                if (absOffset < buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                    result.%s = view.getUint8(absOffset) !== 0;\n", fName))
				sb.WriteString("                }\n")
			case ast.TypeString:
				sb.WriteString("                if (absOffset + 4 <= buf.length) {\n")
				sb.WriteString("                    const relOffset = view.getUint32(absOffset, true);\n")
				sb.WriteString("                    const strStart = absOffset + relOffset;\n")
				sb.WriteString("                    if (strStart + 4 <= buf.length) {\n")
				sb.WriteString("                        const strLen = view.getUint32(strStart, true);\n")
				sb.WriteString("                        if (strStart + 4 + strLen <= buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                            result.%s = decoder.decode(buf.subarray(strStart + 4, strStart + 4 + strLen));\n", fName))
				sb.WriteString("                        }\n")
				sb.WriteString("                    }\n")
				sb.WriteString("                }\n")
			}
			sb.WriteString("            }\n")
			sb.WriteString("        }\n")
		}
		sb.WriteString("        return result;\n")
		sb.WriteString("    }\n")

		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func mapJSType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32, ast.TypeInt64:
		return "number"
	case ast.TypeBool:
		return "boolean"
	case ast.TypeString:
		return "string"
	default:
		return "any"
	}
}

func mapJSDefaultValue(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32, ast.TypeInt64:
		return "0"
	case ast.TypeBool:
		return "false"
	case ast.TypeString:
		return `""`
	default:
		return "null"
	}
}

func toJSFieldName(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.Title(parts[i])
	}
	return strings.Join(parts, "")
}
