package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

func GenerateNode(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Automatically generated by Helix RPC. DO NOT EDIT.\n\n")

	// ---------------------------------------------------------------------------
	// Global cross-protocol helper functions (injected once)
	// ---------------------------------------------------------------------------
	sb.WriteString(`function readVarint(buf: Uint8Array, idx: number): [bigint, number] {
    let v = BigInt(0);
    let shift = BigInt(0);
    while (true) {
        if (idx >= buf.length) throw new Error('unexpected EOF reading varint');
        const b = buf[idx++];
        v |= BigInt(b & 0x7f) << shift;
        if ((b & 0x80) === 0) break;
        shift += BigInt(7);
    }
    return [v, idx];
}

function writeThriftVarint(out: number[], v: bigint): void {
    while (true) {
        if ((v & ~BigInt(0x7F)) === BigInt(0)) { out.push(Number(v)); break; }
        out.push(Number(v & BigInt(0x7F)) | 0x80);
        v >>= BigInt(7);
    }
}

function writeThriftI16(out: number[], v: number): void {
    out.push((v >> 8) & 0xFF);
    out.push(v & 0xFF);
}

function fastScanField(buf: Uint8Array, targetFieldNum: number): [Uint8Array, number] {
    let idx = 0;
    while (idx < buf.length) {
        const [tag, ni] = readVarint(buf, idx); idx = ni;
        const fieldNum = Number(tag >> BigInt(3));
        const wireType = Number(tag & BigInt(7));
        if (fieldNum === targetFieldNum) {
            if (wireType === 2) {
                const [len, ni2] = readVarint(buf, idx);
                const end = ni2 + Number(len);
                if (end > buf.length) throw new Error('unexpected EOF');
                return [buf.subarray(ni2, end), wireType];
            } else if (wireType === 0) {
                const start = idx;
                const [, ni2] = readVarint(buf, idx);
                return [buf.subarray(start, ni2), wireType];
            }
            throw new Error(` + "`" + `unsupported wireType ${wireType} for fastScan` + "`" + `);
        }
        if (wireType === 0) { const [, ni2] = readVarint(buf, idx); idx = ni2; }
        else if (wireType === 2) { const [len, ni2] = readVarint(buf, idx); idx = ni2 + Number(len); }
        else throw new Error(` + "`" + `unhandled wireType ${wireType} in fastScan skip` + "`" + `);
    }
    throw new Error(` + "`" + `field ${targetFieldNum} not found` + "`" + `);
}

`)

	// Generate interfaces and classes for each struct
	for _, str := range parsed.Structs {
		// Calculate fixed offsets mirroring Go/Rust/Python exactly
		offsets := make([]int, len(str.Fields))
		currentOffset := 4 // starts after vtable_offset (4 bytes)
		for idx, f := range str.Fields {
			size := 4
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeBool:
				size = 4
			case ast.TypeInt64, ast.TypeDouble:
				size = 8
			case ast.TypeString, ast.TypeBinary:
				size = 4
			}
			rem := currentOffset % size
			if rem != 0 {
				currentOffset += size - rem
			}
			offsets[idx] = currentOffset
			currentOffset += size
		}
		tableSize := currentOffset
		vtableSize := 4 + 2*len(str.Fields)

		sb.WriteString(fmt.Sprintf("export class %s {\n", str.Name))
		for _, f := range str.Fields {
			jsType := mapJSType(f.Type)
			defaultVal := mapJSDefaultValue(f.Type)
			sb.WriteString(fmt.Sprintf("    public %s: %s = %s;\n", toJSFieldName(f.Name), jsType, defaultVal))
		}
		sb.WriteString("\n")

		// Constructor
		sb.WriteString("    constructor(init?: Partial<" + str.Name + ">) {\n")
		sb.WriteString("        if (init) {\n")
		sb.WriteString("            Object.assign(this, init);\n")
		sb.WriteString("        }\n")
		sb.WriteString("    }\n\n")

		// FlatBuffers Marshaller
		sb.WriteString("    public marshalFlatBuffers(): Uint8Array {\n")
		sb.WriteString("        const encoder = new TextEncoder();\n")
		sb.WriteString("        let dynamicSize = 0;\n")

		// Calculate string sizes
		for _, f := range str.Fields {
			if f.Type.Kind == ast.TypeString {
				fName := toJSFieldName(f.Name)
				sb.WriteString(fmt.Sprintf("        const enc_%s = this.%s ? encoder.encode(this.%s) : new Uint8Array(0);\n", fName, fName, fName))
				sb.WriteString(fmt.Sprintf("        if (this.%s) {\n", fName))
				sb.WriteString(fmt.Sprintf("            dynamicSize += 4 + enc_%s.length;\n", fName))
				sb.WriteString("        }\n")
			}
		}

		sb.WriteString(fmt.Sprintf("        const tableSize = %d;\n", tableSize))
		sb.WriteString(fmt.Sprintf("        const vtableSize = %d;\n", vtableSize))
		sb.WriteString("        const totalSize = 4 + tableSize + dynamicSize + vtableSize;\n")
		sb.WriteString("        const buf = new Uint8Array(totalSize);\n")
		sb.WriteString("        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);\n")
		sb.WriteString("        \n")
		sb.WriteString("        // Root offset pointing to root table (always 4)\n")
		sb.WriteString("        view.setUint32(0, 4, true);\n")
		sb.WriteString("        \n")
		sb.WriteString("        // Write vtable offset at buf[4:8]\n")
		sb.WriteString("        const vtableStart = 4 + tableSize + dynamicSize;\n")
		sb.WriteString("        const vtableOffset = vtableStart - 4;\n")
		sb.WriteString("        view.setInt32(4, vtableOffset, true);\n")
		sb.WriteString("        \n")

		sb.WriteString(fmt.Sprintf("        let currentStringOffset = 4 + %d;\n", tableSize))
		// Write field values using computed static offsets (relative to buffer start, so 4 + offset)
		for idx, f := range str.Fields {
			fName := toJSFieldName(f.Name)
			bufOffset := 4 + offsets[idx]
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("        view.setInt32(%d, this.%s || 0, true);\n", bufOffset, fName))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("        view.setBigInt64(%d, BigInt(this.%s || 0), true);\n", bufOffset, fName))
			case ast.TypeBool:
				sb.WriteString(fmt.Sprintf("        view.setUint8(%d, this.%s ? 1 : 0);\n", bufOffset, fName))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("        if (this.%s) {\n", fName))
				sb.WriteString(fmt.Sprintf("            const relOffset = currentStringOffset - %d;\n", bufOffset))
				sb.WriteString(fmt.Sprintf("            view.setUint32(%d, relOffset, true);\n", bufOffset))
				sb.WriteString(fmt.Sprintf("            view.setUint32(currentStringOffset, enc_%s.length, true);\n", fName))
				sb.WriteString(fmt.Sprintf("            buf.set(enc_%s, currentStringOffset + 4);\n", fName))
				sb.WriteString(fmt.Sprintf("            currentStringOffset += 4 + enc_%s.length;\n", fName))
				sb.WriteString("        }\n")
			}
		}

		// Write vtable header
		sb.WriteString("        // Write vtable\n")
		sb.WriteString("        view.setUint16(vtableStart, vtableSize, true);\n")
		sb.WriteString("        view.setUint16(vtableStart + 2, tableSize, true);\n")
		vOffset := 4
		for idx, f := range str.Fields {
			off := offsets[idx]
			sb.WriteString(fmt.Sprintf("        if (this.%s !== undefined) {\n", toJSFieldName(f.Name)))
			sb.WriteString(fmt.Sprintf("            view.setUint16(vtableStart + %d, %d, true);\n", vOffset, off))
			sb.WriteString("        }\n")
			vOffset += 2
		}
		sb.WriteString("        return buf;\n")
		sb.WriteString("    }\n\n")

		// FlatBuffers Unmarshaller
		sb.WriteString(fmt.Sprintf("    public static unmarshalFlatBuffers(buf: Uint8Array): %s {\n", str.Name))
		sb.WriteString("        const decoder = new TextDecoder();\n")
		sb.WriteString("        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);\n")
		sb.WriteString("        if (buf.length < 8) {\n")
		sb.WriteString("            throw new Error('flatbuffers: buffer too small');\n")
		sb.WriteString("        }\n")
		sb.WriteString("        const rootOffset = view.getUint32(0, true);\n")
		sb.WriteString("        if (rootOffset + 4 > buf.length) {\n")
		sb.WriteString("            throw new Error('flatbuffers: invalid root offset');\n")
		sb.WriteString("        }\n")
		sb.WriteString("        const vtableOffset = view.getInt32(rootOffset, true);\n")
		sb.WriteString("        const vtableStart = rootOffset + vtableOffset;\n")
		sb.WriteString("        if (vtableStart < 0 || vtableStart + 4 > buf.length) {\n")
		sb.WriteString("            throw new Error('flatbuffers: invalid vtable offset');\n")
		sb.WriteString("        }\n")
		sb.WriteString("        const vtableSize = view.getUint16(vtableStart, true);\n")
		sb.WriteString(fmt.Sprintf("        const result = new %s();\n", str.Name))
		sb.WriteString("        \n")

		// Read fields from vtable
		for idx, f := range str.Fields {
			fName := toJSFieldName(f.Name)
			voff := 4 + 2*idx
			sb.WriteString(fmt.Sprintf("        if (%d + 2 <= vtableSize) {\n", voff))
			sb.WriteString(fmt.Sprintf("            const foffset = view.getUint16(vtableStart + %d, true);\n", voff))
			sb.WriteString("            if (foffset > 0) {\n")
			sb.WriteString("                const absOffset = rootOffset + foffset;\n")
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString("                if (absOffset + 4 <= buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                    result.%s = view.getInt32(absOffset, true);\n", fName))
				sb.WriteString("                }\n")
			case ast.TypeInt64:
				sb.WriteString("                if (absOffset + 8 <= buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                    result.%s = Number(view.getBigInt64(absOffset, true));\n", fName))
				sb.WriteString("                }\n")
			case ast.TypeBool:
				sb.WriteString("                if (absOffset < buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                    result.%s = view.getUint8(absOffset) !== 0;\n", fName))
				sb.WriteString("                }\n")
			case ast.TypeString:
				sb.WriteString("                if (absOffset + 4 <= buf.length) {\n")
				sb.WriteString("                    const relOffset = view.getUint32(absOffset, true);\n")
				sb.WriteString("                    const strStart = absOffset + relOffset;\n")
				sb.WriteString("                    if (strStart + 4 <= buf.length) {\n")
				sb.WriteString("                        const strLen = view.getUint32(strStart, true);\n")
				sb.WriteString("                        if (strStart + 4 + strLen <= buf.length) {\n")
				sb.WriteString(fmt.Sprintf("                            result.%s = decoder.decode(buf.subarray(strStart + 4, strStart + 4 + strLen));\n", fName))
				sb.WriteString("                        }\n")
				sb.WriteString("                    }\n")
				sb.WriteString("                }\n")
			}
			sb.WriteString("            }\n")
			sb.WriteString("        }\n")
		}
		sb.WriteString("        return result;\n")
		sb.WriteString("    }\n")

		if str.HasFallback {
			sb.WriteString("\n    public static transpileProtobufToThriftCompact(input: Uint8Array): Uint8Array {\n")
			sb.WriteString("        throw new Error(\"Transpilation is unsupported for structs with complex fields.\");\n")
			sb.WriteString("    }\n")
			sb.WriteString("}\n\n")

			sb.WriteString(fmt.Sprintf("export class Lazy%s {\n", str.Name))
			sb.WriteString(fmt.Sprintf("    private readonly decoded: %s;\n", str.Name))
			sb.WriteString(fmt.Sprintf("    constructor(raw: Uint8Array) { this.decoded = %s.unmarshalProtobuf(raw); }\n", str.Name))
			for _, f := range str.Fields {
				fName := toJSFieldName(f.Name)
				getterName := "get" + strings.Title(fName)
				sb.WriteString(fmt.Sprintf("    %s(): any { return this.decoded.%s; }\n", getterName, fName))
			}
			sb.WriteString("}\n\n")
		} else {
			// -----------------------------------------------------------------------
			// transpileProtobufToThriftCompact static method
			// -----------------------------------------------------------------------
			sb.WriteString("\n    public static transpileProtobufToThriftCompact(input: Uint8Array): Uint8Array {\n")
			sb.WriteString("        const out: number[] = [];\n")
			sb.WriteString("        let idx = 0;\n")
			sb.WriteString("        let lastField = 0;\n")
			sb.WriteString("        while (idx < input.length) {\n")
			sb.WriteString("            const [tag, ni] = readVarint(input, idx); idx = ni;\n")
			sb.WriteString("            const fieldNum = Number(tag >> BigInt(3));\n")
			sb.WriteString("            const wireType = Number(tag & BigInt(7));\n")
			sb.WriteString("            switch (fieldNum) {\n")

			for _, f := range str.Fields {
				fieldID := int(f.ID)
				sb.WriteString(fmt.Sprintf("                case %d: {\n", fieldID))
				switch f.Type.Kind {
				case ast.TypeInt64:
					sb.WriteString("                    const [rawVal, ni2] = readVarint(input, idx); idx = ni2;\n")
					sb.WriteString(fmt.Sprintf("                    const delta%d = %d - lastField;\n", fieldID, fieldID))
					sb.WriteString(fmt.Sprintf("                    if (delta%d > 0 && delta%d <= 15) {\n", fieldID, fieldID))
					sb.WriteString(fmt.Sprintf("                        out.push((delta%d << 4) | 0x06);\n", fieldID))
					sb.WriteString("                    } else {\n")
					sb.WriteString("                        out.push(0x06);\n")
					sb.WriteString(fmt.Sprintf("                        writeThriftI16(out, %d);\n", fieldID))
					sb.WriteString("                    }\n")
					// zigzag64
					sb.WriteString("                    const zz = (rawVal << BigInt(1)) ^ (rawVal >> BigInt(63));\n")
					sb.WriteString("                    writeThriftVarint(out, zz);\n")
					sb.WriteString(fmt.Sprintf("                    lastField = %d;\n", fieldID))
				case ast.TypeInt32:
					sb.WriteString("                    const [rawVal, ni2] = readVarint(input, idx); idx = ni2;\n")
					sb.WriteString(fmt.Sprintf("                    const delta%d = %d - lastField;\n", fieldID, fieldID))
					sb.WriteString(fmt.Sprintf("                    if (delta%d > 0 && delta%d <= 15) {\n", fieldID, fieldID))
					sb.WriteString(fmt.Sprintf("                        out.push((delta%d << 4) | 0x05);\n", fieldID))
					sb.WriteString("                    } else {\n")
					sb.WriteString("                        out.push(0x05);\n")
					sb.WriteString(fmt.Sprintf("                        writeThriftI16(out, %d);\n", fieldID))
					sb.WriteString("                    }\n")
					// zigzag32
					sb.WriteString("                    const zz = (rawVal << 1) ^ (rawVal >> 31);\n")
					sb.WriteString("                    writeThriftVarint(out, BigInt(zz));\n")
					sb.WriteString(fmt.Sprintf("                    lastField = %d;\n", fieldID))
				case ast.TypeString:
					sb.WriteString("                    const [len, ni2] = readVarint(input, idx); idx = ni2;\n")
					sb.WriteString("                    const strVal = input.subarray(idx, idx + Number(len)); idx += Number(len);\n")
					sb.WriteString(fmt.Sprintf("                    const delta%d = %d - lastField;\n", fieldID, fieldID))
					sb.WriteString(fmt.Sprintf("                    if (delta%d > 0 && delta%d <= 15) {\n", fieldID, fieldID))
					sb.WriteString(fmt.Sprintf("                        out.push((delta%d << 4) | 0x08);\n", fieldID))
					sb.WriteString("                    } else {\n")
					sb.WriteString("                        out.push(0x08);\n")
					sb.WriteString(fmt.Sprintf("                        writeThriftI16(out, %d);\n", fieldID))
					sb.WriteString("                    }\n")
					sb.WriteString("                    writeThriftVarint(out, len);\n")
					sb.WriteString("                    const strBytes = Array.from(strVal);\n")
					sb.WriteString("                    for (let i = 0; i < strBytes.length; i++) out.push(strBytes[i]);\n")
					sb.WriteString(fmt.Sprintf("                    lastField = %d;\n", fieldID))
				default:
					// Skip unsupported wire types
					sb.WriteString("                    if (wireType === 0) { const [, ni2] = readVarint(input, idx); idx = ni2; }\n")
					sb.WriteString("                    else if (wireType === 2) { const [l, ni2] = readVarint(input, idx); idx = ni2 + Number(l); }\n")
				}
				sb.WriteString("                    break;\n")
				sb.WriteString("                }\n")
			}

			sb.WriteString("                default:\n")
			sb.WriteString("                    if (wireType === 0) { const [, ni2] = readVarint(input, idx); idx = ni2; }\n")
			sb.WriteString("                    else if (wireType === 2) { const [l, ni2] = readVarint(input, idx); idx = ni2 + Number(l); }\n")
			sb.WriteString("                    break;\n")
			sb.WriteString("            }\n")
			sb.WriteString("        }\n")
			sb.WriteString("        out.push(0); // Thrift STOP\n")
			sb.WriteString("        return new Uint8Array(out);\n")
			sb.WriteString("    }\n")

			// Close the main class
			sb.WriteString("}\n\n")

			// -----------------------------------------------------------------------
			// LazyXxx class — zero-copy protobuf field access
			// -----------------------------------------------------------------------
			sb.WriteString(fmt.Sprintf("export class Lazy%s {\n", str.Name))
			sb.WriteString("    private readonly raw: Uint8Array;\n")
			sb.WriteString("    constructor(raw: Uint8Array) { this.raw = raw; }\n")

			for _, f := range str.Fields {
				fName := toJSFieldName(f.Name)
				getterName := "get" + strings.Title(fName)
				fieldID := int(f.ID)
				switch f.Type.Kind {
				case ast.TypeInt32, ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("    %s(): number { const [b,] = fastScanField(this.raw, %d); const [v,] = readVarint(b, 0); return Number(v); }\n", getterName, fieldID))
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("    %s(): string { const [b,] = fastScanField(this.raw, %d); return new TextDecoder().decode(b); }\n", getterName, fieldID))
				case ast.TypeBool:
					sb.WriteString(fmt.Sprintf("    %s(): boolean { const [b,] = fastScanField(this.raw, %d); const [v,] = readVarint(b, 0); return Number(v) !== 0; }\n", getterName, fieldID))
				default:
					sb.WriteString(fmt.Sprintf("    %s(): Uint8Array { const [b,] = fastScanField(this.raw, %d); return b; }\n", getterName, fieldID))
				}
			}

			sb.WriteString("}\n\n")
		}
	}

	return sb.String(), nil
}

func mapJSType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32, ast.TypeInt64:
		return "number"
	case ast.TypeBool:
		return "boolean"
	case ast.TypeString:
		return "string"
	default:
		return "any"
	}
}

func mapJSDefaultValue(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32, ast.TypeInt64:
		return "0"
	case ast.TypeBool:
		return "false"
	case ast.TypeString:
		return `""`
	default:
		return "null"
	}
}

func toJSFieldName(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.Title(parts[i])
	}
	return strings.Join(parts, "")
}
