package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

func mapPythonType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32, ast.TypeInt64:
		return "int"
	case ast.TypeString:
		return "str"
	case ast.TypeBinary:
		return "bytes"
	case ast.TypeBool:
		return "bool"
	case ast.TypeDouble:
		return "float"
	case ast.TypeStruct, ast.TypeEnum:
		return fmt.Sprintf("'%s'", t.Name) // Using string reference for forward declarations
	case ast.TypeList:
		return fmt.Sprintf("List[%s]", mapPythonType(*t.ValueType))
	case ast.TypeMap:
		return fmt.Sprintf("Dict[%s, %s]", mapPythonType(*t.KeyType), mapPythonType(*t.ValueType))
	default:
		return "Any"
	}
}

func GeneratePython(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("# Code generated by helix-gen. DO NOT EDIT.\n")
	sb.WriteString("from dataclasses import dataclass, field\n")
	sb.WriteString("from typing import List, Dict, Any, Optional, AsyncIterator\n")
	sb.WriteString("from abc import ABC, abstractmethod\n")
	sb.WriteString("import struct as _struct\n\n")

	// Protobuf binary helpers — emitted once per generated file
	sb.WriteString("def _read_varint(buf: memoryview, idx: int):\n")
	sb.WriteString("    v, shift = 0, 0\n")
	sb.WriteString("    while True:\n")
	sb.WriteString("        if idx >= len(buf): raise EOFError('unexpected EOF reading varint')\n")
	sb.WriteString("        b = buf[idx]; idx += 1\n")
	sb.WriteString("        v |= (b & 0x7f) << shift\n")
	sb.WriteString("        if (b & 0x80) == 0: break\n")
	sb.WriteString("        shift += 7\n")
	sb.WriteString("    return v, idx\n\n")

	sb.WriteString("def _write_thrift_varint(out: bytearray, v: int) -> None:\n")
	sb.WriteString("    while True:\n")
	sb.WriteString("        if (v & ~0x7F) == 0: out.append(v); break\n")
	sb.WriteString("        out.append((v & 0x7F) | 0x80); v >>= 7\n\n")

	sb.WriteString("def _write_thrift_i16(out: bytearray, v: int) -> None:\n")
	sb.WriteString("    out.append((v >> 8) & 0xFF); out.append(v & 0xFF)\n\n")

	sb.WriteString("def _fast_scan_field(raw: memoryview, target_field: int):\n")
	sb.WriteString("    idx = 0\n")
	sb.WriteString("    while idx < len(raw):\n")
	sb.WriteString("        tag, idx = _read_varint(raw, idx)\n")
	sb.WriteString("        field_num = tag >> 3\n")
	sb.WriteString("        wire_type = tag & 0x7\n")
	sb.WriteString("        if field_num == target_field:\n")
	sb.WriteString("            if wire_type == 2:\n")
	sb.WriteString("                length, idx = _read_varint(raw, idx)\n")
	sb.WriteString("                return raw[idx:idx+length], wire_type\n")
	sb.WriteString("            elif wire_type == 0:\n")
	sb.WriteString("                start = idx\n")
	sb.WriteString("                _, idx = _read_varint(raw, idx)\n")
	sb.WriteString("                return raw[start:idx], wire_type\n")
	sb.WriteString("            raise ValueError(f'unsupported wire_type {wire_type}')\n")
	sb.WriteString("        if wire_type == 0: _, idx = _read_varint(raw, idx)\n")
	sb.WriteString("        elif wire_type == 2:\n")
	sb.WriteString("            length, idx = _read_varint(raw, idx)\n")
	sb.WriteString("            idx += length\n")
	sb.WriteString("        else: raise ValueError(f'unknown wire_type {wire_type}')\n")
	sb.WriteString("    raise KeyError(f'field {target_field} not found')\n\n")

	// Generate Enums
	for _, e := range parsed.Enums {
		sb.WriteString(fmt.Sprintf("class %s:\n", e.Name))
		for k, v := range e.Values {
			sb.WriteString(fmt.Sprintf("    %s = %d\n", k, v))
		}
		sb.WriteString("\n")
	}

	// Generate Structs
	for _, str := range parsed.Structs {
		sb.WriteString("@dataclass\n")
		sb.WriteString(fmt.Sprintf("class %s:\n", str.Name))
		if len(str.Fields) == 0 {
			sb.WriteString("    pass\n")
		}
		for _, f := range str.Fields {
			pyType := mapPythonType(f.Type)
			if f.Optional {
				pyType = fmt.Sprintf("Optional[%s]", pyType)
			}
			sb.WriteString(fmt.Sprintf("    %s: %s\n", f.Name, pyType))
		}
		sb.WriteString("\n")

		// FlatBuffers offsets calculation
		offsets := make([]int, len(str.Fields))
		currentOffset := 4 // starts after vtable_offset (4 bytes)
		for idx, f := range str.Fields {
			size := 4
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeBool:
				size = 4
			case ast.TypeInt64, ast.TypeDouble:
				size = 8
			case ast.TypeString, ast.TypeBinary:
				size = 4
			}
			rem := currentOffset % size
			if rem != 0 {
				currentOffset += size - rem
			}
			offsets[idx] = currentOffset
			currentOffset += size
		}
		tableSize := currentOffset
		vtableSize := 4 + 2*len(str.Fields)

		sb.WriteString("    def marshal_flatbuffers(self) -> bytes:\n")
		sb.WriteString("        import struct\n")
		sb.WriteString("        dynamic_size = 0\n")
		for _, f := range str.Fields {
			if f.Type.Kind == ast.TypeString || f.Type.Kind == ast.TypeBinary {
				sb.WriteString(fmt.Sprintf("        str_%s = self.%s.encode('utf-8') if self.%s else b''\n", f.Name, f.Name, f.Name))
				sb.WriteString(fmt.Sprintf("        if str_%s:\n", f.Name))
				sb.WriteString(fmt.Sprintf("            dynamic_size += 4 + len(str_%s)\n", f.Name))
			}
		}
		sb.WriteString(fmt.Sprintf("        table_size = %d\n", tableSize))
		sb.WriteString(fmt.Sprintf("        vtable_size = %d\n", vtableSize))
		sb.WriteString("        total_size = 4 + table_size + dynamic_size + vtable_size\n")
		sb.WriteString("        buf = bytearray(total_size)\n")
		sb.WriteString("        struct.pack_into('<I', buf, 0, 4) # root offset\n")
		sb.WriteString("        vtable_start = 4 + table_size + dynamic_size\n")
		sb.WriteString("        vtable_offset = vtable_start - 4\n")
		sb.WriteString("        struct.pack_into('<i', buf, 4, vtable_offset)\n")
		sb.WriteString("        current_string_offset = 4 + table_size\n")

		for idx, f := range str.Fields {
			off := offsets[idx]
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("        struct.pack_into('<i', buf, 4 + %d, self.%s or 0)\n", off, f.Name))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("        struct.pack_into('<q', buf, 4 + %d, self.%s or 0)\n", off, f.Name))
			case ast.TypeBool:
				sb.WriteString(fmt.Sprintf("        struct.pack_into('<?', buf, 4 + %d, bool(self.%s))\n", off, f.Name))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("        if str_%s:\n", f.Name))
				sb.WriteString(fmt.Sprintf("            rel_offset = current_string_offset - (4 + %d)\n", off))
				sb.WriteString(fmt.Sprintf("            struct.pack_into('<I', buf, 4 + %d, rel_offset)\n", off))
				sb.WriteString(fmt.Sprintf("            struct.pack_into('<I', buf, current_string_offset, len(str_%s))\n", f.Name))
				sb.WriteString(fmt.Sprintf("            buf[current_string_offset+4 : current_string_offset+4+len(str_%s)] = str_%s\n", f.Name, f.Name))
				sb.WriteString(fmt.Sprintf("            current_string_offset += 4 + len(str_%s)\n", f.Name))
			}
		}

		// Write vtable
		sb.WriteString("        struct.pack_into('<HH', buf, vtable_start, vtable_size, table_size)\n")
		for idx := range str.Fields {
			off := offsets[idx]
			sb.WriteString(fmt.Sprintf("        struct.pack_into('<H', buf, vtable_start + 4 + %d, %d)\n", 2*idx, off))
		}
		sb.WriteString("        return bytes(buf)\n\n")

		// unmarshal_flatbuffers
		sb.WriteString("    @classmethod\n")
		sb.WriteString(fmt.Sprintf("    def unmarshal_flatbuffers(cls, buf: bytes) -> '%s':\n", str.Name))
		sb.WriteString("        import struct\n")
		sb.WriteString("        if len(buf) < 8:\n            raise ValueError('flatbuffers: buffer too small')\n")
		sb.WriteString("        root_offset = struct.unpack_from('<I', buf, 0)[0]\n")
		sb.WriteString("        if root_offset + 4 > len(buf):\n            raise ValueError('flatbuffers: invalid root offset')\n")
		sb.WriteString("        vtable_offset = struct.unpack_from('<i', buf, root_offset)[0]\n")
		sb.WriteString("        vtable_start = root_offset + vtable_offset\n")
		sb.WriteString("        if vtable_start < 0 or vtable_start + 4 > len(buf):\n            raise ValueError('flatbuffers: invalid vtable offset')\n")
		sb.WriteString("        vtable_size = struct.unpack_from('<H', buf, vtable_start)[0]\n")

		for _, f := range str.Fields {
			defaultValue := "0"
			if f.Type.Kind == ast.TypeString {
				defaultValue = "\"\""
			} else if f.Type.Kind == ast.TypeBool {
				defaultValue = "False"
			}
			sb.WriteString(fmt.Sprintf("        val_%s = %s\n", f.Name, defaultValue))
		}

		for idx, f := range str.Fields {
			voff := 4 + 2*idx
			sb.WriteString(fmt.Sprintf("        if %d + 2 <= vtable_size:\n", voff))
			sb.WriteString(fmt.Sprintf("            foffset = struct.unpack_from('<H', buf, vtable_start + %d)[0]\n", voff))
			sb.WriteString("            if foffset > 0:\n")
			sb.WriteString("                abs_offset = root_offset + foffset\n")
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString("                if abs_offset + 4 <= len(buf):\n")
				sb.WriteString(fmt.Sprintf("                    val_%s = struct.unpack_from('<i', buf, abs_offset)[0]\n", f.Name))
			case ast.TypeInt64:
				sb.WriteString("                if abs_offset + 8 <= len(buf):\n")
				sb.WriteString(fmt.Sprintf("                    val_%s = struct.unpack_from('<q', buf, abs_offset)[0]\n", f.Name))
			case ast.TypeBool:
				sb.WriteString("                if abs_offset < len(buf):\n")
				sb.WriteString(fmt.Sprintf("                    val_%s = struct.unpack_from('<?', buf, abs_offset)[0]\n", f.Name))
			case ast.TypeString:
				sb.WriteString("                if abs_offset + 4 <= len(buf):\n")
				sb.WriteString("                    rel_offset = struct.unpack_from('<I', buf, abs_offset)[0]\n")
				sb.WriteString("                    str_start = abs_offset + rel_offset\n")
				sb.WriteString("                    if str_start + 4 <= len(buf):\n")
				sb.WriteString("                        str_len = struct.unpack_from('<I', buf, str_start)[0]\n")
				sb.WriteString("                        if str_start + 4 + str_len <= len(buf):\n")
				sb.WriteString(fmt.Sprintf("                            val_%s = buf[str_start+4 : str_start+4+str_len].decode('utf-8')\n", f.Name))
			}
		}

		sb.WriteString(fmt.Sprintf("        return cls(\n"))
		for _, f := range str.Fields {
			sb.WriteString(fmt.Sprintf("            %s=val_%s,\n", f.Name, f.Name))
		}
		sb.WriteString("        )\n\n")

		// from_proto: zero-copy protobuf decode via memoryview
		sb.WriteString("    @classmethod\n")
		sb.WriteString(fmt.Sprintf("    def from_proto(cls, buf: bytes) -> '%s':\n", str.Name))
		sb.WriteString("        raw = memoryview(buf)\n")
		for _, f := range str.Fields {
			defaultVal := "0"
			if f.Type.Kind == ast.TypeString {
				defaultVal = "\"\""
			} else if f.Type.Kind == ast.TypeBool {
				defaultVal = "False"
			} else if f.Type.Kind == ast.TypeDouble {
				defaultVal = "0.0"
			} else if f.Type.Kind == ast.TypeBinary {
				defaultVal = "b\"\""
			}
			sb.WriteString(fmt.Sprintf("        val_%s = %s\n", f.Name, defaultVal))
		}
		sb.WriteString("        idx = 0\n")
		sb.WriteString("        while idx < len(raw):\n")
		sb.WriteString("            tag, idx = _read_varint(raw, idx)\n")
		sb.WriteString("            field_num = tag >> 3\n")
		sb.WriteString("            wire_type = tag & 0x7\n")
		for fieldIdx, f := range str.Fields {
			protoFieldNum := fieldIdx + 1
			if fieldIdx == 0 {
				sb.WriteString(fmt.Sprintf("            if field_num == %d:\n", protoFieldNum))
			} else {
				sb.WriteString(fmt.Sprintf("            elif field_num == %d:\n", protoFieldNum))
			}
			switch f.Type.Kind {
			case ast.TypeInt32, ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("                val_%s, idx = _read_varint(raw, idx)\n", f.Name))
			case ast.TypeBool:
				sb.WriteString(fmt.Sprintf("                _v, idx = _read_varint(raw, idx); val_%s = bool(_v)\n", f.Name))
			case ast.TypeDouble:
				sb.WriteString(fmt.Sprintf("                val_%s = _struct.unpack_from('<d', bytes(raw[idx:idx+8]))[0]; idx += 8\n", f.Name))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("                _len, idx = _read_varint(raw, idx); val_%s = bytes(raw[idx:idx+_len]).decode('utf-8'); idx += _len\n", f.Name))
			case ast.TypeBinary:
				sb.WriteString(fmt.Sprintf("                _len, idx = _read_varint(raw, idx); val_%s = bytes(raw[idx:idx+_len]); idx += _len\n", f.Name))
			default:
				sb.WriteString("                _, idx = _read_varint(raw, idx)\n")
			}
		}
		sb.WriteString("            else:\n")
		sb.WriteString("                if wire_type == 0: _, idx = _read_varint(raw, idx)\n")
		sb.WriteString("                elif wire_type == 2:\n")
		sb.WriteString("                    _l, idx = _read_varint(raw, idx); idx += _l\n")
		sb.WriteString("                elif wire_type == 5: idx += 4\n")
			sb.WriteString("                elif wire_type == 1: idx += 8\n")
		sb.WriteString(fmt.Sprintf("        return cls(\n"))
		for _, f := range str.Fields {
			sb.WriteString(fmt.Sprintf("            %s=val_%s,\n", f.Name, f.Name))
		}
		sb.WriteString("        )\n\n")

		if str.HasFallback {
			sb.WriteString(fmt.Sprintf("class Lazy%s:\n", str.Name))
			sb.WriteString("    __slots__ = ('_decoded',)\n")
			sb.WriteString("    def __init__(self, raw: bytes) -> None:\n")
			sb.WriteString(fmt.Sprintf("        self._decoded = %s.from_proto(raw)\n", str.Name))
			for _, f := range str.Fields {
				sb.WriteString(fmt.Sprintf("    def get_%s(self):\n", f.Name))
				sb.WriteString(fmt.Sprintf("        return self._decoded.%s\n", f.Name))
			}
			sb.WriteString("\n")
			sb.WriteString("    @classmethod\n")
			sb.WriteString("    def transpile_protobuf_to_thrift_compact(cls, data: bytes) -> bytes:\n")
			sb.WriteString("        raise NotImplementedError(\"Transpilation is unsupported for structs with complex fields.\")\n\n")
		} else {
			// Lazy class — field access triggers _fast_scan_field on demand
			sb.WriteString(fmt.Sprintf("class Lazy%s:\n", str.Name))
			sb.WriteString("    __slots__ = ('_raw',)\n")
			sb.WriteString("    def __init__(self, raw: bytes) -> None:\n")
			sb.WriteString("        self._raw = memoryview(raw)\n")
			for fieldIdx, f := range str.Fields {
				protoFieldNum := fieldIdx + 1
				switch f.Type.Kind {
				case ast.TypeInt32, ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("    def get_%s(self) -> int:\n", f.Name))
					sb.WriteString(fmt.Sprintf("        b, _ = _fast_scan_field(self._raw, %d)\n", protoFieldNum))
					sb.WriteString("        v, _ = _read_varint(b, 0)\n")
					sb.WriteString("        return v\n")
				case ast.TypeString:
					sb.WriteString(fmt.Sprintf("    def get_%s(self) -> str:\n", f.Name))
					sb.WriteString(fmt.Sprintf("        b, _ = _fast_scan_field(self._raw, %d)\n", protoFieldNum))
					sb.WriteString("        return bytes(b).decode('utf-8')\n")
				case ast.TypeBinary:
					sb.WriteString(fmt.Sprintf("    def get_%s(self) -> bytes:\n", f.Name))
					sb.WriteString(fmt.Sprintf("        b, _ = _fast_scan_field(self._raw, %d)\n", protoFieldNum))
					sb.WriteString("        return bytes(b)\n")
				case ast.TypeBool:
					sb.WriteString(fmt.Sprintf("    def get_%s(self) -> bool:\n", f.Name))
					sb.WriteString(fmt.Sprintf("        b, _ = _fast_scan_field(self._raw, %d)\n", protoFieldNum))
					sb.WriteString("        v, _ = _read_varint(b, 0)\n")
					sb.WriteString("        return v != 0\n")
				default:
					sb.WriteString(fmt.Sprintf("    def get_%s(self):\n", f.Name))
					sb.WriteString(fmt.Sprintf("        b, _ = _fast_scan_field(self._raw, %d)\n", protoFieldNum))
					sb.WriteString("        return bytes(b)\n")
				}
			}
			sb.WriteString("\n")

			// transpile_protobuf_to_thrift_compact classmethod
			sb.WriteString(fmt.Sprintf("    @classmethod\n"))
			sb.WriteString("    def transpile_protobuf_to_thrift_compact(cls, data: bytes) -> bytes:\n")
			sb.WriteString("        raw = memoryview(data)\n")
			sb.WriteString("        out = bytearray()\n")
			for _, f := range str.Fields {
				defaultVal := "0"
				if f.Type.Kind == ast.TypeString || f.Type.Kind == ast.TypeBinary {
					defaultVal = "None"
				} else if f.Type.Kind == ast.TypeBool {
					defaultVal = "False"
				} else if f.Type.Kind == ast.TypeDouble {
					defaultVal = "0.0"
				}
				sb.WriteString(fmt.Sprintf("        _f_%s = %s\n", f.Name, defaultVal))
			}
			sb.WriteString("        idx = 0\n")
			sb.WriteString("        while idx < len(raw):\n")
			sb.WriteString("            tag, idx = _read_varint(raw, idx)\n")
			sb.WriteString("            field_num = tag >> 3\n")
			sb.WriteString("            wire_type = tag & 0x7\n")
			for fieldIdx, f := range str.Fields {
				protoFieldNum := fieldIdx + 1
				if fieldIdx == 0 {
					sb.WriteString(fmt.Sprintf("            if field_num == %d:\n", protoFieldNum))
				} else {
					sb.WriteString(fmt.Sprintf("            elif field_num == %d:\n", protoFieldNum))
				}
				switch f.Type.Kind {
				case ast.TypeInt32, ast.TypeInt64:
					sb.WriteString("                v, idx = _read_varint(raw, idx)\n")
					sb.WriteString(fmt.Sprintf("                _f_%s = v\n", f.Name))
				case ast.TypeString, ast.TypeBinary:
					sb.WriteString("                _l, idx = _read_varint(raw, idx)\n")
					sb.WriteString(fmt.Sprintf("                _f_%s = bytes(raw[idx:idx+_l])\n", f.Name))
					sb.WriteString("                idx += _l\n")
					if f.Type.Kind == ast.TypeString {
						sb.WriteString(fmt.Sprintf("                _f_%s = _f_%s.decode('utf-8')\n", f.Name, f.Name))
					}
				case ast.TypeBool:
					sb.WriteString("                v, idx = _read_varint(raw, idx)\n")
					sb.WriteString(fmt.Sprintf("                _f_%s = (v != 0)\n", f.Name))
				case ast.TypeDouble:
					sb.WriteString(fmt.Sprintf("                _f_%s = _struct.unpack('<d', raw[idx:idx+8])[0]\n", f.Name))
					sb.WriteString("                idx += 8\n")
				}
			}
			sb.WriteString("            else:\n")
			sb.WriteString("                if wire_type == 0: _, idx = _read_varint(raw, idx)\n")
			sb.WriteString("                elif wire_type == 2:\n")
			sb.WriteString("                    _l, idx = _read_varint(raw, idx); idx += _l\n")
			sb.WriteString("                elif wire_type == 5: idx += 4\n")
			sb.WriteString("                elif wire_type == 1: idx += 8\n")

			sb.WriteString("        prev_field = 0\n")
			for fieldIdx, f := range str.Fields {
				thriftFieldNum := fieldIdx + 1
				switch f.Type.Kind {
				case ast.TypeInt32, ast.TypeInt64:
					sb.WriteString(fmt.Sprintf("        _delta = %d - prev_field\n", thriftFieldNum))
					ttype := 5
					if f.Type.Kind == ast.TypeInt64 {
						ttype = 6
					}
					sb.WriteString(fmt.Sprintf("        if 0 < _delta <= 15: out.append((_delta << 4) | %d)\n", ttype))
					sb.WriteString(fmt.Sprintf("        else: out.append(%d); _write_thrift_i16(out, %d)\n", ttype, thriftFieldNum))
					if f.Type.Kind == ast.TypeInt32 {
						sb.WriteString(fmt.Sprintf("        _zz = (_f_%s << 1) ^ (_f_%s >> 31) if _f_%s < 0 else _f_%s << 1\n", f.Name, f.Name, f.Name, f.Name))
					} else {
						sb.WriteString(fmt.Sprintf("        _zz = (_f_%s << 1) ^ (_f_%s >> 63) if _f_%s < 0 else _f_%s << 1\n", f.Name, f.Name, f.Name, f.Name))
					}
					sb.WriteString("        _write_thrift_varint(out, _zz)\n")
					sb.WriteString(fmt.Sprintf("        prev_field = %d\n", thriftFieldNum))
				case ast.TypeString, ast.TypeBinary:
					// Thrift compact type=8 (binary/string)
					sb.WriteString(fmt.Sprintf("        if _f_%s is not None:\n", f.Name))
					sb.WriteString(fmt.Sprintf("            _delta = %d - prev_field\n", thriftFieldNum))
					sb.WriteString("            if 0 < _delta <= 15: out.append((_delta << 4) | 8)\n")
					sb.WriteString(fmt.Sprintf("            else: out.append(8); _write_thrift_i16(out, %d)\n", thriftFieldNum))
					if f.Type.Kind == ast.TypeString {
						sb.WriteString(fmt.Sprintf("            _enc = _f_%s.encode('utf-8')\n", f.Name))
					} else {
						sb.WriteString(fmt.Sprintf("            _enc = _f_%s\n", f.Name))
					}
					sb.WriteString("            _write_thrift_varint(out, len(_enc))\n")
					sb.WriteString("            out.extend(_enc)\n")
					sb.WriteString(fmt.Sprintf("            prev_field = %d\n", thriftFieldNum))
				case ast.TypeBool:
					// Thrift compact type=1 (true) or 2 (false)
					sb.WriteString(fmt.Sprintf("        _delta = %d - prev_field\n", thriftFieldNum))
					sb.WriteString(fmt.Sprintf("        _ttype = 1 if _f_%s else 2\n", f.Name))
					sb.WriteString("        if 0 < _delta <= 15: out.append((_delta << 4) | _ttype)\n")
					sb.WriteString(fmt.Sprintf("        else: out.append(_ttype); _write_thrift_i16(out, %d)\n", thriftFieldNum))
					sb.WriteString(fmt.Sprintf("        prev_field = %d\n", thriftFieldNum))
				case ast.TypeDouble:
					// Thrift compact type=7 (double)
					sb.WriteString(fmt.Sprintf("        _delta = %d - prev_field\n", thriftFieldNum))
					sb.WriteString("        if 0 < _delta <= 15: out.append((_delta << 4) | 7)\n")
					sb.WriteString(fmt.Sprintf("        else: out.append(7); _write_thrift_i16(out, %d)\n", thriftFieldNum))
					sb.WriteString(fmt.Sprintf("        out.extend(_struct.pack('<d', _f_%s))\n", f.Name))
					sb.WriteString(fmt.Sprintf("        prev_field = %d\n", thriftFieldNum))
				}
			}
			sb.WriteString("        out.append(0x00)  # Thrift STOP byte\n")
			sb.WriteString("        return bytes(out)\n\n")
		}
	}

	// Generate Service ABCs
	for _, srv := range parsed.Services {
		sb.WriteString(fmt.Sprintf("class %sBase(ABC):\n", srv.Name))
		if len(srv.Methods) == 0 {
			sb.WriteString("    pass\n")
		}
		for _, m := range srv.Methods {
			sb.WriteString("    @abstractmethod\n")
			retType := m.OutputType
			if m.ServerStreaming {
				retType = fmt.Sprintf("AsyncIterator['%s']", m.OutputType)
			} else {
				retType = fmt.Sprintf("'%s'", m.OutputType)
			}

			inputType := fmt.Sprintf("'%s'", m.InputType)
			if m.ClientStreaming {
				inputType = fmt.Sprintf("AsyncIterator['%s']", m.InputType)
			}

			sb.WriteString(fmt.Sprintf("    async def %s(self, request: %s) -> %s:\n", m.Name, inputType, retType))
			sb.WriteString("        pass\n\n")
		}
	}

	return sb.String(), nil
}
