package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

func mapPythonType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32, ast.TypeInt64:
		return "int"
	case ast.TypeString:
		return "str"
	case ast.TypeBinary:
		return "bytes"
	case ast.TypeBool:
		return "bool"
	case ast.TypeDouble:
		return "float"
	case ast.TypeStruct, ast.TypeEnum:
		return fmt.Sprintf("'%s'", t.Name) // Using string reference for forward declarations
	case ast.TypeList:
		return fmt.Sprintf("List[%s]", mapPythonType(*t.ValueType))
	case ast.TypeMap:
		return fmt.Sprintf("Dict[%s, %s]", mapPythonType(*t.KeyType), mapPythonType(*t.ValueType))
	default:
		return "Any"
	}
}

func GeneratePython(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("# Code generated by helix-gen. DO NOT EDIT.\n")
	sb.WriteString("from dataclasses import dataclass, field\n")
	sb.WriteString("from typing import List, Dict, Any, Optional, AsyncIterator\n")
	sb.WriteString("from abc import ABC, abstractmethod\n\n")

	// Generate Enums
	for _, e := range parsed.Enums {
		sb.WriteString(fmt.Sprintf("class %s:\n", e.Name))
		for k, v := range e.Values {
			sb.WriteString(fmt.Sprintf("    %s = %d\n", k, v))
		}
		sb.WriteString("\n")
	}

	// Generate Structs
	for _, str := range parsed.Structs {
		sb.WriteString("@dataclass\n")
		sb.WriteString(fmt.Sprintf("class %s:\n", str.Name))
		if len(str.Fields) == 0 {
			sb.WriteString("    pass\n")
		}
		for _, f := range str.Fields {
			pyType := mapPythonType(f.Type)
			if f.Optional {
				pyType = fmt.Sprintf("Optional[%s]", pyType)
			}
			sb.WriteString(fmt.Sprintf("    %s: %s\n", f.Name, pyType))
		}
		sb.WriteString("\n")
	}

	// Generate Service ABCs
	for _, srv := range parsed.Services {
		sb.WriteString(fmt.Sprintf("class %sBase(ABC):\n", srv.Name))
		if len(srv.Methods) == 0 {
			sb.WriteString("    pass\n")
		}
		for _, m := range srv.Methods {
			sb.WriteString("    @abstractmethod\n")
			retType := m.OutputType
			if m.ServerStreaming {
				retType = fmt.Sprintf("AsyncIterator['%s']", m.OutputType)
			} else {
				retType = fmt.Sprintf("'%s'", m.OutputType)
			}
			
			inputType := fmt.Sprintf("'%s'", m.InputType)
			if m.ClientStreaming {
				inputType = fmt.Sprintf("AsyncIterator['%s']", m.InputType)
			}
			
			sb.WriteString(fmt.Sprintf("    async def %s(self, request: %s) -> %s:\n", m.Name, inputType, retType))
			sb.WriteString("        pass\n\n")
		}
	}

	return sb.String(), nil
}
