package codegen

import (
	"fmt"
	"strings"

	"github.com/helix-rpc/helix/compiler/ast"
)

func GenerateRust(parsed *ast.AST) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by helix-gen. DO NOT EDIT.\n\n")
	sb.WriteString("use std::collections::HashMap;\n")
	sb.WriteString("use thrift::protocol::{TInputProtocol, TOutputProtocol, TSerializable, TFieldIdentifier, TStructIdentifier, TType};\n")
	sb.WriteString("use thrift::Error as ThriftError;\n\n")

	// Generate Structs
	for _, str := range parsed.Structs {
		sb.WriteString("#[derive(Clone, PartialEq, ::prost::Message)]\n")
		sb.WriteString(fmt.Sprintf("pub struct %s {\n", str.Name))
		for _, f := range str.Fields {
			rustType := mapRustType(f.Type)
			prostType := mapProstType(f.Type)
			sb.WriteString(fmt.Sprintf("    #[prost(%s, tag = \"%d\")]\n", prostType, f.ID))
			sb.WriteString(fmt.Sprintf("    pub %s: %s,\n", f.Name, rustType))
		}
		sb.WriteString("}\n\n")

		// Implement TSerializable for Thrift
		sb.WriteString(fmt.Sprintf("impl TSerializable for %s {\n", str.Name))
		
		// read_from_in_protocol
		sb.WriteString("    fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Self> {\n")
		sb.WriteString("        i_prot.read_struct_begin()?;\n")
		for _, f := range str.Fields {
			sb.WriteString(fmt.Sprintf("        let mut var_%s: Option<%s> = None;\n", f.Name, mapRustType(f.Type)))
		}
		sb.WriteString("        loop {\n")
		sb.WriteString("            let field_ident = i_prot.read_field_begin()?;\n")
		sb.WriteString("            if field_ident.field_type == TType::Stop {\n")
		sb.WriteString("                break;\n")
		sb.WriteString("            }\n")
		sb.WriteString("            let field_id = field_ident.id.unwrap_or(0);\n")
		sb.WriteString("            match field_id {\n")
		for _, f := range str.Fields {
			sb.WriteString(fmt.Sprintf("                %d => {\n", f.ID))
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("                    let val = i_prot.read_i32()?;\n"))
				sb.WriteString(fmt.Sprintf("                    var_%s = Some(val);\n", f.Name))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("                    let val = i_prot.read_i64()?;\n"))
				sb.WriteString(fmt.Sprintf("                    var_%s = Some(val);\n", f.Name))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("                    let val = i_prot.read_string()?;\n"))
				sb.WriteString(fmt.Sprintf("                    var_%s = Some(val);\n", f.Name))
			}
			sb.WriteString("                }\n")
		}
		sb.WriteString("                _ => {\n")
		sb.WriteString("                    i_prot.skip(field_ident.field_type)?;\n")
		sb.WriteString("                }\n")
		sb.WriteString("            }\n")
		sb.WriteString("            i_prot.read_field_end()?;\n")
		sb.WriteString("        }\n")
		sb.WriteString("        i_prot.read_struct_end()?;\n")
		sb.WriteString("        Ok(Self {\n")
		for _, f := range str.Fields {
			sb.WriteString(fmt.Sprintf("            %s: var_%s.unwrap_or_default(),\n", f.Name, f.Name))
		}
		sb.WriteString("        })\n")
		sb.WriteString("    }\n\n")

		// write_to_out_protocol
		sb.WriteString("    fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {\n")
		sb.WriteString(fmt.Sprintf("        o_prot.write_struct_begin(&TStructIdentifier::new(\"%s\"))?;\n", str.Name))
		for _, f := range str.Fields {
			thriftType := mapThriftTypeConstRust(f.Type)
			sb.WriteString(fmt.Sprintf("        o_prot.write_field_begin(&TFieldIdentifier::new(\"%s\", TType::%s, Some(%d)))?;\n", f.Name, thriftType, f.ID))
			switch f.Type.Kind {
			case ast.TypeInt32:
				sb.WriteString(fmt.Sprintf("        o_prot.write_i32(self.%s)?;\n", f.Name))
			case ast.TypeInt64:
				sb.WriteString(fmt.Sprintf("        o_prot.write_i64(self.%s)?;\n", f.Name))
			case ast.TypeString:
				sb.WriteString(fmt.Sprintf("        o_prot.write_string(&self.%s)?;\n", f.Name))
			}
			sb.WriteString("        o_prot.write_field_end()?;\n")
		}
		sb.WriteString("        o_prot.write_field_stop()?;\n")
		sb.WriteString("        o_prot.write_struct_end()?;\n")
		sb.WriteString("        Ok(())\n")
		sb.WriteString("    }\n")
		sb.WriteString("}\n\n")
	}

	// Generate Service Traits
	for _, srv := range parsed.Services {
		sb.WriteString("#[async_trait::async_trait]\n")
		sb.WriteString(fmt.Sprintf("pub trait %s: Send + Sync + 'static {\n", srv.Name))
		for _, m := range srv.Methods {
			sb.WriteString(fmt.Sprintf("    async fn %s(&self, req: %s) -> Result<%s, ThriftError>;\n",
				toSnakeCase(m.Name), m.InputType, m.OutputType))
		}
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func mapRustType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "i32"
	case ast.TypeInt64:
		return "i64"
	case ast.TypeString:
		return "String"
	case ast.TypeBinary:
		return "Vec<u8>"
	case ast.TypeBool:
		return "bool"
	case ast.TypeDouble:
		return "f64"
	case ast.TypeStruct:
		return t.Name
	default:
		return "String"
	}
}

func mapProstType(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "int32"
	case ast.TypeInt64:
		return "int64"
	case ast.TypeString:
		return "string"
	case ast.TypeBinary:
		return "bytes"
	case ast.TypeBool:
		return "bool"
	default:
		return "string"
	}
}

func mapThriftTypeConstRust(t ast.TypeNode) string {
	switch t.Kind {
	case ast.TypeInt32:
		return "I32"
	case ast.TypeInt64:
		return "I64"
	case ast.TypeString:
		return "String"
	case ast.TypeBinary:
		return "String"
	case ast.TypeBool:
		return "Bool"
	case ast.TypeStruct:
		return "Struct"
	default:
		return "Stop"
	}
}

func toSnakeCase(s string) string {
	var result []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result = append(result, '_')
		}
		result = append(result, r)
	}
	return strings.ToLower(string(result))
}
