// Automatically generated by Helix RPC. DO NOT EDIT.
function readVarint(buf, idx) {
    let v = BigInt(0);
    let shift = BigInt(0);
    while (true) {
        if (idx >= buf.length)
            throw new Error('unexpected EOF reading varint');
        const b = buf[idx++];
        v |= BigInt(b & 0x7f) << shift;
        if ((b & 0x80) === 0)
            break;
        shift += BigInt(7);
    }
    return [v, idx];
}
function writeThriftVarint(out, v) {
    while (true) {
        if ((v & ~BigInt(0x7F)) === BigInt(0)) {
            out.push(Number(v));
            break;
        }
        out.push(Number(v & BigInt(0x7F)) | 0x80);
        v >>= BigInt(7);
    }
}
function writeThriftI16(out, v) {
    out.push((v >> 8) & 0xFF);
    out.push(v & 0xFF);
}
function fastScanField(buf, targetFieldNum) {
    let idx = 0;
    while (idx < buf.length) {
        const [tag, ni] = readVarint(buf, idx);
        idx = ni;
        const fieldNum = Number(tag >> BigInt(3));
        const wireType = Number(tag & BigInt(7));
        if (fieldNum === targetFieldNum) {
            if (wireType === 2) {
                const [len, ni2] = readVarint(buf, idx);
                const end = ni2 + Number(len);
                if (end > buf.length)
                    throw new Error('unexpected EOF');
                return [buf.subarray(ni2, end), wireType];
            }
            else if (wireType === 0) {
                const start = idx;
                const [, ni2] = readVarint(buf, idx);
                return [buf.subarray(start, ni2), wireType];
            }
            throw new Error(`unsupported wireType ${wireType} for fastScan`);
        }
        if (wireType === 0) {
            const [, ni2] = readVarint(buf, idx);
            idx = ni2;
        }
        else if (wireType === 2) {
            const [len, ni2] = readVarint(buf, idx);
            idx = ni2 + Number(len);
        }
        else
            throw new Error(`unhandled wireType ${wireType} in fastScan skip`);
    }
    throw new Error(`field ${targetFieldNum} not found`);
}
export class ComplexRequest {
    id = 0;
    metadata = null;
    constructor(init) {
        if (init) {
            Object.assign(this, init);
        }
    }
    marshalFlatBuffers() {
        const encoder = new TextEncoder();
        let dynamicSize = 0;
        const tableSize = 12;
        const vtableSize = 8;
        const totalSize = 4 + tableSize + dynamicSize + vtableSize;
        const buf = new Uint8Array(totalSize);
        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        // Root offset pointing to root table (always 4)
        view.setUint32(0, 4, true);
        // Write vtable offset at buf[4:8]
        const vtableStart = 4 + tableSize + dynamicSize;
        const vtableOffset = vtableStart - 4;
        view.setInt32(4, vtableOffset, true);
        let currentStringOffset = 4 + 12;
        view.setInt32(8, this.id || 0, true);
        // Write vtable
        view.setUint16(vtableStart, vtableSize, true);
        view.setUint16(vtableStart + 2, tableSize, true);
        if (this.id !== undefined) {
            view.setUint16(vtableStart + 4, 4, true);
        }
        if (this.metadata !== undefined) {
            view.setUint16(vtableStart + 6, 8, true);
        }
        return buf;
    }
    static unmarshalFlatBuffers(buf) {
        const decoder = new TextDecoder();
        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        if (buf.length < 8) {
            throw new Error('flatbuffers: buffer too small');
        }
        const rootOffset = view.getUint32(0, true);
        if (rootOffset + 4 > buf.length) {
            throw new Error('flatbuffers: invalid root offset');
        }
        const vtableOffset = view.getInt32(rootOffset, true);
        const vtableStart = rootOffset + vtableOffset;
        if (vtableStart < 0 || vtableStart + 4 > buf.length) {
            throw new Error('flatbuffers: invalid vtable offset');
        }
        const vtableSize = view.getUint16(vtableStart, true);
        const result = new ComplexRequest();
        if (4 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 4, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
                if (absOffset + 4 <= buf.length) {
                    result.id = view.getInt32(absOffset, true);
                }
            }
        }
        if (6 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 6, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
            }
        }
        return result;
    }
    static unmarshalProtobuf(buf) {
        const res = new ComplexRequest();
        let idx = 0;
        while (idx < buf.length) {
            const [tag, ni] = readVarint(buf, idx);
            idx = ni;
            const fieldNum = Number(tag >> 3n);
            const wireType = Number(tag & 7n);
            switch (fieldNum) {
                case 1:
                    const [v_1, ni_1] = readVarint(buf, idx);
                    idx = ni_1;
                    res.id = Number(v_1);
                    break;
                case 4:
                    break;
                default:
                    if (wireType === 0) {
                        const [, ni2] = readVarint(buf, idx);
                        idx = ni2;
                    }
                    else if (wireType === 2) {
                        const [len, ni2] = readVarint(buf, idx);
                        idx = ni2 + Number(len);
                    }
                    break;
            }
        }
        return res;
    }
    static transpileProtobufToThriftCompact(input) {
        throw new Error("Transpilation is unsupported for structs with complex fields.");
    }
}
export class LazyComplexRequest {
    decoded;
    constructor(raw) { this.decoded = ComplexRequest.unmarshalProtobuf(raw); }
    getId() { return this.decoded.id; }
    getMetadata() { return this.decoded.metadata; }
}
