// Automatically generated by Helix RPC. DO NOT EDIT.
function readVarint(buf, idx) {
    let v = BigInt(0);
    let shift = BigInt(0);
    while (true) {
        if (idx >= buf.length)
            throw new Error('unexpected EOF reading varint');
        const b = buf[idx++];
        v |= BigInt(b & 0x7f) << shift;
        if ((b & 0x80) === 0)
            break;
        shift += BigInt(7);
    }
    return [v, idx];
}
function writeThriftVarint(out, v) {
    while (true) {
        if ((v & ~BigInt(0x7F)) === BigInt(0)) {
            out.push(Number(v));
            break;
        }
        out.push(Number(v & BigInt(0x7F)) | 0x80);
        v >>= BigInt(7);
    }
}
function writeThriftI16(out, v) {
    out.push((v >> 8) & 0xFF);
    out.push(v & 0xFF);
}
function fastScanField(buf, targetFieldNum) {
    let idx = 0;
    while (idx < buf.length) {
        const [tag, ni] = readVarint(buf, idx);
        idx = ni;
        const fieldNum = Number(tag >> BigInt(3));
        const wireType = Number(tag & BigInt(7));
        if (fieldNum === targetFieldNum) {
            if (wireType === 2) {
                const [len, ni2] = readVarint(buf, idx);
                const end = ni2 + Number(len);
                if (end > buf.length)
                    throw new Error('unexpected EOF');
                return [buf.subarray(ni2, end), wireType];
            }
            else if (wireType === 0) {
                const start = idx;
                const [, ni2] = readVarint(buf, idx);
                return [buf.subarray(start, ni2), wireType];
            }
            throw new Error(`unsupported wireType ${wireType} for fastScan`);
        }
        if (wireType === 0) {
            const [, ni2] = readVarint(buf, idx);
            idx = ni2;
        }
        else if (wireType === 2) {
            const [len, ni2] = readVarint(buf, idx);
            idx = ni2 + Number(len);
        }
        else
            throw new Error(`unhandled wireType ${wireType} in fastScan skip`);
    }
    throw new Error(`field ${targetFieldNum} not found`);
}
export class UserProfile {
    userId = 0;
    username = "";
    email = "";
    constructor(init) {
        if (init) {
            Object.assign(this, init);
        }
    }
    marshalFlatBuffers() {
        const encoder = new TextEncoder();
        let dynamicSize = 0;
        const enc_username = this.username ? encoder.encode(this.username) : new Uint8Array(0);
        if (this.username) {
            dynamicSize += 4 + enc_username.length;
        }
        const enc_email = this.email ? encoder.encode(this.email) : new Uint8Array(0);
        if (this.email) {
            dynamicSize += 4 + enc_email.length;
        }
        const tableSize = 24;
        const vtableSize = 10;
        const totalSize = 4 + tableSize + dynamicSize + vtableSize;
        const buf = new Uint8Array(totalSize);
        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        // Root offset pointing to root table (always 4)
        view.setUint32(0, 4, true);
        // Write vtable offset at buf[4:8]
        const vtableStart = 4 + tableSize + dynamicSize;
        const vtableOffset = vtableStart - 4;
        view.setInt32(4, vtableOffset, true);
        let currentStringOffset = 4 + 24;
        view.setBigInt64(12, BigInt(this.userId || 0), true);
        if (this.username) {
            const relOffset = currentStringOffset - 20;
            view.setUint32(20, relOffset, true);
            view.setUint32(currentStringOffset, enc_username.length, true);
            buf.set(enc_username, currentStringOffset + 4);
            currentStringOffset += 4 + enc_username.length;
        }
        if (this.email) {
            const relOffset = currentStringOffset - 24;
            view.setUint32(24, relOffset, true);
            view.setUint32(currentStringOffset, enc_email.length, true);
            buf.set(enc_email, currentStringOffset + 4);
            currentStringOffset += 4 + enc_email.length;
        }
        // Write vtable
        view.setUint16(vtableStart, vtableSize, true);
        view.setUint16(vtableStart + 2, tableSize, true);
        if (this.userId !== undefined) {
            view.setUint16(vtableStart + 4, 8, true);
        }
        if (this.username !== undefined) {
            view.setUint16(vtableStart + 6, 16, true);
        }
        if (this.email !== undefined) {
            view.setUint16(vtableStart + 8, 20, true);
        }
        return buf;
    }
    static unmarshalFlatBuffers(buf) {
        const decoder = new TextDecoder();
        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        if (buf.length < 8) {
            throw new Error('flatbuffers: buffer too small');
        }
        const rootOffset = view.getUint32(0, true);
        if (rootOffset + 4 > buf.length) {
            throw new Error('flatbuffers: invalid root offset');
        }
        const vtableOffset = view.getInt32(rootOffset, true);
        const vtableStart = rootOffset + vtableOffset;
        if (vtableStart < 0 || vtableStart + 4 > buf.length) {
            throw new Error('flatbuffers: invalid vtable offset');
        }
        const vtableSize = view.getUint16(vtableStart, true);
        const result = new UserProfile();
        if (4 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 4, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
                if (absOffset + 8 <= buf.length) {
                    result.userId = Number(view.getBigInt64(absOffset, true));
                }
            }
        }
        if (6 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 6, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
                if (absOffset + 4 <= buf.length) {
                    const relOffset = view.getUint32(absOffset, true);
                    const strStart = absOffset + relOffset;
                    if (strStart + 4 <= buf.length) {
                        const strLen = view.getUint32(strStart, true);
                        if (strStart + 4 + strLen <= buf.length) {
                            result.username = decoder.decode(buf.subarray(strStart + 4, strStart + 4 + strLen));
                        }
                    }
                }
            }
        }
        if (8 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 8, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
                if (absOffset + 4 <= buf.length) {
                    const relOffset = view.getUint32(absOffset, true);
                    const strStart = absOffset + relOffset;
                    if (strStart + 4 <= buf.length) {
                        const strLen = view.getUint32(strStart, true);
                        if (strStart + 4 + strLen <= buf.length) {
                            result.email = decoder.decode(buf.subarray(strStart + 4, strStart + 4 + strLen));
                        }
                    }
                }
            }
        }
        return result;
    }
    static transpileProtobufToThriftCompact(input) {
        const out = [];
        let idx = 0;
        let lastField = 0;
        while (idx < input.length) {
            const [tag, ni] = readVarint(input, idx);
            idx = ni;
            const fieldNum = Number(tag >> BigInt(3));
            const wireType = Number(tag & BigInt(7));
            switch (fieldNum) {
                case 1: {
                    const [rawVal, ni2] = readVarint(input, idx);
                    idx = ni2;
                    const delta1 = 1 - lastField;
                    if (delta1 > 0 && delta1 <= 15) {
                        out.push((delta1 << 4) | 0x06);
                    }
                    else {
                        out.push(0x06);
                        writeThriftI16(out, 1);
                    }
                    const zz = (rawVal << BigInt(1)) ^ (rawVal >> BigInt(63));
                    writeThriftVarint(out, zz);
                    lastField = 1;
                    break;
                }
                case 2: {
                    const [strLen, ni2] = readVarint(input, idx);
                    idx = ni2;
                    const strBytes = input.subarray(idx, idx + Number(strLen));
                    idx += Number(strLen);
                    const delta2 = 2 - lastField;
                    if (delta2 > 0 && delta2 <= 15) {
                        out.push((delta2 << 4) | 0x08);
                    }
                    else {
                        out.push(0x08);
                        writeThriftI16(out, 2);
                    }
                    writeThriftVarint(out, strLen);
                    for (let i = 0; i < strBytes.length; i++)
                        out.push(strBytes[i]);
                    lastField = 2;
                    break;
                }
                case 3: {
                    const [strLen, ni2] = readVarint(input, idx);
                    idx = ni2;
                    const strBytes = input.subarray(idx, idx + Number(strLen));
                    idx += Number(strLen);
                    const delta3 = 3 - lastField;
                    if (delta3 > 0 && delta3 <= 15) {
                        out.push((delta3 << 4) | 0x08);
                    }
                    else {
                        out.push(0x08);
                        writeThriftI16(out, 3);
                    }
                    writeThriftVarint(out, strLen);
                    for (let i = 0; i < strBytes.length; i++)
                        out.push(strBytes[i]);
                    lastField = 3;
                    break;
                }
                default:
                    if (wireType === 0) {
                        const [, ni2] = readVarint(input, idx);
                        idx = ni2;
                    }
                    else if (wireType === 2) {
                        const [l, ni2] = readVarint(input, idx);
                        idx = ni2 + Number(l);
                    }
                    break;
            }
        }
        out.push(0); // Thrift STOP
        return new Uint8Array(out);
    }
}
export class LazyUserProfile {
    raw;
    constructor(raw) { this.raw = raw; }
    getUserId() { const [b,] = fastScanField(this.raw, 1); const [v,] = readVarint(b, 0); return Number(v); }
    getUsername() { const [b,] = fastScanField(this.raw, 2); return new TextDecoder().decode(b); }
    getEmail() { const [b,] = fastScanField(this.raw, 3); return new TextDecoder().decode(b); }
}
