// Automatically generated by Helix RPC. DO NOT EDIT.

export class UserProfile {
    public userId: number = 0;
    public username: string = "";
    public email: string = "";

    constructor(init?: Partial<UserProfile>) {
        if (init) {
            Object.assign(this, init);
        }
    }

    public marshalFlatBuffers(): Uint8Array {
        const encoder = new TextEncoder();
        let dynamicSize = 0;
        const enc_username = this.username ? encoder.encode(this.username) : new Uint8Array(0);
        if (this.username) {
            dynamicSize += 4 + enc_username.length;
        }
        const enc_email = this.email ? encoder.encode(this.email) : new Uint8Array(0);
        if (this.email) {
            dynamicSize += 4 + enc_email.length;
        }
        const tableSize = 24;
        const vtableSize = 10;
        const totalSize = 4 + tableSize + dynamicSize + vtableSize;
        const buf = new Uint8Array(totalSize);
        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        
        // Root offset pointing to root table (always 4)
        view.setUint32(0, 4, true);
        
        // Write vtable offset at buf[4:8]
        const vtableStart = 4 + tableSize + dynamicSize;
        const vtableOffset = vtableStart - 4;
        view.setInt32(4, vtableOffset, true);
        
        let currentStringOffset = 4 + 24;
        view.setBigInt64(12, BigInt(this.userId || 0), true);
        if (this.username) {
            const relOffset = currentStringOffset - 20;
            view.setUint32(20, relOffset, true);
            view.setUint32(currentStringOffset, enc_username.length, true);
            buf.set(enc_username, currentStringOffset + 4);
            currentStringOffset += 4 + enc_username.length;
        }
        if (this.email) {
            const relOffset = currentStringOffset - 24;
            view.setUint32(24, relOffset, true);
            view.setUint32(currentStringOffset, enc_email.length, true);
            buf.set(enc_email, currentStringOffset + 4);
            currentStringOffset += 4 + enc_email.length;
        }
        // Write vtable
        view.setUint16(vtableStart, vtableSize, true);
        view.setUint16(vtableStart + 2, tableSize, true);
        if (this.userId !== undefined) {
            view.setUint16(vtableStart + 4, 8, true);
        }
        if (this.username !== undefined) {
            view.setUint16(vtableStart + 6, 16, true);
        }
        if (this.email !== undefined) {
            view.setUint16(vtableStart + 8, 20, true);
        }
        return buf;
    }

    public static unmarshalFlatBuffers(buf: Uint8Array): UserProfile {
        const decoder = new TextDecoder();
        const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
        if (buf.length < 8) {
            throw new Error('flatbuffers: buffer too small');
        }
        const rootOffset = view.getUint32(0, true);
        if (rootOffset + 4 > buf.length) {
            throw new Error('flatbuffers: invalid root offset');
        }
        const vtableOffset = view.getInt32(rootOffset, true);
        const vtableStart = rootOffset + vtableOffset;
        if (vtableStart < 0 || vtableStart + 4 > buf.length) {
            throw new Error('flatbuffers: invalid vtable offset');
        }
        const vtableSize = view.getUint16(vtableStart, true);
        const result = new UserProfile();
        
        if (4 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 4, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
                if (absOffset + 8 <= buf.length) {
                    result.userId = Number(view.getBigInt64(absOffset, true));
                }
            }
        }
        if (6 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 6, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
                if (absOffset + 4 <= buf.length) {
                    const relOffset = view.getUint32(absOffset, true);
                    const strStart = absOffset + relOffset;
                    if (strStart + 4 <= buf.length) {
                        const strLen = view.getUint32(strStart, true);
                        if (strStart + 4 + strLen <= buf.length) {
                            result.username = decoder.decode(buf.subarray(strStart + 4, strStart + 4 + strLen));
                        }
                    }
                }
            }
        }
        if (8 + 2 <= vtableSize) {
            const foffset = view.getUint16(vtableStart + 8, true);
            if (foffset > 0) {
                const absOffset = rootOffset + foffset;
                if (absOffset + 4 <= buf.length) {
                    const relOffset = view.getUint32(absOffset, true);
                    const strStart = absOffset + relOffset;
                    if (strStart + 4 <= buf.length) {
                        const strLen = view.getUint32(strStart, true);
                        if (strStart + 4 + strLen <= buf.length) {
                            result.email = decoder.decode(buf.subarray(strStart + 4, strStart + 4 + strLen));
                        }
                    }
                }
            }
        }
        return result;
    }
}

